(* Generated by tools/extract_profession.py -- do not edit *)

open Campaign_types

type profession = {
  id: string;
  name_text: string;
  desc_text: string;
  portraits: portrait list;
  skills: skill_affinities;
  starts: start_stats;
  start_city: string;
  life_per_level: int;
  sprite: string;
  xp: xp_table;
  spells_by_level: spell_table;
}

let professions = [
  {
    id = "PDRU";
    name_text = "[PROF_PDRU_NAME]";
    desc_text = "[PROF_PDRU_DESC]";
    portraits = [
      {
        file = "Assets\\Portraits\\Portrait_PC_Druid0.png";
        sex = 0;
        sprite = "ZDRU";
        age = 1;
      };
      {
        file = "Assets\\Portraits\\Portrait_PC_FDruid0.png";
        sex = 1;
        sprite = "ZDRF";
        age = 0;
      };
      {
        file = "Assets\\Portraits\\Portrait_PC_Druid1.png";
        sex = 0;
        sprite = "ZDR0";
        age = 0;
      };
      {
        file = "Assets\\Portraits\\Portrait_PC_FDruid1.png";
        sex = 1;
        sprite = "ZD0F";
        age = 1;
      };
    ];
    skills = { earth = 1; fire = 3; air = 1; water = 2; battle = 3; cunning = 2; morale = 2 };
    starts = { earth = 2; fire = 1; air = 3; water = 2; battle = 0; cunning = 1; morale = 0; gold = 100 };
    start_city = "CBAR";
    life_per_level = 2;
    sprite = "ZDRU";
    xp = { leveladd = 5000; levels = [ (1, 0); (2, 40); (3, 80); (4, 150); (5, 250); (6, 400); (7, 600); (8, 900); (9, 1250); (10, 1700); (11, 2200); (12, 2800); (13, 3500); (14, 4250); (15, 5000); (16, 5800); (17, 6600); (18, 7500); (19, 8500); (20, 9500); (21, 10600); (22, 11700); (23, 12800); (24, 13900); (25, 15000); (26, 16200); (27, 17400); (28, 18600); (29, 19800); (30, 21000); (31, 22300); (32, 23600); (33, 24900); (34, 26200); (35, 27500); (36, 28900); (37, 30300); (38, 31700); (39, 33100); (40, 34500); (41, 36000); (42, 37600); (43, 39300); (44, 41000); (45, 42800); (46, 44700); (47, 46700); (48, 49000); (49, 52000); (50, 55000) ] };
    spells_by_level = [ (1, "SGEM"); (2, "SCHA"); (3, "SENT"); (4, "SCLM"); (5, "SFOF"); (6, "SCLI"); (7, "SEVA"); (8, "SGOW"); (10, "SSAN"); (12, "SWOT"); (15, "SEPO"); (20, "SWHI"); (25, "SLIS"); (30, "SRNC"); (40, "SCLE"); (50, "SNWR") ];
  };
  {
    id = "PKNI";
    name_text = "[PROF_PKNI_NAME]";
    desc_text = "[PROF_PKNI_DESC]";
    portraits = [
      {
        file = "Assets\\Portraits\\Portrait_PC_Knight0.png";
        sex = 0;
        sprite = "ZKNI";
        age = 1;
      };
      {
        file = "Assets\\Portraits\\Portrait_PC_FKnight0.png";
        sex = 1;
        sprite = "ZKNF";
        age = 1;
      };
      {
        file = "Assets\\Portraits\\Portrait_PC_Knight1.png";
        sex = 0;
        sprite = "ZKN0";
        age = 0;
      };
      {
        file = "Assets\\Portraits\\Portrait_PC_FKnight1.png";
        sex = 1;
        sprite = "ZK0F";
        age = 0;
      };
    ];
    skills = { earth = 3; fire = 2; air = 2; water = 2; battle = 1; cunning = 3; morale = 1 };
    starts = { earth = 0; fire = 0; air = 1; water = 2; battle = 2; cunning = 1; morale = 3; gold = 100 };
    start_city = "CBAR";
    life_per_level = 2;
    sprite = "ZKNI";
    xp = { leveladd = 5000; levels = [ (1, 0); (2, 40); (3, 80); (4, 150); (5, 250); (6, 400); (7, 600); (8, 900); (9, 1250); (10, 1700); (11, 2200); (12, 2800); (13, 3500); (14, 4250); (15, 5000); (16, 5800); (17, 6600); (18, 7500); (19, 8500); (20, 9500); (21, 10600); (22, 11700); (23, 12800); (24, 13900); (25, 15000); (26, 16200); (27, 17400); (28, 18600); (29, 19800); (30, 21000); (31, 22300); (32, 23600); (33, 24900); (34, 26200); (35, 27500); (36, 28900); (37, 30300); (38, 31700); (39, 33100); (40, 34500); (41, 36000); (42, 37600); (43, 39300); (44, 41000); (45, 42800); (46, 44700); (47, 46700); (48, 49000); (49, 52000); (50, 55000) ] };
    spells_by_level = [ (1, "STHR"); (2, "SDIV"); (3, "SCHL"); (4, "SSTU"); (5, "STRM"); (7, "SFAV"); (8, "SCOU"); (10, "SPRO"); (12, "SCHG"); (15, "SVIG"); (20, "SKLO"); (30, "SSOS"); (40, "SCHV"); (50, "SPAU") ];
  };
  {
    id = "PWAR";
    name_text = "[PROF_PWAR_NAME]";
    desc_text = "[PROF_PWAR_DESC]";
    portraits = [
      {
        file = "Assets\\Portraits\\Portrait_PC_Warrior0.png";
        sex = 0;
        sprite = "ZWAR";
        age = 1;
      };
      {
        file = "Assets\\Portraits\\Portrait_PC_FWarrior0.png";
        sex = 1;
        sprite = "ZWRF";
        age = 0;
      };
      {
        file = "Assets\\Portraits\\Portrait_PC_Warrior1.png";
        sex = 0;
        sprite = "ZWR0";
        age = 0;
      };
      {
        file = "Assets\\Portraits\\Portrait_PC_FWarrior1.png";
        sex = 1;
        sprite = "ZW0F";
        age = 1;
      };
    ];
    skills = { earth = 3; fire = 1; air = 2; water = 3; battle = 1; cunning = 2; morale = 2 };
    starts = { earth = 1; fire = 2; air = 0; water = 0; battle = 3; cunning = 2; morale = 1; gold = 100 };
    start_city = "CBAR";
    life_per_level = 2;
    sprite = "ZWAR";
    xp = { leveladd = 5000; levels = [ (1, 0); (2, 40); (3, 80); (4, 150); (5, 250); (6, 400); (7, 600); (8, 900); (9, 1250); (10, 1700); (11, 2200); (12, 2800); (13, 3500); (14, 4250); (15, 5000); (16, 5800); (17, 6600); (18, 7500); (19, 8500); (20, 9500); (21, 10600); (22, 11700); (23, 12800); (24, 13900); (25, 15000); (26, 16200); (27, 17400); (28, 18600); (29, 19800); (30, 21000); (31, 22300); (32, 23600); (33, 24900); (34, 26200); (35, 27500); (36, 28900); (37, 30300); (38, 31700); (39, 33100); (40, 34500); (41, 36000); (42, 37600); (43, 39300); (44, 41000); (45, 42800); (46, 44700); (47, 46700); (48, 49000); (49, 52000); (50, 55000) ] };
    spells_by_level = [ (1, "SBAC"); (2, "SWLO"); (3, "SSPA"); (5, "SCLV"); (7, "STHX"); (8, "SENR"); (10, "SBLU"); (15, "SSUT"); (20, "SBRA"); (30, "SDBR"); (40, "SSBL"); (50, "SREV") ];
  };
  {
    id = "PWIZ";
    name_text = "[PROF_PWIZ_NAME]";
    desc_text = "[PROF_PWIZ_DESC]";
    portraits = [
      {
        file = "Assets\\Portraits\\Portrait_PC_Wizard0.png";
        sex = 0;
        sprite = "ZWIZ";
        age = 1;
      };
      {
        file = "Assets\\Portraits\\Portrait_PC_FWizard0.png";
        sex = 1;
        sprite = "ZWIF";
        age = 0;
      };
      {
        file = "Assets\\Portraits\\Portrait_PC_Wizard1.png";
        sex = 0;
        sprite = "ZWI0";
        age = 0;
      };
      {
        file = "Assets\\Portraits\\Portrait_PC_FWizard1.png";
        sex = 1;
        sprite = "ZZ0F";
        age = 1;
      };
    ];
    skills = { earth = 2; fire = 1; air = 1; water = 2; battle = 3; cunning = 2; morale = 3 };
    starts = { earth = 1; fire = 3; air = 2; water = 0; battle = 1; cunning = 2; morale = 0; gold = 100 };
    start_city = "CBAR";
    life_per_level = 2;
    sprite = "ZWIZ";
    xp = { leveladd = 5000; levels = [ (1, 0); (2, 40); (3, 80); (4, 150); (5, 250); (6, 400); (7, 600); (8, 900); (9, 1250); (10, 1700); (11, 2200); (12, 2800); (13, 3500); (14, 4250); (15, 5000); (16, 5800); (17, 6600); (18, 7500); (19, 8500); (20, 9500); (21, 10600); (22, 11700); (23, 12800); (24, 13900); (25, 15000); (26, 16200); (27, 17400); (28, 18600); (29, 19800); (30, 21000); (31, 22300); (32, 23600); (33, 24900); (34, 26200); (35, 27500); (36, 28900); (37, 30300); (38, 31700); (39, 33100); (40, 34500); (41, 36000); (42, 37600); (43, 39300); (44, 41000); (45, 42800); (46, 44700); (47, 46700); (48, 49000); (49, 52000); (50, 55000) ] };
    spells_by_level = [ (1, "SFBO"); (2, "SCHF"); (3, "SFSH"); (4, "SHAS"); (5, "SMBU"); (6, "SHOP"); (7, "SLIG"); (8, "SHSI"); (10, "SFBA"); (12, "SWOF"); (15, "SFSK"); (20, "SCAU"); (25, "SMST"); (30, "SFOD"); (40, "SLCO"); (50, "SFLV") ];
  };
]

let profession_by_id id = List.find (fun p -> p.id = id) professions
