(* Generated by tools/extract_campaign_map.py — do not edit *)

type node_kind = City | Waypoint | Ruin

type city = {
  id: string;
  name_text: string;
  desc_text: string;
  icon: int;
  gfx_type: int;
  x: int;
  y: int;
  level: int;
  visible: bool;
  income: int;
  items: string list;
  spells: string list;
}

type waypoint = {
  id: string;
  name_text: string;
  desc_text: string;
  x: int;
  y: int;
  wtype: int;
  icon: int;
  visible: bool;
}

type ruin = {
  id: string;
  name_text: string;
  desc_text: string;
  icon: int;
  x: int;
  y: int;
  ruin_type: int;
  visible: bool;
  attach: string;
}

type road = {
  start: string;
  end_: string;
  visible: bool;
}

let cities : city list = [
  {
    id = "CBAR";
    name_text = "[CITY_CBAR_NAME]";
    desc_text = "[CITY_CBAR_DESC]";
    icon = 3;
    gfx_type = 0;
    x = 1418;
    y = 934;
    level = 0;
    visible = true;
    income = 100;
    items = [ "ITWH"; "IWLM"; "IGTS"; "IMOA" ];
    spells = [ "SCHG"; "SBSG" ];
  };
  {
    id = "CDKO";
    name_text = "[CITY_CDKO_NAME]";
    desc_text = "[CITY_CDKO_DESC]";
    icon = 20;
    gfx_type = 0;
    x = 1712;
    y = 737;
    level = 0;
    visible = false;
    income = 50;
    items = [ "ITWS"; "IWLR"; "IGTI"; "IBOI" ];
    spells = [ "SBSG"; "STHX"; "SCOU" ];
  };
  {
    id = "CDRA";
    name_text = "[CITY_CDRA_NAME]";
    desc_text = "[CITY_CDRA_DESC]";
    icon = 0;
    gfx_type = 0;
    x = 1339;
    y = 1278;
    level = 0;
    visible = false;
    income = 150;
    items = [ "ITWS"; "IWLS"; "IGTW"; "IMOA" ];
    spells = [ "SCHG" ];
  };
  {
    id = "CDRH";
    name_text = "[CITY_CDRH_NAME]";
    desc_text = "[CITY_CDRH_DESC]";
    icon = 21;
    gfx_type = 1;
    x = 1911;
    y = 490;
    level = 0;
    visible = false;
    income = 200;
    items = [ "ITWM"; "IWLM"; "IGTA"; "IFMO" ];
    spells = [ "SFBO"; "SSWP" ];
  };
  {
    id = "CEHL";
    name_text = "[CITY_CEHL_NAME]";
    desc_text = "[CITY_CEHL_DESC]";
    icon = 10;
    gfx_type = 0;
    x = 806;
    y = 475;
    level = 0;
    visible = false;
    income = 160;
    items = [ "ITWM"; "IWLM"; "IGTA"; "IMND" ];
    spells = [ "SCHM"; "SENT"; "SFRZ"; "SFBT" ];
  };
  {
    id = "CENM";
    name_text = "[CITY_CENM_NAME]";
    desc_text = "[CITY_CENM_DESC]";
    icon = 0;
    gfx_type = 0;
    x = 1202;
    y = 883;
    level = 0;
    visible = false;
    income = 150;
    items = [ "ITWS"; "IWLB"; "IGTW"; "IBOI" ];
    spells = [ "SCHG" ];
  };
  {
    id = "CGAL";
    name_text = "[CITY_CGAL_NAME]";
    desc_text = "[CITY_CGAL_DESC]";
    icon = 19;
    gfx_type = 0;
    x = 1522;
    y = 1225;
    level = 0;
    visible = false;
    income = 120;
    items = [ "ITWH"; "IWLB"; "IGTI"; "IBOI" ];
    spells = [ "SCHG"; "SBAC" ];
  };
  {
    id = "CGLK";
    name_text = "[CITY_CGLK_NAME]";
    desc_text = "[CITY_CGLK_DESC]";
    icon = 18;
    gfx_type = 1;
    x = 1929;
    y = 1271;
    level = 0;
    visible = false;
    income = 58;
    items = [ "ITWP"; "IWLS"; "IGTS"; "IBOI" ];
    spells = [ "SSTO"; "STHU" ];
  };
  {
    id = "CGRU";
    name_text = "[CITY_CGRU_NAME]";
    desc_text = "[CITY_CGRU_DESC]";
    icon = 8;
    gfx_type = 1;
    x = 1930;
    y = 1087;
    level = 0;
    visible = false;
    income = 100;
    items = [ "ITWP"; "IWLS"; "IGTS"; "IFMO" ];
    spells = [ "SCTH"; "SBAC"; "SHGO" ];
  };
  {
    id = "CHTP";
    name_text = "[CITY_CHTP_NAME]";
    desc_text = "[CITY_CHTP_DESC]";
    icon = 16;
    gfx_type = 1;
    x = 1498;
    y = 423;
    level = 0;
    visible = false;
    income = 50;
    items = [ "ITWM"; "IWLR"; "IGTW"; "IFMO" ];
    spells = [ "SCHG"; "SBAC"; "SBRA" ];
  };
  {
    id = "CHYA";
    name_text = "[CITY_CHYA_NAME]";
    desc_text = "[CITY_CHYA_DESC]";
    icon = 18;
    gfx_type = 1;
    x = 1288;
    y = 373;
    level = 0;
    visible = false;
    income = 100;
    items = [ "ITWS"; "IWLB"; "IGTS"; "IGPK" ];
    spells = [ "SHWL"; "SSBD" ];
  };
  {
    id = "CJAK";
    name_text = "[CITY_CJAK_NAME]";
    desc_text = "[CITY_CJAK_DESC]";
    icon = 15;
    gfx_type = 1;
    x = 1885;
    y = 213;
    level = 0;
    visible = false;
    income = 75;
    items = [ "ITWH"; "IWLM"; "IGTS"; "IMOA" ];
    spells = [ "SFRZ"; "SFBT" ];
  };
  {
    id = "CJOK";
    name_text = "[CITY_CJOK_NAME]";
    desc_text = "[CITY_CJOK_DESC]";
    icon = 15;
    gfx_type = 1;
    x = 1823;
    y = 320;
    level = 0;
    visible = false;
    income = 75;
    items = [ "ITWH"; "IWLM"; "IGTS"; "IFMO" ];
    spells = [ "SBUR"; "SROF"; "SFSK" ];
  };
  {
    id = "CKUN";
    name_text = "[CITY_CKUN_NAME]";
    desc_text = "[CITY_CKUN_DESC]";
    icon = 14;
    gfx_type = 1;
    x = 777;
    y = 135;
    level = 0;
    visible = false;
    income = 150;
    items = [ "ITWH"; "IWLM"; "IGTA"; "IFMO" ];
    spells = [ "SFSK"; "SEPO"; "SMST"; "SMBU" ];
  };
  {
    id = "CLBC";
    name_text = "[CITY_CLBC_NAME]";
    desc_text = "[CITY_CLBC_DESC]";
    icon = 4;
    gfx_type = 1;
    x = 955;
    y = 175;
    level = 0;
    visible = false;
    income = 200;
    items = [ "ITWH"; "IWLM"; "IGTA"; "IMND" ];
    spells = [ "SWTD"; "SSPF"; "SBST"; "SDBR" ];
  };
  {
    id = "COHT";
    name_text = "[CITY_COHT_NAME]";
    desc_text = "[CITY_COHT_DESC]";
    icon = 16;
    gfx_type = 1;
    x = 1624;
    y = 179;
    level = 0;
    visible = false;
    income = 150;
    items = [ "ITWP"; "IWLM"; "IGTA"; "IFMO" ];
    spells = [ "SBRA"; "SCHG"; "SROF" ];
  };
  {
    id = "CSIL";
    name_text = "[CITY_CSIL_NAME]";
    desc_text = "[CITY_CSIL_DESC]";
    icon = 10;
    gfx_type = 0;
    x = 1250;
    y = 776;
    level = 0;
    visible = false;
    income = 90;
    items = [ "ITWM"; "IWLS"; "IGTW"; "IMND" ];
    spells = [ "SENT"; "SWOT" ];
  };
  {
    id = "CTRA";
    name_text = "[CITY_CTRA_NAME]";
    desc_text = "[CITY_CTRA_DESC]";
    icon = 8;
    gfx_type = 1;
    x = 1251;
    y = 1164;
    level = 0;
    visible = false;
    income = 100;
    items = [ "ITWS"; "IWLB"; "IGTW"; "IBOI" ];
    spells = [ "SCHG" ];
  };
  {
    id = "CTSK";
    name_text = "[CITY_CTSK_NAME]";
    desc_text = "[CITY_CTSK_DESC]";
    icon = 18;
    gfx_type = 1;
    x = 1469;
    y = 228;
    level = 0;
    visible = false;
    income = 100;
    items = [ "ITWP"; "IWLB"; "IGTS"; "IBOI" ];
    spells = [ "SCOU"; "SBSG" ];
  };
  {
    id = "CYLA";
    name_text = "[CITY_CYLA_NAME]";
    desc_text = "[CITY_CYLA_DESC]";
    icon = 23;
    gfx_type = 0;
    x = 1061;
    y = 438;
    level = 0;
    visible = false;
    income = 75;
    items = [ "ITWM"; "IWLS"; "IGTW"; "IMND" ];
    spells = [ "SENT"; "SCHM" ];
  };
]

let waypoints : waypoint list = [
  {
    id = "WELE";
    name_text = "[WAYPOINT_WELE_NAME]";
    desc_text = "[WAYPOINT_WELE_DESC]";
    x = 1286;
    y = 970;
    wtype = 0;
    icon = 9;
    visible = true;
  };
  {
    id = "WGIL";
    name_text = "[WAYPOINT_WGIL_NAME]";
    desc_text = "[WAYPOINT_WGIL_DESC]";
    x = 1434;
    y = 1048;
    wtype = 0;
    icon = 9;
    visible = true;
  };
  {
    id = "WSIR";
    name_text = "[WAYPOINT_WSIR_NAME]";
    desc_text = "[WAYPOINT_WSIR_DESC]";
    x = 1543;
    y = 949;
    wtype = 0;
    icon = 9;
    visible = true;
  };
  {
    id = "WTHR";
    name_text = "[WAYPOINT_WTHR_NAME]";
    desc_text = "[WAYPOINT_WTHR_DESC]";
    x = 1462;
    y = 831;
    wtype = 0;
    icon = 9;
    visible = true;
  };
  {
    id = "WRAR";
    name_text = "[WAYPOINT_WRAR_NAME]";
    desc_text = "[WAYPOINT_WRAR_DESC]";
    x = 1576;
    y = 1304;
    wtype = 3;
    icon = 17;
    visible = false;
  };
  {
    id = "WMAE";
    name_text = "[WAYPOINT_WMAE_NAME]";
    desc_text = "[WAYPOINT_WMAE_DESC]";
    x = 1636;
    y = 1237;
    wtype = 0;
    icon = 22;
    visible = false;
  };
  {
    id = "WAPS";
    name_text = "[WAYPOINT_WAPS_NAME]";
    desc_text = "[WAYPOINT_WAPS_DESC]";
    x = 1532;
    y = 1117;
    wtype = 2;
    icon = 7;
    visible = false;
  };
  {
    id = "WSKE";
    name_text = "[WAYPOINT_WSKE_NAME]";
    desc_text = "[WAYPOINT_WSKE_DESC]";
    x = 1428;
    y = 1240;
    wtype = 0;
    icon = 9;
    visible = false;
  };
  {
    id = "WBTH";
    name_text = "[WAYPOINT_WBTH_NAME]";
    desc_text = "[WAYPOINT_WBTH_DESC]";
    x = 1127;
    y = 1058;
    wtype = 1;
    icon = 6;
    visible = false;
  };
  {
    id = "WHPS";
    name_text = "[WAYPOINT_WHPS_NAME]";
    desc_text = "[WAYPOINT_WHPS_DESC]";
    x = 1515;
    y = 746;
    wtype = 0;
    icon = 9;
    visible = false;
  };
  {
    id = "WALF";
    name_text = "[WAYPOINT_WALF_NAME]";
    desc_text = "[WAYPOINT_WALF_DESC]";
    x = 1342;
    y = 728;
    wtype = 1;
    icon = 6;
    visible = false;
  };
  {
    id = "WRMO";
    name_text = "[WAYPOINT_WRMO_NAME]";
    desc_text = "[WAYPOINT_WRMO_DESC]";
    x = 1772;
    y = 889;
    wtype = 1;
    icon = 18;
    visible = false;
  };
  {
    id = "WWSK";
    name_text = "[WAYPOINT_WWSK_NAME]";
    desc_text = "[WAYPOINT_WWSK_DESC]";
    x = 1871;
    y = 753;
    wtype = 1;
    icon = 18;
    visible = false;
  };
  {
    id = "WBHE";
    name_text = "[WAYPOINT_WBHE_NAME]";
    desc_text = "[WAYPOINT_WBHE_DESC]";
    x = 1867;
    y = 849;
    wtype = 1;
    icon = 18;
    visible = false;
  };
  {
    id = "WSFA";
    name_text = "[WAYPOINT_WSFA_NAME]";
    desc_text = "[WAYPOINT_WSFA_DESC]";
    x = 1925;
    y = 971;
    wtype = 1;
    icon = 5;
    visible = false;
  };
  {
    id = "WGRK";
    name_text = "[WAYPOINT_WGRK_NAME]";
    desc_text = "[WAYPOINT_WGRK_DESC]";
    x = 1899;
    y = 1177;
    wtype = 0;
    icon = 9;
    visible = false;
  };
  {
    id = "WDRT";
    name_text = "[WAYPOINT_WDRT_NAME]";
    desc_text = "[WAYPOINT_WDRT_DESC]";
    x = 1817;
    y = 1276;
    wtype = 0;
    icon = 15;
    visible = false;
  };
  {
    id = "WNKR";
    name_text = "[WAYPOINT_WNKR_NAME]";
    desc_text = "[WAYPOINT_WNKR_DESC]";
    x = 1687;
    y = 636;
    wtype = 3;
    icon = 17;
    visible = false;
  };
  {
    id = "WDPS";
    name_text = "[WAYPOINT_WDPS_NAME]";
    desc_text = "[WAYPOINT_WDPS_DESC]";
    x = 1791;
    y = 541;
    wtype = 2;
    icon = 7;
    visible = false;
  };
  {
    id = "WVOK";
    name_text = "[WAYPOINT_WVOK_NAME]";
    desc_text = "[WAYPOINT_WVOK_DESC]";
    x = 1623;
    y = 586;
    wtype = 3;
    icon = 1;
    visible = false;
  };
  {
    id = "WHBG";
    name_text = "[WAYPOINT_WHBG_NAME]";
    desc_text = "[WAYPOINT_WHBG_DESC]";
    x = 1652;
    y = 503;
    wtype = 0;
    icon = 9;
    visible = false;
  };
  {
    id = "WPIK";
    name_text = "[WAYPOINT_WPIK_NAME]";
    desc_text = "[WAYPOINT_WPIK_DESC]";
    x = 1388;
    y = 308;
    wtype = 3;
    icon = 17;
    visible = false;
  };
  {
    id = "WGWK";
    name_text = "[WAYPOINT_WGWK_NAME]";
    desc_text = "[WAYPOINT_WGWK_DESC]";
    x = 1705;
    y = 243;
    wtype = 2;
    icon = 7;
    visible = false;
  };
  {
    id = "WSHD";
    name_text = "[WAYPOINT_WSHD_NAME]";
    desc_text = "[WAYPOINT_WSHD_DESC]";
    x = 1593;
    y = 255;
    wtype = 1;
    icon = 18;
    visible = false;
  };
  {
    id = "WWRT";
    name_text = "[WAYPOINT_WWRT_NAME]";
    desc_text = "[WAYPOINT_WWRT_DESC]";
    x = 1408;
    y = 158;
    wtype = 1;
    icon = 18;
    visible = false;
  };
  {
    id = "WPAR";
    name_text = "[WAYPOINT_WPAR_NAME]";
    desc_text = "[WAYPOINT_WPAR_DESC]";
    x = 1376;
    y = 577;
    wtype = 1;
    icon = 6;
    visible = false;
  };
  {
    id = "WGGP";
    name_text = "[WAYPOINT_WGGP_NAME]";
    desc_text = "[WAYPOINT_WGGP_DESC]";
    x = 1237;
    y = 147;
    wtype = 3;
    icon = 17;
    visible = false;
  };
  {
    id = "WSGK";
    name_text = "[WAYPOINT_WSGK_NAME]";
    desc_text = "[WAYPOINT_WSGK_DESC]";
    x = 1080;
    y = 314;
    wtype = 0;
    icon = 9;
    visible = false;
  };
  {
    id = "WIGK";
    name_text = "[WAYPOINT_WIGK_NAME]";
    desc_text = "[WAYPOINT_WIGK_DESC]";
    x = 891;
    y = 310;
    wtype = 0;
    icon = 9;
    visible = false;
  };
  {
    id = "WRAG";
    name_text = "[WAYPOINT_WRAG_NAME]";
    desc_text = "[WAYPOINT_WRAG_DESC]";
    x = 650;
    y = 528;
    wtype = 3;
    icon = 17;
    visible = false;
  };
  {
    id = "WETO";
    name_text = "[WAYPOINT_WETO_NAME]";
    desc_text = "[WAYPOINT_WETO_DESC]";
    x = 1174;
    y = 507;
    wtype = 0;
    icon = 9;
    visible = false;
  };
  {
    id = "WGRW";
    name_text = "[WAYPOINT_WGRW_NAME]";
    desc_text = "[WAYPOINT_WGRW_DESC]";
    x = 1151;
    y = 180;
    wtype = 1;
    icon = 18;
    visible = false;
  };
  {
    id = "WSOI";
    name_text = "[WAYPOINT_WSOI_NAME]";
    desc_text = "[WAYPOINT_WSOI_DESC]";
    x = 1055;
    y = 139;
    wtype = 2;
    icon = 7;
    visible = false;
  };
  {
    id = "WLOB";
    name_text = "[WAYPOINT_WLOB_NAME]";
    desc_text = "[WAYPOINT_WLOB_DESC]";
    x = 864;
    y = 225;
    wtype = 3;
    icon = 17;
    visible = false;
  };
  {
    id = "WTIR";
    name_text = "[WAYPOINT_WTIR_NAME]";
    desc_text = "[WAYPOINT_WTIR_DESC]";
    x = 949;
    y = 482;
    wtype = 0;
    icon = 9;
    visible = false;
  };
  {
    id = "WSMZ";
    name_text = "[WAYPOINT_WSMZ_NAME]";
    desc_text = "[WAYPOINT_WSMZ_DESC]";
    x = 1308;
    y = 219;
    wtype = 2;
    icon = 7;
    visible = false;
  };
  {
    id = "WBBR";
    name_text = "[WAYPOINT_WBBR_NAME]";
    desc_text = "[WAYPOINT_WBBR_DESC]";
    x = 1063;
    y = 225;
    wtype = 0;
    icon = 5;
    visible = false;
  };
  {
    id = "WWAS";
    name_text = "[WAYPOINT_WWAS_NAME]";
    desc_text = "[WAYPOINT_WWAS_DESC]";
    x = 632;
    y = 147;
    wtype = 3;
    icon = 17;
    visible = false;
  };
  {
    id = "WHVA";
    name_text = "[WAYPOINT_WHVA_NAME]";
    desc_text = "[WAYPOINT_WHVA_DESC]";
    x = 620;
    y = 259;
    wtype = 2;
    icon = 7;
    visible = false;
  };
  {
    id = "WBSP";
    name_text = "[WAYPOINT_WBSP_NAME]";
    desc_text = "[WAYPOINT_WBSP_DESC]";
    x = 771;
    y = 235;
    wtype = 2;
    icon = 7;
    visible = false;
  };
]

let ruins : ruin list = [
  {
    id = "RATO";
    name_text = "[RUIN_RATO_NAME]";
    desc_text = "[RUIN_RATO_DESC]";
    icon = 0;
    x = 1481;
    y = 334;
    ruin_type = 7;
    visible = false;
    attach = "CTSK";
  };
  {
    id = "RBST";
    name_text = "[RUIN_RBST_NAME]";
    desc_text = "[RUIN_RBST_DESC]";
    icon = 13;
    x = 1149;
    y = 266;
    ruin_type = 0;
    visible = false;
    attach = "WSGK";
  };
  {
    id = "RCBL";
    name_text = "[RUIN_RCBL_NAME]";
    desc_text = "[RUIN_RCBL_DESC]";
    icon = 2;
    x = 1977;
    y = 421;
    ruin_type = 2;
    visible = false;
    attach = "CDRH";
  };
  {
    id = "RDCV";
    name_text = "[RUIN_RDCV_NAME]";
    desc_text = "[RUIN_RDCV_DESC]";
    icon = 2;
    x = 1359;
    y = 1189;
    ruin_type = 2;
    visible = false;
    attach = "CDRA";
  };
  {
    id = "RDGV";
    name_text = "[RUIN_RDGV_NAME]";
    desc_text = "[RUIN_RDGV_DESC]";
    icon = 12;
    x = 1713;
    y = 451;
    ruin_type = 5;
    visible = false;
    attach = "WDPS";
  };
  {
    id = "RDPS";
    name_text = "[RUIN_RDPS_NAME]";
    desc_text = "[RUIN_RDPS_DESC]";
    icon = 12;
    x = 1215;
    y = 1064;
    ruin_type = 5;
    visible = false;
    attach = "WBTH";
  };
  {
    id = "RDSH";
    name_text = "[RUIN_RDSH_NAME]";
    desc_text = "[RUIN_RDSH_DESC]";
    icon = 11;
    x = 776;
    y = 389;
    ruin_type = 4;
    visible = false;
    attach = "WIGK";
  };
  {
    id = "RDST";
    name_text = "[RUIN_RDST_NAME]";
    desc_text = "[RUIN_RDST_DESC]";
    icon = 1;
    x = 889;
    y = 150;
    ruin_type = 6;
    visible = false;
    attach = "CLBC";
  };
  {
    id = "REGB";
    name_text = "[RUIN_REGB_NAME]";
    desc_text = "[RUIN_REGB_DESC]";
    icon = 13;
    x = 1638;
    y = 1164;
    ruin_type = 0;
    visible = false;
    attach = "WMAE";
  };
  {
    id = "RGSE";
    name_text = "[RUIN_RGSE_NAME]";
    desc_text = "[RUIN_RGSE_DESC]";
    icon = 1;
    x = 1384;
    y = 1062;
    ruin_type = 1;
    visible = false;
    attach = "WGIL";
  };
  {
    id = "RHAG";
    name_text = "[RUIN_RHAG_NAME]";
    desc_text = "[RUIN_RHAG_DESC]";
    icon = 13;
    x = 636;
    y = 421;
    ruin_type = 0;
    visible = false;
    attach = "WRAG";
  };
  {
    id = "RICM";
    name_text = "[RUIN_RICM_NAME]";
    desc_text = "[RUIN_RICM_DESC]";
    icon = 2;
    x = 988;
    y = 341;
    ruin_type = 2;
    visible = false;
    attach = "WIGK";
  };
  {
    id = "RMOL";
    name_text = "[RUIN_RMOL_NAME]";
    desc_text = "[RUIN_RMOL_DESC]";
    icon = 2;
    x = 1982;
    y = 617;
    ruin_type = 2;
    visible = false;
    attach = "CDRH";
  };
  {
    id = "ROOU";
    name_text = "[RUIN_ROOU_NAME]";
    desc_text = "[RUIN_ROOU_DESC]";
    icon = 5;
    x = 1207;
    y = 998;
    ruin_type = 6;
    visible = false;
    attach = "WBTH";
  };
  {
    id = "ROTO";
    name_text = "[RUIN_ROTO_NAME]";
    desc_text = "[RUIN_ROTO_DESC]";
    icon = 5;
    x = 1519;
    y = 871;
    ruin_type = 3;
    visible = false;
    attach = "WTHR";
  };
  {
    id = "RSCC";
    name_text = "[RUIN_RSCC_NAME]";
    desc_text = "[RUIN_RSCC_DESC]";
    icon = 2;
    x = 1616;
    y = 677;
    ruin_type = 2;
    visible = false;
    attach = "CDKO";
  };
  {
    id = "RSCV";
    name_text = "[RUIN_RSCV_NAME]";
    desc_text = "[RUIN_RSCV_DESC]";
    icon = 2;
    x = 1274;
    y = 635;
    ruin_type = 2;
    visible = false;
    attach = "WALF";
  };
  {
    id = "RSKM";
    name_text = "[RUIN_RSKM_NAME]";
    desc_text = "[RUIN_RSKM_DESC]";
    icon = 13;
    x = 1486;
    y = 1339;
    ruin_type = 0;
    visible = false;
    attach = "WSKE";
  };
  {
    id = "RSLV";
    name_text = "[RUIN_RSLV_NAME]";
    desc_text = "[RUIN_RSLV_DESC]";
    icon = 5;
    x = 1145;
    y = 1165;
    ruin_type = 3;
    visible = false;
    attach = "WBTH";
  };
  {
    id = "RSTR";
    name_text = "[RUIN_RSTR_NAME]";
    desc_text = "[RUIN_RSTR_DESC]";
    icon = 11;
    x = 1303;
    y = 906;
    ruin_type = 4;
    visible = false;
    attach = "WELE";
  };
  {
    id = "RTHC";
    name_text = "[RUIN_RTHC_NAME]";
    desc_text = "[RUIN_RTHC_DESC]";
    icon = 1;
    x = 1407;
    y = 851;
    ruin_type = 1;
    visible = false;
    attach = "WTHR";
  };
  {
    id = "RTLH";
    name_text = "[RUIN_RTLH_NAME]";
    desc_text = "[RUIN_RTLH_DESC]";
    icon = 2;
    x = 1429;
    y = 709;
    ruin_type = 2;
    visible = false;
    attach = "WALF";
  };
  {
    id = "RUML";
    name_text = "[RUIN_RUML_NAME]";
    desc_text = "[RUIN_RUML_DESC]";
    icon = 2;
    x = 1820;
    y = 442;
    ruin_type = 2;
    visible = false;
    attach = "CDRH";
  };
  {
    id = "RVOL";
    name_text = "[RUIN_RVOL_NAME]";
    desc_text = "[RUIN_RVOL_DESC]";
    icon = 13;
    x = 1613;
    y = 376;
    ruin_type = 0;
    visible = false;
    attach = "CHTP";
  };
  {
    id = "RWCV";
    name_text = "[RUIN_RWCV_NAME]";
    desc_text = "[RUIN_RWCV_DESC]";
    icon = 2;
    x = 1971;
    y = 861;
    ruin_type = 2;
    visible = false;
    attach = "WBHE";
  };
  {
    id = "RWGS";
    name_text = "[RUIN_RWGS_NAME]";
    desc_text = "[RUIN_RWGS_DESC]";
    icon = 13;
    x = 1812;
    y = 1076;
    ruin_type = 0;
    visible = false;
    attach = "CGRU";
  };
  {
    id = "RWHV";
    name_text = "[RUIN_RWHV_NAME]";
    desc_text = "[RUIN_RWHV_DESC]";
    icon = 2;
    x = 1956;
    y = 720;
    ruin_type = 2;
    visible = false;
    attach = "WWSK";
  };
  {
    id = "RWRO";
    name_text = "[RUIN_RWRO_NAME]";
    desc_text = "[RUIN_RWRO_DESC]";
    icon = 2;
    x = 1707;
    y = 966;
    ruin_type = 2;
    visible = false;
    attach = "WRMO";
  };
]

let roads : road list = [
  { start = "CBAR"; end_ = "WTHR"; visible = true };
  { start = "CBAR"; end_ = "WSIR"; visible = true };
  { start = "CBAR"; end_ = "WGIL"; visible = true };
  { start = "CBAR"; end_ = "WELE"; visible = true };
  { start = "WGIL"; end_ = "RGSE"; visible = false };
  { start = "CGAL"; end_ = "WRAR"; visible = false };
  { start = "CGAL"; end_ = "WMAE"; visible = false };
  { start = "WGIL"; end_ = "WAPS"; visible = false };
  { start = "WAPS"; end_ = "CGAL"; visible = false };
  { start = "WTHR"; end_ = "RTHC"; visible = false };
  { start = "REGB"; end_ = "WMAE"; visible = false };
  { start = "CGAL"; end_ = "WSKE"; visible = false };
  { start = "WSKE"; end_ = "CDRA"; visible = false };
  { start = "WSKE"; end_ = "RSKM"; visible = false };
  { start = "RSTR"; end_ = "WELE"; visible = false };
  { start = "WTHR"; end_ = "ROTO"; visible = false };
  { start = "CENM"; end_ = "WELE"; visible = false };
  { start = "CENM"; end_ = "WBTH"; visible = false };
  { start = "WBTH"; end_ = "CTRA"; visible = false };
  { start = "WELE"; end_ = "CTRA"; visible = false };
  { start = "WBTH"; end_ = "RSLV"; visible = false };
  { start = "WBTH"; end_ = "ROOU"; visible = false };
  { start = "WBTH"; end_ = "RDPS"; visible = false };
  { start = "RDCV"; end_ = "CDRA"; visible = false };
  { start = "WHPS"; end_ = "WTHR"; visible = false };
  { start = "WALF"; end_ = "WTHR"; visible = false };
  { start = "CSIL"; end_ = "WALF"; visible = false };
  { start = "WALF"; end_ = "RSCV"; visible = false };
  { start = "WHPS"; end_ = "CDKO"; visible = false };
  { start = "CDKO"; end_ = "WRMO"; visible = false };
  { start = "CDKO"; end_ = "WWSK"; visible = false };
  { start = "CDKO"; end_ = "WBHE"; visible = false };
  { start = "WBHE"; end_ = "WSFA"; visible = false };
  { start = "WBHE"; end_ = "RWCV"; visible = false };
  { start = "CDKO"; end_ = "RSCC"; visible = false };
  { start = "WRMO"; end_ = "WBHE"; visible = false };
  { start = "WWSK"; end_ = "WBHE"; visible = false };
  { start = "WRMO"; end_ = "RWRO"; visible = false };
  { start = "WSFA"; end_ = "CGRU"; visible = false };
  { start = "CGRU"; end_ = "RWGS"; visible = false };
  { start = "WWSK"; end_ = "RWHV"; visible = false };
  { start = "WALF"; end_ = "RTLH"; visible = false };
  { start = "CGRU"; end_ = "WGRK"; visible = false };
  { start = "WGRK"; end_ = "CGLK"; visible = false };
  { start = "CGLK"; end_ = "WDRT"; visible = false };
  { start = "CDKO"; end_ = "WNKR"; visible = false };
  { start = "WNKR"; end_ = "WDPS"; visible = false };
  { start = "WDPS"; end_ = "CDRH"; visible = false };
  { start = "CDRH"; end_ = "RUML"; visible = false };
  { start = "CDRH"; end_ = "RCBL"; visible = false };
  { start = "CDRH"; end_ = "RMOL"; visible = false };
  { start = "CHTP"; end_ = "WHBG"; visible = false };
  { start = "WHBG"; end_ = "WVOK"; visible = false };
  { start = "WVOK"; end_ = "WNKR"; visible = false };
  { start = "CHTP"; end_ = "WPIK"; visible = false };
  { start = "WPIK"; end_ = "CTSK"; visible = false };
  { start = "CTSK"; end_ = "WSHD"; visible = false };
  { start = "WSHD"; end_ = "WGWK"; visible = false };
  { start = "WSHD"; end_ = "COHT"; visible = false };
  { start = "WPIK"; end_ = "CHYA"; visible = false };
  { start = "WWRT"; end_ = "CTSK"; visible = false };
  { start = "CHTP"; end_ = "RVOL"; visible = false };
  { start = "CTSK"; end_ = "RATO"; visible = false };
  { start = "RDGV"; end_ = "WDPS"; visible = false };
  { start = "CHTP"; end_ = "WPAR"; visible = false };
  { start = "WPAR"; end_ = "WALF"; visible = false };
  { start = "WGWK"; end_ = "CJAK"; visible = false };
  { start = "WGWK"; end_ = "CJOK"; visible = false };
  { start = "CYLA"; end_ = "WSGK"; visible = false };
  { start = "CYLA"; end_ = "WTIR"; visible = false };
  { start = "WTIR"; end_ = "CEHL"; visible = false };
  { start = "CEHL"; end_ = "WRAG"; visible = false };
  { start = "WTIR"; end_ = "WIGK"; visible = false };
  { start = "WGRW"; end_ = "WSOI"; visible = false };
  { start = "WSOI"; end_ = "CLBC"; visible = false };
  { start = "CLBC"; end_ = "WLOB"; visible = false };
  { start = "WLOB"; end_ = "WIGK"; visible = false };
  { start = "CTSK"; end_ = "WSMZ"; visible = false };
  { start = "WSMZ"; end_ = "WGGP"; visible = false };
  { start = "WGGP"; end_ = "WGRW"; visible = false };
  { start = "WSGK"; end_ = "WBBR"; visible = false };
  { start = "WBBR"; end_ = "CLBC"; visible = false };
  { start = "WLOB"; end_ = "CKUN"; visible = false };
  { start = "CYLA"; end_ = "WETO"; visible = false };
  { start = "WETO"; end_ = "CHYA"; visible = false };
  { start = "RDSH"; end_ = "WIGK"; visible = false };
  { start = "RICM"; end_ = "WIGK"; visible = false };
  { start = "CKUN"; end_ = "WWAS"; visible = false };
  { start = "WWAS"; end_ = "WHVA"; visible = false };
  { start = "WHVA"; end_ = "WBSP"; visible = false };
  { start = "WSGK"; end_ = "RBST"; visible = false };
  { start = "RDST"; end_ = "CLBC"; visible = false };
  { start = "RHAG"; end_ = "WRAG"; visible = false };
]

let city_by_id (id: string) : city = List.find (fun (c: city) -> c.id = id) cities
let waypoint_by_id (id: string) : waypoint = List.find (fun (w: waypoint) -> w.id = id) waypoints
let ruin_by_id (id: string) : ruin = List.find (fun (r: ruin) -> r.id = id) ruins

let roads_from (node: string) : road list = List.filter (fun (r: road) -> r.start = node) roads
let roads_to (node: string) : road list = List.filter (fun (r: road) -> r.end_ = node) roads
let roads_connected (node: string) : road list =
  List.filter (fun (r: road) -> r.start = node || r.end_ = node) roads

let node_position (kind: node_kind) (id: string) : (int * int) =
  match kind with
  | City -> (let c = city_by_id id in (c.x, c.y))
  | Waypoint -> (let w = waypoint_by_id id in (w.x, w.y))
  | Ruin -> (let r = ruin_by_id id in (r.x, r.y))
