(* Generated by tools/extract_fx_data.py from Assets/Effects/*.xml and
   Assets/Particles/*.xml. Do not edit by hand; re-run the extractor. *)

(** The game's effects and particles, as data.

    An effect is a named bundle: a duration, some children (other effects or
    particle emitters), a set of initial parameters, and timed keyframes on
    those parameters. A particle is an emitter of textured sprites with a
    lifetime, a spawn schedule, and a start and end size and colour.

    This is the file [ADD_ANIMEFFECT_TO_GRID] names one entry of, and the
    timing table the cascade animation had to invent: [SpellHealing] runs for
    2.1 seconds because the descriptor says so.

    Nothing in it is interpreted. [shape_steps], the planar [planes] codes and
    [anim_position] are transcribed as they are written, because they belong
    to the engine's particle code and this project has not read it. *)

type param =
  | Alpha
  | Colour_r
  | Colour_g
  | Colour_b
  | Dest_x
  | Dest_y
  | Dest_w
  | Dest_h
  | Rotation
  | Source_x
  | Source_y
  | Source_w
  | Source_h

type easing = Linear | Discrete

type keyframe = {
  at : float;  (** seconds from the effect's start *)
  param : param;
  value : float;
  easing : easing;
}

type child_kind = Effect | Particle

type child = {
  name : string;
  kind : child_kind;
  at : float;  (** seconds after the effect starts that this child begins *)
  duration : float;  (** the child's own duration, not the parent's *)
  x : float;
  y : float;
}

(* Not [effect], which is a keyword in OCaml 5: it is what the algebraic
   effects extension spells. *)
type effect_desc = {
  name : string;
  bitmap : string;
  (* The sheet this effect draws its own bitmap from - bmp_skin_battlemisc
     for most of them - and empty for the ones that are only children and
     keyframes. The rectangle of it is the source_* parameters. *)
  duration : float;
  children : child list;
  initial : (param * float) list;
  keys : keyframe list;
}

type colour = { r : float; g : float; b : float; a : float }

type blend = Additive | Alpha_blend

type vec3 = { x : float; y : float; z : float }

type particle = {
  name : string;
  texture : string;
  radius : float;
  lifetime : int;  (** milliseconds, unlike every duration in these files *)
  max : int;  (** how many may be alive at once *)
  release : int;  (** how many are let out together *)
  interval : float;  (** seconds between releases *)
  life : float;  (** seconds one particle lives *)
  total : int option;
  (** A cap on the whole emission, absent in 16 of 51 files. Absent is not
      zero: without it the emitter runs until the effect ends. *)
  blend : blend;
  size : float;
  colour : colour;
  to_size : float;
  to_colour : colour;
  start : float;
  (** The fraction of a particle's life at which it begins its own animation;
      [colour] and [to_colour] are its ends, not two frames of a sprite. *)
  position : vec3;
  position_var : float;
  position_planar : string option;
  position_planes : string option;
  position_perimeter : string option;
  velocity : vec3;
  velocity_var : float;
  velocity_planar : string option;
  velocity_planes : string option;
  gravity : vec3;
  anim_position : vec3 option;
  anim_position_var : float option;
  anim_position_start : float option;
  anim_position_end : float option;
  air_resistance : bool;
  wind : bool;
  shape_steps : int;
  (** 2 in seven files. Not interpreted: see the note at the top. *)
}

let effects =
  [
    { name = "BlueExplosion"; bitmap = "bmp_skin_battlemisc";
      duration = 1.0; children =
      [];
      initial = [ (Source_x, 101.0); (Source_y, 257.0); (Source_w, 100.0); (Source_h, 100.0); (Dest_x, -25.0); (Dest_y, -25.0); (Dest_w, 50.0); (Dest_h, 50.0); (Alpha, 0.0); (Rotation, 0.0); (Colour_r, 0.7); (Colour_g, 0.7); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.2; param = Alpha; value = 1.0; easing = Linear };
          { at = 0.8; param = Alpha; value = 1.0; easing = Linear };
          { at = 0.8; param = Dest_x; value = -150.0; easing = Linear };
          { at = 0.8; param = Dest_y; value = -150.0; easing = Linear };
          { at = 0.8; param = Dest_w; value = 300.0; easing = Linear };
          { at = 0.8; param = Dest_h; value = 300.0; easing = Linear };
          { at = 1.0; param = Alpha; value = 0.0; easing = Linear };
          { at = 1.0; param = Dest_x; value = -200.0; easing = Linear };
          { at = 1.0; param = Dest_y; value = -200.0; easing = Linear };
          { at = 1.0; param = Dest_w; value = 400.0; easing = Linear };
          { at = 1.0; param = Dest_h; value = 400.0; easing = Linear };
        ];
    };
    { name = "BlueWave"; bitmap = "";
      duration = 1.5; children =
      [
        { name = "BlueWave0"; kind = Effect; at = 0.0; duration = 1.5; x = 0.0; y = 0.0 };
        { name = "BlueWave1"; kind = Effect; at = 0.0; duration = 1.5; x = 0.0; y = -10.0 };
        { name = "BlueWave0"; kind = Effect; at = 0.1; duration = 1.5; x = 0.0; y = 0.0 };
        { name = "BlueWave1"; kind = Effect; at = 0.1; duration = 1.5; x = 0.0; y = -10.0 };
        { name = "BlueWave0"; kind = Effect; at = 0.2; duration = 1.5; x = 0.0; y = 0.0 };
        { name = "BlueWave1"; kind = Effect; at = 0.2; duration = 1.5; x = 0.0; y = -10.0 };
        { name = "BlueWave0"; kind = Effect; at = 0.3; duration = 1.5; x = 0.0; y = 0.0 };
        { name = "BlueWave1"; kind = Effect; at = 0.3; duration = 1.5; x = 0.0; y = -10.0 };
        { name = "BlueWave0"; kind = Effect; at = 0.4; duration = 1.5; x = 0.0; y = 0.0 };
        { name = "BlueWave1"; kind = Effect; at = 0.4; duration = 1.5; x = 0.0; y = -10.0 };
        { name = "BlueWave0"; kind = Effect; at = 0.5; duration = 1.5; x = 0.0; y = 0.0 };
        { name = "BlueWave1"; kind = Effect; at = 0.5; duration = 1.5; x = 0.0; y = -10.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); (Rotation, 0.0); ];
      keys = [];
    };
    { name = "BlueWave0"; bitmap = "bmp_skin_battlemisc";
      duration = 1.0; children =
      [];
      initial = [ (Source_x, 101.0); (Source_y, 358.0); (Source_w, 100.0); (Source_h, 100.0); (Dest_x, -50.0); (Dest_y, -50.0); (Dest_w, 100.0); (Dest_h, 100.0); (Alpha, 0.0); (Rotation, 1.6); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.1; param = Alpha; value = 0.8; easing = Linear };
          { at = 0.3; param = Alpha; value = 0.9; easing = Linear };
          { at = 0.8; param = Alpha; value = 0.9; easing = Linear };
          { at = 1.0; param = Alpha; value = 0.0; easing = Linear };
          { at = 1.0; param = Rotation; value = 1.3; easing = Linear };
          { at = 1.0; param = Dest_x; value = 300.0; easing = Linear };
          { at = 1.0; param = Dest_y; value = -150.0; easing = Linear };
          { at = 1.0; param = Dest_w; value = 150.0; easing = Linear };
          { at = 1.0; param = Dest_h; value = 300.0; easing = Linear };
        ];
    };
    { name = "BlueWave1"; bitmap = "bmp_skin_battlemisc";
      duration = 1.5; children =
      [];
      initial = [ (Source_x, 101.0); (Source_y, 358.0); (Source_w, 100.0); (Source_h, 100.0); (Dest_x, -50.0); (Dest_y, -50.0); (Dest_w, 100.0); (Dest_h, 100.0); (Alpha, 0.0); (Rotation, -1.6); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.1; param = Alpha; value = 0.8; easing = Linear };
          { at = 0.3; param = Alpha; value = 0.9; easing = Linear };
          { at = 0.8; param = Alpha; value = 0.9; easing = Linear };
          { at = 1.0; param = Alpha; value = 0.0; easing = Linear };
          { at = 1.0; param = Rotation; value = -1.9; easing = Linear };
          { at = 1.0; param = Dest_x; value = -400.0; easing = Linear };
          { at = 1.0; param = Dest_y; value = -150.0; easing = Linear };
          { at = 1.0; param = Dest_w; value = 150.0; easing = Linear };
          { at = 1.0; param = Dest_h; value = 300.0; easing = Linear };
        ];
    };
    { name = "CyanStun"; bitmap = "bmp_skin_battlemisc";
      duration = 0.4; children =
      [];
      initial = [ (Source_x, 202.0); (Source_y, 257.0); (Source_w, 100.0); (Source_h, 100.0); (Dest_x, -20.0); (Dest_y, -20.0); (Dest_w, 40.0); (Dest_h, 40.0); (Alpha, 0.0); (Rotation, 0.0); (Colour_r, 0.3); (Colour_g, 0.7); (Colour_b, 0.7); ];
      keys =
        [
          { at = 0.1; param = Alpha; value = 0.4; easing = Linear };
          { at = 0.3; param = Alpha; value = 0.8; easing = Linear };
          { at = 0.4; param = Alpha; value = 0.0; easing = Linear };
          { at = 0.4; param = Dest_x; value = -45.0; easing = Linear };
          { at = 0.4; param = Dest_y; value = -45.0; easing = Linear };
          { at = 0.4; param = Dest_w; value = 90.0; easing = Linear };
          { at = 0.4; param = Dest_h; value = 90.0; easing = Linear };
        ];
    };
    { name = "GrowAir"; bitmap = "bmp_skin_battlemisc";
      duration = 1.5; children =
      [];
      initial = [ (Source_x, 0.0); (Source_y, 358.0); (Source_w, 100.0); (Source_h, 100.0); (Dest_x, -30.0); (Dest_y, -30.0); (Dest_w, 60.0); (Dest_h, 60.0); (Alpha, 0.0); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.2; param = Alpha; value = 1.0; easing = Linear };
          { at = 0.5; param = Dest_x; value = -100.0; easing = Linear };
          { at = 0.5; param = Dest_y; value = -100.0; easing = Linear };
          { at = 0.5; param = Dest_w; value = 200.0; easing = Linear };
          { at = 0.5; param = Dest_h; value = 200.0; easing = Linear };
          { at = 1.0; param = Alpha; value = 1.0; easing = Linear };
          { at = 1.5; param = Alpha; value = 0.0; easing = Linear };
          { at = 1.5; param = Dest_x; value = -150.0; easing = Linear };
          { at = 1.5; param = Dest_y; value = -150.0; easing = Linear };
          { at = 1.5; param = Dest_w; value = 300.0; easing = Linear };
          { at = 1.5; param = Dest_h; value = 300.0; easing = Linear };
          { at = 1.5; param = Rotation; value = 10.0; easing = Linear };
        ];
    };
    { name = "GrowFlare"; bitmap = "bmp_skin_battlemisc";
      duration = 2.0; children =
      [];
      initial = [ (Source_x, 0.0); (Source_y, 462.0); (Source_w, 200.0); (Source_h, 50.0); (Dest_x, -100.0); (Dest_y, -25.0); (Dest_w, 200.0); (Dest_h, 50.0); (Alpha, 0.0); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.2; param = Alpha; value = 1.0; easing = Linear };
          { at = 0.5; param = Dest_x; value = -320.0; easing = Linear };
          { at = 0.5; param = Dest_y; value = -80.0; easing = Linear };
          { at = 0.5; param = Dest_w; value = 640.0; easing = Linear };
          { at = 0.5; param = Dest_h; value = 160.0; easing = Linear };
          { at = 1.0; param = Alpha; value = 1.0; easing = Linear };
          { at = 2.0; param = Alpha; value = 0.0; easing = Linear };
        ];
    };
    { name = "GrowGreenStar"; bitmap = "bmp_skin_battlemisc";
      duration = 0.7; children =
      [];
      initial = [ (Source_x, 101.0); (Source_y, 257.0); (Source_w, 100.0); (Source_h, 100.0); (Dest_x, -64.0); (Dest_y, -64.0); (Dest_w, 128.0); (Dest_h, 128.0); (Alpha, 0.0); (Rotation, 0.0); (Colour_r, 0.8); (Colour_g, 1.0); (Colour_b, 0.8); ];
      keys =
        [
          { at = 0.1; param = Alpha; value = 0.4; easing = Linear };
          { at = 0.4; param = Alpha; value = 0.8; easing = Linear };
          { at = 0.4; param = Dest_x; value = -160.0; easing = Linear };
          { at = 0.4; param = Dest_y; value = -160.0; easing = Linear };
          { at = 0.4; param = Dest_w; value = 220.0; easing = Linear };
          { at = 0.4; param = Dest_h; value = 220.0; easing = Linear };
          { at = 0.7; param = Alpha; value = 0.0; easing = Linear };
          { at = 0.7; param = Rotation; value = 4.0; easing = Linear };
          { at = 0.7; param = Colour_r; value = 0.4; easing = Linear };
          { at = 0.7; param = Colour_g; value = 0.8; easing = Linear };
          { at = 0.7; param = Colour_b; value = 1.0; easing = Linear };
          { at = 0.7; param = Dest_x; value = -60.0; easing = Linear };
          { at = 0.7; param = Dest_y; value = -60.0; easing = Linear };
          { at = 0.7; param = Dest_w; value = 50.0; easing = Linear };
          { at = 0.7; param = Dest_h; value = 50.0; easing = Linear };
        ];
    };
    { name = "GrowRedRing"; bitmap = "bmp_skin_battlemisc";
      duration = 2.0; children =
      [];
      initial = [ (Source_x, 202.0); (Source_y, 257.0); (Source_w, 100.0); (Source_h, 100.0); (Dest_x, -50.0); (Dest_y, -50.0); (Dest_w, 100.0); (Dest_h, 100.0); (Alpha, 0.0); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.2; param = Alpha; value = 0.9; easing = Linear };
          { at = 0.5; param = Dest_x; value = -150.0; easing = Linear };
          { at = 0.5; param = Dest_y; value = -150.0; easing = Linear };
          { at = 0.5; param = Dest_w; value = 300.0; easing = Linear };
          { at = 0.5; param = Dest_h; value = 300.0; easing = Linear };
          { at = 0.8; param = Alpha; value = 1.0; easing = Linear };
          { at = 2.0; param = Alpha; value = 0.0; easing = Linear };
          { at = 2.0; param = Dest_x; value = -225.0; easing = Linear };
          { at = 2.0; param = Dest_y; value = -225.0; easing = Linear };
          { at = 2.0; param = Dest_w; value = 450.0; easing = Linear };
          { at = 2.0; param = Dest_h; value = 450.0; easing = Linear };
        ];
    };
    { name = "GrowSkull"; bitmap = "bmp_skin_battlemisc";
      duration = 1.0; children =
      [];
      initial = [ (Source_x, 404.0); (Source_y, 358.0); (Source_w, 100.0); (Source_h, 100.0); (Dest_x, -25.0); (Dest_y, -25.0); (Dest_w, 50.0); (Dest_h, 50.0); (Alpha, 0.0); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.2; param = Alpha; value = 1.0; easing = Linear };
          { at = 0.5; param = Alpha; value = 1.0; easing = Linear };
          { at = 0.5; param = Dest_x; value = -100.0; easing = Linear };
          { at = 0.5; param = Dest_y; value = -100.0; easing = Linear };
          { at = 0.5; param = Dest_w; value = 200.0; easing = Linear };
          { at = 0.5; param = Dest_h; value = 200.0; easing = Linear };
          { at = 1.0; param = Alpha; value = 0.0; easing = Linear };
          { at = 1.0; param = Dest_x; value = -125.0; easing = Linear };
          { at = 1.0; param = Dest_y; value = -125.0; easing = Linear };
          { at = 1.0; param = Dest_w; value = 250.0; easing = Linear };
          { at = 1.0; param = Dest_h; value = 250.0; easing = Linear };
        ];
    };
    { name = "GrowSpiral"; bitmap = "bmp_skin_battlemisc";
      duration = 1.5; children =
      [];
      initial = [ (Source_x, 0.0); (Source_y, 358.0); (Source_w, 100.0); (Source_h, 100.0); (Dest_x, -40.0); (Dest_y, -40.0); (Dest_w, 80.0); (Dest_h, 80.0); (Alpha, 1.0); (Rotation, 0.0); (Colour_r, 0.2); (Colour_g, 0.4); (Colour_b, 0.8); ];
      keys =
        [
          { at = 1.0; param = Alpha; value = 1.0; easing = Linear };
          { at = 1.5; param = Alpha; value = 0.0; easing = Linear };
          { at = 1.5; param = Rotation; value = 4.0; easing = Linear };
          { at = 1.5; param = Dest_x; value = -100.0; easing = Linear };
          { at = 1.5; param = Dest_y; value = -100.0; easing = Linear };
          { at = 1.5; param = Dest_w; value = 200.0; easing = Linear };
          { at = 1.5; param = Dest_h; value = 200.0; easing = Linear };
        ];
    };
    { name = "GrowWater"; bitmap = "bmp_skin_battlemisc";
      duration = 1.5; children =
      [];
      initial = [ (Source_x, 101.0); (Source_y, 358.0); (Source_w, 100.0); (Source_h, 100.0); (Dest_x, -40.0); (Dest_y, -40.0); (Dest_w, 80.0); (Dest_h, 80.0); (Alpha, 0.0); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.2; param = Alpha; value = 1.0; easing = Linear };
          { at = 1.0; param = Alpha; value = 1.0; easing = Linear };
          { at = 1.5; param = Alpha; value = 0.0; easing = Linear };
          { at = 1.5; param = Dest_x; value = -175.0; easing = Linear };
          { at = 1.5; param = Dest_y; value = -125.0; easing = Linear };
          { at = 1.5; param = Dest_w; value = 350.0; easing = Linear };
          { at = 1.5; param = Dest_h; value = 250.0; easing = Linear };
        ];
    };
    { name = "MoveGemAI_0"; bitmap = "bmp_skin_battlemisc";
      duration = 1.0; children =
      [];
      initial = [ (Source_x, 91.0); (Source_y, 74.0); (Source_w, 128.0); (Source_h, 128.0); (Dest_x, -64.0); (Dest_y, -64.0); (Dest_w, 128.0); (Dest_h, 128.0); (Alpha, 0.0); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.5; param = Alpha; value = 1.0; easing = Linear };
          { at = 1.0; param = Rotation; value = 1.05; easing = Linear };
        ];
    };
    { name = "MoveGemAI_1"; bitmap = "bmp_skin_battlemisc";
      duration = 1.0; children =
      [];
      initial = [ (Source_x, 91.0); (Source_y, 74.0); (Source_w, 128.0); (Source_h, 128.0); (Dest_x, -64.0); (Dest_y, -64.0); (Dest_w, 128.0); (Dest_h, 128.0); (Alpha, 0.0); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.3; param = Alpha; value = 0.0; easing = Discrete };
          { at = 0.8; param = Alpha; value = 1.0; easing = Linear };
          { at = 1.0; param = Rotation; value = 1.05; easing = Linear };
        ];
    };
    { name = "PulseGreenSkull"; bitmap = "bmp_skin_battlemisc";
      duration = 2.0; children =
      [];
      initial = [ (Source_x, 404.0); (Source_y, 358.0); (Source_w, 100.0); (Source_h, 100.0); (Dest_x, -25.0); (Dest_y, -25.0); (Dest_w, 50.0); (Dest_h, 50.0); (Alpha, 0.5); (Rotation, 0.0); (Colour_r, 0.5); (Colour_g, 1.0); (Colour_b, 0.5); ];
      keys =
        [
          { at = 0.2; param = Alpha; value = 1.0; easing = Linear };
          { at = 0.4; param = Alpha; value = 0.5; easing = Linear };
          { at = 0.6; param = Alpha; value = 1.0; easing = Linear };
          { at = 0.8; param = Alpha; value = 0.5; easing = Linear };
          { at = 1.0; param = Alpha; value = 1.0; easing = Linear };
          { at = 1.2; param = Alpha; value = 0.5; easing = Linear };
          { at = 1.4; param = Alpha; value = 1.0; easing = Linear };
          { at = 1.6; param = Alpha; value = 0.5; easing = Linear };
          { at = 1.8; param = Alpha; value = 1.0; easing = Linear };
          { at = 2.0; param = Alpha; value = 0.5; easing = Linear };
          { at = 2.2; param = Alpha; value = 1.0; easing = Linear };
          { at = 2.2; param = Dest_x; value = -100.0; easing = Linear };
          { at = 2.2; param = Dest_y; value = -100.0; easing = Linear };
          { at = 2.2; param = Dest_w; value = 200.0; easing = Linear };
          { at = 2.2; param = Dest_h; value = 200.0; easing = Linear };
        ];
    };
    { name = "PulseRedSkull"; bitmap = "bmp_skin_battlemisc";
      duration = 2.0; children =
      [];
      initial = [ (Source_x, 404.0); (Source_y, 358.0); (Source_w, 100.0); (Source_h, 100.0); (Dest_x, -25.0); (Dest_y, -25.0); (Dest_w, 50.0); (Dest_h, 50.0); (Alpha, 0.5); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 0.5); (Colour_b, 0.5); ];
      keys =
        [
          { at = 0.2; param = Alpha; value = 1.0; easing = Linear };
          { at = 0.4; param = Alpha; value = 0.5; easing = Linear };
          { at = 0.6; param = Alpha; value = 1.0; easing = Linear };
          { at = 0.8; param = Alpha; value = 0.5; easing = Linear };
          { at = 1.0; param = Alpha; value = 1.0; easing = Linear };
          { at = 1.2; param = Alpha; value = 0.5; easing = Linear };
          { at = 1.4; param = Alpha; value = 1.0; easing = Linear };
          { at = 1.6; param = Alpha; value = 0.5; easing = Linear };
          { at = 1.8; param = Alpha; value = 1.0; easing = Linear };
          { at = 2.0; param = Alpha; value = 0.5; easing = Linear };
          { at = 2.2; param = Alpha; value = 1.0; easing = Linear };
          { at = 2.2; param = Dest_x; value = -100.0; easing = Linear };
          { at = 2.2; param = Dest_y; value = -100.0; easing = Linear };
          { at = 2.2; param = Dest_w; value = 200.0; easing = Linear };
          { at = 2.2; param = Dest_h; value = 200.0; easing = Linear };
        ];
    };
    { name = "SpellAir"; bitmap = "";
      duration = 2.5; children =
      [
        { name = "GrowAir"; kind = Effect; at = 0.0; duration = 1.5; x = 50.0; y = 0.0 };
        { name = "GrowAir"; kind = Effect; at = 0.0; duration = 1.5; x = 0.0; y = 50.0 };
        { name = "GrowAir"; kind = Effect; at = 0.0; duration = 1.5; x = -50.0; y = 0.0 };
        { name = "GrowAir"; kind = Effect; at = 0.0; duration = 1.5; x = 0.0; y = -50.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpellChaos"; bitmap = "";
      duration = 2.7; children =
      [
        { name = "SpinFlare"; kind = Effect; at = 0.0; duration = 2.0; x = 0.0; y = 0.0 };
        { name = "RingRed"; kind = Particle; at = 0.2; duration = 2.0; x = 0.0; y = 0.0 };
        { name = "RingYellow"; kind = Particle; at = 0.3; duration = 2.0; x = 0.0; y = 0.0 };
        { name = "SpinFlare"; kind = Effect; at = 0.3; duration = 2.0; x = 0.0; y = 0.0 };
        { name = "CyanExplosion"; kind = Particle; at = 0.4; duration = 1.0; x = 0.0; y = 0.0 };
        { name = "RingGreen"; kind = Particle; at = 0.6; duration = 1.5; x = 0.0; y = 0.0 };
        { name = "WhiteExplosion"; kind = Particle; at = 1.2; duration = 1.0; x = 0.0; y = 0.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpellDeselectGem"; bitmap = "bmp_skin_battlemisc";
      duration = 0.7; children =
      [];
      initial = [ (Source_x, 220.0); (Source_y, 74.0); (Source_w, 128.0); (Source_h, 128.0); (Dest_x, -128.0); (Dest_y, -128.0); (Dest_w, 256.0); (Dest_h, 256.0); (Alpha, 0.0); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.7; param = Alpha; value = 0.8; easing = Linear };
          { at = 0.7; param = Dest_x; value = -64.0; easing = Linear };
          { at = 0.7; param = Dest_y; value = -64.0; easing = Linear };
          { at = 0.7; param = Dest_w; value = 128.0; easing = Linear };
          { at = 0.7; param = Dest_h; value = 128.0; easing = Linear };
          { at = 0.7; param = Rotation; value = 2.1; easing = Linear };
        ];
    };
    { name = "SpellDisease"; bitmap = "";
      duration = 2.2; children =
      [
        { name = "PulseRedSkull"; kind = Effect; at = 0.0; duration = 2.0; x = 0.0; y = 0.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpellFear"; bitmap = "";
      duration = 1.5; children =
      [
        { name = "SpinBlackHole"; kind = Effect; at = 0.0; duration = 1.5; x = 0.0; y = 0.0 };
        { name = "GrowSkull"; kind = Effect; at = 0.3; duration = 1.0; x = 0.0; y = 0.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpellFireball"; bitmap = "";
      duration = 1.5; children =
      [
        { name = "SpellFireball0"; kind = Effect; at = 0.0; duration = 1.5; x = 0.0; y = 0.0 };
        { name = "SpellFireball1"; kind = Effect; at = 0.0; duration = 1.5; x = 0.0; y = 0.0 };
        { name = "Sparks"; kind = Particle; at = 0.0; duration = 2.0; x = 0.0; y = 0.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpellFireball0"; bitmap = "bmp_skin_battlemisc";
      duration = 0.7; children =
      [];
      initial = [ (Source_x, 349.0); (Source_y, 74.0); (Source_w, 128.0); (Source_h, 128.0); (Dest_x, -64.0); (Dest_y, -64.0); (Dest_w, 128.0); (Dest_h, 128.0); (Alpha, 0.0); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.1; param = Alpha; value = 0.8; easing = Linear };
          { at = 0.5; param = Alpha; value = 0.9; easing = Linear };
          { at = 0.7; param = Alpha; value = 0.0; easing = Linear };
          { at = 0.7; param = Dest_x; value = -160.0; easing = Linear };
          { at = 0.7; param = Dest_y; value = -160.0; easing = Linear };
          { at = 0.7; param = Dest_w; value = 320.0; easing = Linear };
          { at = 0.7; param = Dest_h; value = 320.0; easing = Linear };
        ];
    };
    { name = "SpellFireball1"; bitmap = "bmp_skin_battlemisc";
      duration = 1.2; children =
      [];
      initial = [ (Source_x, 349.0); (Source_y, 74.0); (Source_w, 128.0); (Source_h, 128.0); (Dest_x, -8.0); (Dest_y, -8.0); (Dest_w, 16.0); (Dest_h, 16.0); (Alpha, 0.0); (Rotation, 1.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); (Rotation, 1.1); ];
      keys =
        [
          { at = 0.2; param = Alpha; value = 0.8; easing = Linear };
          { at = 0.8; param = Alpha; value = 0.9; easing = Linear };
          { at = 1.2; param = Alpha; value = 0.0; easing = Linear };
          { at = 1.2; param = Dest_x; value = -220.0; easing = Linear };
          { at = 1.2; param = Dest_y; value = -220.0; easing = Linear };
          { at = 1.2; param = Dest_w; value = 440.0; easing = Linear };
          { at = 1.2; param = Dest_h; value = 440.0; easing = Linear };
        ];
    };
    { name = "SpellFireballSmall"; bitmap = "bmp_skin_battlemisc";
      duration = 0.8; children =
      [];
      initial = [ (Source_x, 349.0); (Source_y, 74.0); (Source_w, 128.0); (Source_h, 128.0); (Dest_x, -8.0); (Dest_y, -8.0); (Dest_w, 16.0); (Dest_h, 16.0); (Alpha, 0.8); (Rotation, 0.0); (Colour_r, 0.8); (Colour_g, 0.8); (Colour_b, 0.8); ];
      keys =
        [
          { at = 0.5; param = Alpha; value = 0.9; easing = Linear };
          { at = 0.8; param = Alpha; value = 0.0; easing = Linear };
          { at = 0.8; param = Dest_x; value = -100.0; easing = Linear };
          { at = 0.8; param = Dest_y; value = -100.0; easing = Linear };
          { at = 0.8; param = Dest_w; value = 200.0; easing = Linear };
          { at = 0.8; param = Dest_h; value = 200.0; easing = Linear };
          { at = 0.8; param = Rotation; value = -2.1; easing = Linear };
        ];
    };
    { name = "SpellFrost"; bitmap = "";
      duration = 1.5; children =
      [
        { name = "GrowGreenStar"; kind = Effect; at = 0.0; duration = 1.5; x = 0.0; y = 0.0 };
        { name = "GrowGreenStar"; kind = Effect; at = 0.3; duration = 1.5; x = -30.0; y = -30.0 };
        { name = "GrowGreenStar"; kind = Effect; at = 0.4; duration = 1.5; x = 30.0; y = 30.0 };
        { name = "GrowGreenStar"; kind = Effect; at = 0.5; duration = 1.5; x = -30.0; y = 30.0 };
        { name = "GrowGreenStar"; kind = Effect; at = 0.7; duration = 1.5; x = 30.0; y = -30.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpellGood"; bitmap = "";
      duration = 2.0; children =
      [
        { name = "WhiteSparkleLite"; kind = Particle; at = 0.0; duration = 1.0; x = 0.0; y = 0.0 };
        { name = "BlueExplosion"; kind = Particle; at = 0.2; duration = 1.5; x = 0.0; y = 0.0 };
        { name = "WhiteSparkleLite"; kind = Particle; at = 0.7; duration = 1.0; x = 0.0; y = 0.0 };
        { name = "BlueExplosion"; kind = Particle; at = 0.4; duration = 1.5; x = 0.0; y = 0.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpellHealing"; bitmap = "bmp_skin_battlemisc";
      duration = 2.1; children =
      [
        { name = "RingCyan"; kind = Particle; at = 0.5; duration = 1.5; x = 75.0; y = 75.0 };
      ];
      initial = [ (Source_x, 0.0); (Source_y, 257.0); (Source_w, 100.0); (Source_h, 100.0); (Dest_x, -50.0); (Dest_y, -50.0); (Dest_w, 100.0); (Dest_h, 100.0); (Alpha, 0.0); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.1; param = Alpha; value = 0.8; easing = Linear };
          { at = 0.6; param = Alpha; value = 0.9; easing = Linear };
          { at = 1.0; param = Alpha; value = 0.9; easing = Linear };
          { at = 2.0; param = Alpha; value = 0.0; easing = Linear };
          { at = 2.0; param = Dest_x; value = -150.0; easing = Linear };
          { at = 2.0; param = Dest_y; value = -150.0; easing = Linear };
          { at = 2.0; param = Dest_w; value = 300.0; easing = Linear };
          { at = 2.0; param = Dest_h; value = 300.0; easing = Linear };
          { at = 2.0; param = Rotation; value = 12.4; easing = Linear };
        ];
    };
    { name = "SpellHide"; bitmap = "bmp_skin_battlemisc";
      duration = 2.5; children =
      [
        { name = "RingRed"; kind = Particle; at = 0.5; duration = 1.5; x = 75.0; y = 75.0 };
      ];
      initial = [ (Source_x, 404.0); (Source_y, 257.0); (Source_w, 100.0); (Source_h, 100.0); (Dest_x, -25.0); (Dest_y, -25.0); (Dest_w, 50.0); (Dest_h, 50.0); (Alpha, 0.0); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.1; param = Alpha; value = 0.8; easing = Linear };
          { at = 0.6; param = Alpha; value = 1.0; easing = Linear };
          { at = 1.0; param = Dest_x; value = -150.0; easing = Linear };
          { at = 1.0; param = Dest_y; value = -150.0; easing = Linear };
          { at = 1.0; param = Dest_w; value = 300.0; easing = Linear };
          { at = 1.0; param = Dest_h; value = 300.0; easing = Linear };
          { at = 1.0; param = Rotation; value = 0.6; easing = Linear };
          { at = 1.5; param = Alpha; value = 1.0; easing = Linear };
          { at = 2.5; param = Alpha; value = 0.0; easing = Linear };
          { at = 2.5; param = Dest_x; value = -200.0; easing = Linear };
          { at = 2.5; param = Dest_y; value = -200.0; easing = Linear };
          { at = 2.5; param = Dest_w; value = 400.0; easing = Linear };
          { at = 2.5; param = Dest_h; value = 400.0; easing = Linear };
          { at = 2.5; param = Rotation; value = 8.0; easing = Linear };
        ];
    };
    { name = "SpellNature"; bitmap = "";
      duration = 2.0; children =
      [
        { name = "SpinFlare"; kind = Effect; at = 0.0; duration = 2.0; x = -25.0; y = -25.0 };
        { name = "SpinFlare"; kind = Effect; at = 0.0; duration = 2.0; x = 25.0; y = 25.0 };
        { name = "SpinFlare"; kind = Effect; at = 0.0; duration = 2.0; x = -25.0; y = 25.0 };
        { name = "SpinFlare"; kind = Effect; at = 0.0; duration = 2.0; x = 25.0; y = -25.0 };
        { name = "SpinFlare"; kind = Effect; at = 0.0; duration = 2.0; x = 0.0; y = 0.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpellNecro"; bitmap = "";
      duration = 2.5; children =
      [
        { name = "GrowSkull"; kind = Effect; at = 0.0; duration = 1.5; x = 0.0; y = 0.0 };
        { name = "GrowRedRing"; kind = Effect; at = 0.2; duration = 2.0; x = 0.0; y = 0.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpellPoison"; bitmap = "";
      duration = 2.2; children =
      [
        { name = "PulseGreenSkull"; kind = Effect; at = 0.0; duration = 2.0; x = 0.0; y = 0.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpellSelectGem0"; bitmap = "bmp_skin_battlemisc";
      duration = 0.7; children =
      [];
      initial = [ (Source_x, 220.0); (Source_y, 74.0); (Source_w, 128.0); (Source_h, 128.0); (Dest_x, -64.0); (Dest_y, -64.0); (Dest_w, 128.0); (Dest_h, 128.0); (Alpha, 0.8); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.7; param = Alpha; value = 0.0; easing = Linear };
          { at = 0.7; param = Dest_x; value = -128.0; easing = Linear };
          { at = 0.7; param = Dest_y; value = -128.0; easing = Linear };
          { at = 0.7; param = Dest_w; value = 256.0; easing = Linear };
          { at = 0.7; param = Dest_h; value = 256.0; easing = Linear };
          { at = 0.7; param = Rotation; value = 1.05; easing = Linear };
        ];
    };
    { name = "SpellSelectGem1"; bitmap = "bmp_skin_battlemisc";
      duration = 1.0; children =
      [];
      initial = [ (Source_x, 220.0); (Source_y, 74.0); (Source_w, 128.0); (Source_h, 128.0); (Dest_x, -8.0); (Dest_y, -8.0); (Dest_w, 16.0); (Dest_h, 16.0); (Alpha, 0.0); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.6; param = Alpha; value = 0.9; easing = Linear };
          { at = 1.0; param = Alpha; value = 0.0; easing = Linear };
          { at = 1.0; param = Dest_x; value = -180.0; easing = Linear };
          { at = 1.0; param = Dest_y; value = -180.0; easing = Linear };
          { at = 1.0; param = Dest_w; value = 360.0; easing = Linear };
          { at = 1.0; param = Dest_h; value = 360.0; easing = Linear };
          { at = 1.0; param = Rotation; value = -1.5; easing = Linear };
        ];
    };
    { name = "SpellSparkle"; bitmap = "";
      duration = 1.8; children =
      [
        { name = "RingYellow"; kind = Particle; at = 0.0; duration = 1.0; x = 0.0; y = 0.0 };
        { name = "RingRed"; kind = Particle; at = 0.1; duration = 1.0; x = -10.0; y = -5.0 };
        { name = "RingWhite"; kind = Particle; at = 0.3; duration = 1.0; x = 10.0; y = 10.0 };
        { name = "RingYellow"; kind = Particle; at = 0.5; duration = 1.0; x = -10.0; y = 5.0 };
        { name = "RingRed"; kind = Particle; at = 0.6; duration = 1.0; x = 5.0; y = -10.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpellSpin"; bitmap = "";
      duration = 1.5; children =
      [
        { name = "CyanExplosion"; kind = Particle; at = 0.2; duration = 1.5; x = 0.0; y = -10.0 };
        { name = "SpinBlueBlade"; kind = Effect; at = 0.0; duration = 1.5; x = 0.0; y = 0.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpellStone"; bitmap = "";
      duration = 2.4; children =
      [
        { name = "GrowRedRing"; kind = Effect; at = 0.0; duration = 2.0; x = 0.0; y = 0.0 };
        { name = "RedExplosion"; kind = Particle; at = 0.2; duration = 1.5; x = 0.0; y = -10.0 };
        { name = "GrowRedRing"; kind = Effect; at = 0.2; duration = 2.0; x = 0.0; y = 0.0 };
        { name = "GrowRedRing"; kind = Effect; at = 0.3; duration = 2.0; x = 0.0; y = 0.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpellStun"; bitmap = "";
      duration = 1.5; children =
      [
        { name = "CyanStun"; kind = Effect; at = 0.0; duration = 0.8; x = -20.0; y = 0.0 };
        { name = "CyanStun"; kind = Effect; at = 0.3; duration = 0.8; x = 10.0; y = -10.0 };
        { name = "WhiteSparkleLite"; kind = Particle; at = 0.4; duration = 1.0; x = 0.0; y = -10.0 };
        { name = "CyanStun"; kind = Effect; at = 0.5; duration = 0.8; x = -10.0; y = 20.0 };
        { name = "CyanStun"; kind = Effect; at = 0.8; duration = 0.8; x = -20.0; y = -10.0 };
        { name = "CyanStun"; kind = Effect; at = 0.2; duration = 0.8; x = -20.0; y = 5.0 };
        { name = "CyanStun"; kind = Effect; at = 0.6; duration = 0.8; x = 5.0; y = -10.0 };
        { name = "CyanStun"; kind = Effect; at = 0.7; duration = 0.8; x = -15.0; y = 25.0 };
        { name = "CyanStun"; kind = Effect; at = 0.9; duration = 0.8; x = -20.0; y = -15.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpellSymbol"; bitmap = "bmp_skin_battlemisc";
      duration = 2.7; children =
      [
        { name = "SpellSymbol0"; kind = Effect; at = 0.0; duration = 2.0; x = 0.0; y = 0.0 };
        { name = "SpellSymbol0"; kind = Effect; at = 0.3; duration = 2.0; x = 0.0; y = 0.0 };
        { name = "SpellSymbol0"; kind = Effect; at = 0.6; duration = 2.0; x = 0.0; y = 0.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpellSymbol0"; bitmap = "bmp_skin_battlemisc";
      duration = 2.0; children =
      [];
      initial = [ (Source_x, 202.0); (Source_y, 358.0); (Source_w, 100.0); (Source_h, 100.0); (Dest_x, -125.0); (Dest_y, -125.0); (Dest_w, 250.0); (Dest_h, 250.0); (Alpha, 0.0); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.1; param = Alpha; value = 0.8; easing = Linear };
          { at = 0.6; param = Alpha; value = 1.0; easing = Linear };
          { at = 1.25; param = Dest_x; value = -150.0; easing = Linear };
          { at = 1.25; param = Dest_y; value = -150.0; easing = Linear };
          { at = 1.25; param = Dest_w; value = 300.0; easing = Linear };
          { at = 1.25; param = Dest_h; value = 300.0; easing = Linear };
          { at = 1.25; param = Colour_r; value = 1.0; easing = Linear };
          { at = 1.25; param = Colour_g; value = 0.3; easing = Linear };
          { at = 1.25; param = Colour_b; value = 0.3; easing = Linear };
          { at = 1.5; param = Alpha; value = 1.0; easing = Linear };
          { at = 2.0; param = Alpha; value = 0.0; easing = Linear };
          { at = 2.0; param = Dest_x; value = -125.0; easing = Linear };
          { at = 2.0; param = Dest_y; value = -125.0; easing = Linear };
          { at = 2.0; param = Dest_w; value = 250.0; easing = Linear };
          { at = 2.0; param = Dest_h; value = 250.0; easing = Linear };
          { at = 2.0; param = Colour_r; value = 1.0; easing = Linear };
          { at = 2.0; param = Colour_g; value = 1.0; easing = Linear };
          { at = 2.0; param = Colour_b; value = 1.0; easing = Linear };
          { at = 2.0; param = Rotation; value = 1.8; easing = Linear };
        ];
    };
    { name = "SpellWar"; bitmap = "";
      duration = 2.0; children =
      [
        { name = "RedSparkleLite"; kind = Particle; at = 0.0; duration = 1.0; x = 0.0; y = -10.0 };
        { name = "GrowRedRing"; kind = Effect; at = 0.0; duration = 2.0; x = 0.0; y = 0.0 };
        { name = "SpellFireball0"; kind = Effect; at = 0.4; duration = 0.7; x = 10.0; y = -10.0 };
        { name = "GrowSkull"; kind = Effect; at = 0.5; duration = 1.0; x = 0.0; y = 0.0 };
        { name = "RedSparkleLite"; kind = Particle; at = 0.4; duration = 1.0; x = 0.0; y = -10.0 };
        { name = "SpellFireballSmall"; kind = Effect; at = 0.6; duration = 0.8; x = -10.0; y = 20.0 };
        { name = "CyanStun"; kind = Effect; at = 0.7; duration = 0.5; x = -20.0; y = -10.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpellWater"; bitmap = "bmp_skin_battlemisc";
      duration = 2.5; children =
      [
        { name = "GrowWater"; kind = Effect; at = 0.0; duration = 1.5; x = 0.0; y = 0.0 };
        { name = "GrowWater"; kind = Effect; at = 0.3; duration = 1.5; x = 0.0; y = 0.0 };
        { name = "GrowWater"; kind = Effect; at = 0.6; duration = 1.5; x = 0.0; y = 0.0 };
        { name = "GrowFlare"; kind = Effect; at = 0.0; duration = 2.0; x = 0.0; y = 0.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpellWeb"; bitmap = "";
      duration = 2.0; children =
      [
        { name = "GrowSpiral"; kind = Effect; at = 0.0; duration = 1.5; x = -10.0; y = -10.0 };
        { name = "GrowSpiral"; kind = Effect; at = 0.2; duration = 1.5; x = 10.0; y = 10.0 };
        { name = "GrowSpiral"; kind = Effect; at = 0.4; duration = 1.5; x = -10.0; y = 10.0 };
        { name = "GrowSpiral"; kind = Effect; at = 0.5; duration = 1.5; x = 0.0; y = 0.0 };
      ];
      initial = [ (Dest_x, 0.0); (Dest_y, 0.0); ];
      keys = [];
    };
    { name = "SpinBlackHole"; bitmap = "bmp_skin_battlemisc";
      duration = 1.5; children =
      [];
      initial = [ (Source_x, 404.0); (Source_y, 257.0); (Source_w, 100.0); (Source_h, 100.0); (Dest_x, -40.0); (Dest_y, -40.0); (Dest_w, 80.0); (Dest_h, 80.0); (Alpha, 1.0); (Rotation, 0.0); (Colour_r, 0.6); (Colour_g, 0.7); (Colour_b, 0.7); ];
      keys =
        [
          { at = 1.0; param = Alpha; value = 1.0; easing = Linear };
          { at = 1.5; param = Alpha; value = 0.0; easing = Linear };
          { at = 1.5; param = Rotation; value = 26.0; easing = Linear };
          { at = 1.5; param = Dest_x; value = -300.0; easing = Linear };
          { at = 1.5; param = Dest_y; value = -300.0; easing = Linear };
          { at = 1.5; param = Dest_w; value = 600.0; easing = Linear };
          { at = 1.5; param = Dest_h; value = 600.0; easing = Linear };
        ];
    };
    { name = "SpinBlueBlade"; bitmap = "bmp_skin_battlemisc";
      duration = 1.0; children =
      [];
      initial = [ (Source_x, 101.0); (Source_y, 358.0); (Source_w, 100.0); (Source_h, 100.0); (Dest_x, -30.0); (Dest_y, -30.0); (Dest_w, 60.0); (Dest_h, 60.0); (Alpha, 0.0); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.2; param = Alpha; value = 0.5; easing = Linear };
          { at = 0.4; param = Dest_x; value = -100.0; easing = Linear };
          { at = 0.4; param = Dest_y; value = -100.0; easing = Linear };
          { at = 0.4; param = Dest_w; value = 200.0; easing = Linear };
          { at = 0.4; param = Dest_h; value = 200.0; easing = Linear };
          { at = 0.8; param = Alpha; value = 0.8; easing = Linear };
          { at = 0.8; param = Dest_x; value = -170.0; easing = Linear };
          { at = 0.8; param = Dest_y; value = -170.0; easing = Linear };
          { at = 0.8; param = Dest_w; value = 350.0; easing = Linear };
          { at = 0.8; param = Dest_h; value = 350.0; easing = Linear };
          { at = 0.8; param = Rotation; value = -25.0; easing = Linear };
          { at = 1.0; param = Alpha; value = 0.0; easing = Linear };
          { at = 1.0; param = Dest_x; value = -30.0; easing = Linear };
          { at = 1.0; param = Dest_y; value = -30.0; easing = Linear };
          { at = 1.0; param = Dest_w; value = 100.0; easing = Linear };
          { at = 1.0; param = Dest_h; value = 100.0; easing = Linear };
          { at = 1.0; param = Rotation; value = -50.0; easing = Linear };
        ];
    };
    { name = "SpinFlare"; bitmap = "bmp_skin_battlemisc";
      duration = 2.0; children =
      [];
      initial = [ (Source_x, 0.0); (Source_y, 462.0); (Source_w, 200.0); (Source_h, 50.0); (Dest_x, -150.0); (Dest_y, -37.0); (Dest_w, 300.0); (Dest_h, 75.0); (Alpha, 0.5); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 1.0; param = Alpha; value = 1.0; easing = Linear };
          { at = 2.0; param = Alpha; value = 0.0; easing = Linear };
          { at = 2.0; param = Rotation; value = 28.0; easing = Linear };
          { at = 2.0; param = Dest_x; value = -250.0; easing = Linear };
          { at = 2.0; param = Dest_y; value = -75.0; easing = Linear };
          { at = 2.0; param = Dest_w; value = 500.0; easing = Linear };
          { at = 2.0; param = Dest_h; value = 150.0; easing = Linear };
        ];
    };
    { name = "SwapGem"; bitmap = "bmp_skin_battlemisc";
      duration = 0.7; children =
      [];
      initial = [ (Source_x, 220.0); (Source_y, 74.0); (Source_w, 128.0); (Source_h, 128.0); (Dest_x, -64.0); (Dest_y, -64.0); (Dest_w, 128.0); (Dest_h, 128.0); (Alpha, 0.8); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.7; param = Alpha; value = 0.0; easing = Linear };
          { at = 0.7; param = Dest_x; value = -128.0; easing = Linear };
          { at = 0.7; param = Dest_y; value = -128.0; easing = Linear };
          { at = 0.7; param = Dest_w; value = 256.0; easing = Linear };
          { at = 0.7; param = Dest_h; value = 256.0; easing = Linear };
          { at = 0.7; param = Rotation; value = 1.05; easing = Linear };
        ];
    };
    { name = "SwapGemAI"; bitmap = "bmp_skin_battlemisc";
      duration = 0.7; children =
      [];
      initial = [ (Source_x, 91.0); (Source_y, 74.0); (Source_w, 128.0); (Source_h, 128.0); (Dest_x, -64.0); (Dest_y, -64.0); (Dest_w, 128.0); (Dest_h, 128.0); (Alpha, 0.8); (Rotation, 0.0); (Colour_r, 1.0); (Colour_g, 1.0); (Colour_b, 1.0); ];
      keys =
        [
          { at = 0.7; param = Alpha; value = 0.0; easing = Linear };
          { at = 0.7; param = Dest_x; value = -128.0; easing = Linear };
          { at = 0.7; param = Dest_y; value = -128.0; easing = Linear };
          { at = 0.7; param = Dest_w; value = 256.0; easing = Linear };
          { at = 0.7; param = Dest_h; value = 256.0; easing = Linear };
          { at = 0.7; param = Rotation; value = 1.05; easing = Linear };
        ];
    };
  ]

let particles =
  [
    { name = "Arrive"; texture = "Sparkle.png";
      radius = 0.05; lifetime = 1000;
      max = 15; release = 15;
      interval = 0.05; life = 1.0;
      total = Some 15;
      blend = Additive; size = 0.1;
      colour = { r = 0.9; g = 0.5; b = 0.1; a = 1.0 };
      to_size = 0.05;
      to_colour = { r = 0.6; g = 0.3; b = 0.05; a = 0.0 };
      start = 0.5;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.1;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.5;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "CyanExplosion"; texture = "Sparkle.png";
      radius = 0.2; lifetime = 1200;
      max = 100; release = 100;
      interval = 0.05; life = 1.2;
      total = Some 100;
      blend = Additive; size = 0.25;
      colour = { r = 0.2; g = 0.8; b = 0.8; a = 0.7 };
      to_size = 0.1;
      to_colour = { r = 0.1; g = 0.5; b = 0.5; a = 0.0 };
      start = 0.6;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.3;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 1.2;
      gravity = { x = 0.0; y = -2.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "CyanSparkle"; texture = "Sparkle.png";
      radius = 8.0; lifetime = 1600;
      max = 40; release = 6;
      interval = 0.05; life = 0.6;
      total = Some 40;
      blend = Additive; size = 0.4;
      colour = { r = 0.1; g = 0.9; b = 0.9; a = 0.8 };
      to_size = 0.05;
      to_colour = { r = 0.5; g = 0.9; b = 0.9; a = 0.0 };
      start = 0.3;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.3;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.1;
      gravity = { x = 0.0; y = 1.5; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 2 };
    { name = "GreenExplosion"; texture = "Sparkle.png";
      radius = 0.2; lifetime = 1200;
      max = 100; release = 100;
      interval = 0.05; life = 1.2;
      total = Some 100;
      blend = Additive; size = 0.25;
      colour = { r = 0.2; g = 0.8; b = 0.2; a = 0.7 };
      to_size = 0.1;
      to_colour = { r = 0.1; g = 0.5; b = 0.1; a = 0.0 };
      start = 0.6;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.3;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 1.2;
      gravity = { x = 0.0; y = -2.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "GreenSkulls"; texture = "Skull.png";
      radius = 0.2; lifetime = 2200;
      max = 20; release = 1;
      interval = 0.05; life = 1.2;
      total = Some 20;
      blend = Additive; size = 0.05;
      colour = { r = 0.1; g = 0.9; b = 0.1; a = 1.0 };
      to_size = 1.0;
      to_colour = { r = 0.05; g = 0.8; b = 0.05; a = 0.0 };
      start = 0.6;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.1;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = Some "on";
      velocity_planes = Some "110";
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.8;
      gravity = { x = 0.0; y = 0.0; z = -2.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "GreenSparkle"; texture = "Sparkle.png";
      radius = 8.0; lifetime = 1600;
      max = 40; release = 6;
      interval = 0.05; life = 0.6;
      total = Some 40;
      blend = Additive; size = 0.4;
      colour = { r = 0.1; g = 0.9; b = 0.1; a = 0.8 };
      to_size = 0.05;
      to_colour = { r = 0.5; g = 0.5; b = 0.1; a = 0.0 };
      start = 0.3;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.4;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.1;
      gravity = { x = 0.0; y = 1.5; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 2 };
    { name = "ItemSparkle"; texture = "Sparkle.png";
      radius = 8.0; lifetime = 1200;
      max = 16; release = 16;
      interval = 0.05; life = 1.0;
      total = Some 16;
      blend = Additive; size = 0.1;
      colour = { r = 0.7; g = 0.7; b = 0.5; a = 0.8 };
      to_size = 0.05;
      to_colour = { r = 0.2; g = 0.2; b = 0.1; a = 0.0 };
      start = 0.5;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.05;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.4;
      gravity = { x = 0.0; y = 0.5; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "LargeFire"; texture = "Fire.png";
      radius = 1.0; lifetime = 0;
      max = 75; release = 4;
      interval = 0.05; life = 0.5;
      total = None;
      blend = Additive; size = 0.2;
      colour = { r = 0.9; g = 0.9; b = 0.05; a = 1.0 };
      to_size = 0.04;
      to_colour = { r = 0.9; g = 0.05; b = 0.05; a = 0.7 };
      start = 0.0;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.06;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.4; z = 0.0 };
      velocity_var = 0.1;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = true;
      wind = false;
      shape_steps = 1 };
    { name = "LargeSmoke"; texture = "Smoke.png";
      radius = 5.0; lifetime = 0;
      max = 80; release = 1;
      interval = 0.1; life = 4.0;
      total = None;
      blend = Alpha_blend; size = 0.2;
      colour = { r = 0.9; g = 0.9; b = 0.9; a = 1.0 };
      to_size = 1.0;
      to_colour = { r = 0.8; g = 0.8; b = 0.8; a = 0.0 };
      start = 0.3;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.02;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.8; z = 0.0 };
      velocity_var = 0.2;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = true;
      wind = true;
      shape_steps = 1 };
    { name = "MessageCyan"; texture = "Sparkle.png";
      radius = 0.05; lifetime = 1000;
      max = 3; release = 3;
      interval = 0.05; life = 1.0;
      total = None;
      blend = Additive; size = 0.2;
      colour = { r = 0.1; g = 0.9; b = 0.9; a = 1.0 };
      to_size = 0.05;
      to_colour = { r = 0.05; g = 0.6; b = 0.6; a = 0.0 };
      start = 0.0;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.1;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.15;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "MessageGreen"; texture = "Sparkle.png";
      radius = 0.05; lifetime = 1000;
      max = 3; release = 3;
      interval = 0.05; life = 1.0;
      total = None;
      blend = Additive; size = 0.2;
      colour = { r = 0.1; g = 0.9; b = 0.1; a = 1.0 };
      to_size = 0.05;
      to_colour = { r = 0.05; g = 0.6; b = 0.05; a = 0.0 };
      start = 0.0;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.1;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.15;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "MessageOrange"; texture = "Sparkle.png";
      radius = 0.05; lifetime = 1000;
      max = 3; release = 3;
      interval = 0.05; life = 1.0;
      total = None;
      blend = Additive; size = 0.2;
      colour = { r = 0.9; g = 0.5; b = 0.1; a = 1.0 };
      to_size = 0.05;
      to_colour = { r = 0.6; g = 0.3; b = 0.05; a = 0.0 };
      start = 0.0;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.1;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.15;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "MessagePurple"; texture = "Sparkle.png";
      radius = 0.05; lifetime = 1000;
      max = 3; release = 3;
      interval = 0.05; life = 1.0;
      total = None;
      blend = Additive; size = 0.2;
      colour = { r = 0.7; g = 0.1; b = 0.9; a = 1.0 };
      to_size = 0.05;
      to_colour = { r = 0.5; g = 0.05; b = 0.6; a = 0.0 };
      start = 0.0;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.1;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.15;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "MessageRed"; texture = "Sparkle.png";
      radius = 0.05; lifetime = 1000;
      max = 3; release = 3;
      interval = 0.05; life = 1.0;
      total = None;
      blend = Additive; size = 0.2;
      colour = { r = 0.9; g = 0.1; b = 0.1; a = 1.0 };
      to_size = 0.05;
      to_colour = { r = 0.6; g = 0.05; b = 0.05; a = 0.0 };
      start = 0.0;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.1;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.15;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "MessageWhite"; texture = "Sparkle.png";
      radius = 0.05; lifetime = 1000;
      max = 30; release = 3;
      interval = 0.05; life = 1.0;
      total = Some 30;
      blend = Additive; size = 0.1;
      colour = { r = 0.8; g = 0.8; b = 0.6; a = 1.0 };
      to_size = 0.05;
      to_colour = { r = 0.6; g = 0.6; b = 0.4; a = 0.0 };
      start = 0.0;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.1;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.3;
      gravity = { x = 0.0; y = -4.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "MessageYellow"; texture = "Sparkle.png";
      radius = 0.05; lifetime = 1000;
      max = 3; release = 3;
      interval = 0.05; life = 1.0;
      total = None;
      blend = Additive; size = 0.2;
      colour = { r = 0.9; g = 0.9; b = 0.1; a = 1.0 };
      to_size = 0.05;
      to_colour = { r = 0.6; g = 0.6; b = 0.05; a = 0.0 };
      start = 0.0;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.1;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.15;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "NewEncounter"; texture = "Sparkle.png";
      radius = 8.0; lifetime = 2500;
      max = 40; release = 6;
      interval = 0.05; life = 0.9;
      total = Some 40;
      blend = Additive; size = 0.25;
      colour = { r = 0.9; g = 0.5; b = 0.3; a = 0.9 };
      to_size = 0.05;
      to_colour = { r = 0.7; g = 0.2; b = 0.1; a = 0.0 };
      start = 0.5;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.4;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 1.0; z = 0.0 };
      velocity_var = 0.8;
      gravity = { x = 0.0; y = -0.5; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "NewRuin"; texture = "Sparkle.png";
      radius = 8.0; lifetime = 2500;
      max = 40; release = 6;
      interval = 0.05; life = 0.9;
      total = Some 4;
      blend = Additive; size = 0.4;
      colour = { r = 0.5; g = 0.7; b = 0.9; a = 0.9 };
      to_size = 0.05;
      to_colour = { r = 0.2; g = 0.6; b = 0.5; a = 0.0 };
      start = 0.5;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.4;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 1.0; z = 0.0 };
      velocity_var = 0.6;
      gravity = { x = 0.0; y = -2.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "NewTurn"; texture = "Sparkle.png";
      radius = 1.0; lifetime = 1600;
      max = 80; release = 8;
      interval = 0.05; life = 1.0;
      total = Some 80;
      blend = Additive; size = 0.4;
      colour = { r = 0.9; g = 0.9; b = 0.6; a = 1.0 };
      to_size = 0.1;
      to_colour = { r = 0.9; g = 0.9; b = 0.1; a = 0.0 };
      start = 0.2;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.5;
      position_planar = Some "on";
      position_planes = Some "101";
      position_perimeter = Some "on";
      velocity_planar = Some "on";
      velocity_planes = Some "010";
      velocity = { x = 0.0; y = -0.5; z = 0.0 };
      velocity_var = 0.3;
      gravity = { x = 0.0; y = -0.5; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "OrangeSparkle"; texture = "Sparkle.png";
      radius = 8.0; lifetime = 1600;
      max = 40; release = 6;
      interval = 0.05; life = 0.6;
      total = Some 40;
      blend = Additive; size = 0.4;
      colour = { r = 1.0; g = 0.6; b = 0.1; a = 0.8 };
      to_size = 0.05;
      to_colour = { r = 0.9; g = 0.9; b = 0.5; a = 0.0 };
      start = 0.3;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.4;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.1;
      gravity = { x = 0.0; y = 1.5; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 2 };
    { name = "PurpleSparkle"; texture = "Sparkle.png";
      radius = 8.0; lifetime = 1600;
      max = 40; release = 6;
      interval = 0.05; life = 0.6;
      total = Some 40;
      blend = Additive; size = 0.4;
      colour = { r = 0.9; g = 0.1; b = 0.9; a = 0.8 };
      to_size = 0.05;
      to_colour = { r = 0.9; g = 0.5; b = 0.9; a = 0.0 };
      start = 0.3;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.4;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.1;
      gravity = { x = 0.0; y = 1.5; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 2 };
    { name = "Rebellion"; texture = "Fire.png";
      radius = 1.0; lifetime = 1200;
      max = 30; release = 30;
      interval = 0.05; life = 1.2;
      total = Some 30;
      blend = Additive; size = 0.6;
      colour = { r = 0.9; g = 0.9; b = 0.1; a = 1.0 };
      to_size = 0.1;
      to_colour = { r = 0.9; g = 0.3; b = 0.1; a = 0.0 };
      start = 0.2;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.1;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.5;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "RedExplosion"; texture = "Sparkle.png";
      radius = 0.2; lifetime = 1200;
      max = 100; release = 100;
      interval = 0.05; life = 1.2;
      total = Some 100;
      blend = Additive; size = 0.25;
      colour = { r = 0.8; g = 0.2; b = 0.2; a = 0.7 };
      to_size = 0.1;
      to_colour = { r = 0.5; g = 0.1; b = 0.1; a = 0.0 };
      start = 0.6;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.3;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 1.2;
      gravity = { x = 0.0; y = -2.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "RedEyeGlow"; texture = "Sparkle.png";
      radius = 0.05; lifetime = 1000;
      max = 6; release = 6;
      interval = 0.05; life = 1.0;
      total = None;
      blend = Additive; size = 0.2;
      colour = { r = 0.9; g = 0.1; b = 0.1; a = 1.0 };
      to_size = 0.5;
      to_colour = { r = 0.6; g = 0.05; b = 0.05; a = 0.0 };
      start = 0.0;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.0;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.2;
      gravity = { x = 0.0; y = 0.2; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "RedSkull"; texture = "Rock.png";
      radius = 2.0; lifetime = 1200;
      max = 30; release = 30;
      interval = 0.05; life = 1.2;
      total = Some 30;
      blend = Alpha_blend; size = 0.2;
      colour = { r = 1.0; g = 1.0; b = 1.0; a = 1.0 };
      to_size = 0.15;
      to_colour = { r = 1.0; g = 0.5; b = 0.5; a = 0.0 };
      start = 0.8;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.05;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 1.5;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "RedSkulls"; texture = "Skull.png";
      radius = 0.2; lifetime = 2200;
      max = 20; release = 1;
      interval = 0.05; life = 1.2;
      total = Some 20;
      blend = Additive; size = 0.05;
      colour = { r = 0.9; g = 0.1; b = 0.1; a = 1.0 };
      to_size = 1.0;
      to_colour = { r = 0.8; g = 0.05; b = 0.05; a = 0.0 };
      start = 0.6;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.1;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = Some "on";
      velocity_planes = Some "110";
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.8;
      gravity = { x = 0.0; y = 0.0; z = -2.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "RedSparkle"; texture = "Sparkle.png";
      radius = 8.0; lifetime = 1600;
      max = 40; release = 6;
      interval = 0.05; life = 0.6;
      total = Some 40;
      blend = Additive; size = 0.4;
      colour = { r = 1.0; g = 0.1; b = 0.1; a = 0.8 };
      to_size = 0.05;
      to_colour = { r = 0.9; g = 0.5; b = 0.1; a = 0.0 };
      start = 0.3;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.4;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.1;
      gravity = { x = 0.0; y = 1.5; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 2 };
    { name = "RedSparkleLite"; texture = "Sparkle.png";
      radius = 10.0; lifetime = 1600;
      max = 40; release = 4;
      interval = 0.05; life = 0.9;
      total = Some 40;
      blend = Additive; size = 0.5;
      colour = { r = 1.0; g = 0.2; b = 0.2; a = 0.5 };
      to_size = 0.05;
      to_colour = { r = 0.7; g = 0.2; b = 0.2; a = 0.0 };
      start = 0.1;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.8;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.1;
      gravity = { x = 0.0; y = 0.5; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "RemoveEncounter"; texture = "Skull.png";
      radius = 0.2; lifetime = 1200;
      max = 20; release = 20;
      interval = 0.05; life = 1.2;
      total = Some 20;
      blend = Additive; size = 0.5;
      colour = { r = 0.1; g = 0.1; b = 0.9; a = 1.0 };
      to_size = 0.05;
      to_colour = { r = 0.2; g = 0.2; b = 0.6; a = 0.0 };
      start = 0.2;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.4;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.4;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "RingCyan"; texture = "Flare.png";
      radius = 1.0; lifetime = 1500;
      max = 240; release = 12;
      interval = 0.05; life = 0.5;
      total = Some 240;
      blend = Additive; size = 0.25;
      colour = { r = 0.1; g = 0.9; b = 0.9; a = 0.8 };
      to_size = 0.05;
      to_colour = { r = 0.1; g = 0.9; b = 0.9; a = 0.0 };
      start = 0.1;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.05;
      position_planar = Some "on";
      position_planes = Some "110";
      position_perimeter = Some "on";
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = -0.2 };
      velocity_var = 0.2;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = Some { x = 0.0; y = 0.0; z = 0.0 };
      anim_position_var = Some 0.8;
      anim_position_start = Some 0.0;
      anim_position_end = Some 1.0;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "RingGreen"; texture = "Flare.png";
      radius = 1.0; lifetime = 1500;
      max = 240; release = 12;
      interval = 0.05; life = 0.5;
      total = Some 240;
      blend = Additive; size = 0.25;
      colour = { r = 0.1; g = 0.9; b = 0.1; a = 0.8 };
      to_size = 0.05;
      to_colour = { r = 0.1; g = 0.9; b = 0.1; a = 0.0 };
      start = 0.1;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.05;
      position_planar = Some "on";
      position_planes = Some "110";
      position_perimeter = Some "on";
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = -0.2 };
      velocity_var = 0.2;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = Some { x = 0.0; y = 0.0; z = 0.0 };
      anim_position_var = Some 0.8;
      anim_position_start = Some 0.0;
      anim_position_end = Some 1.0;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "RingRed"; texture = "Flare.png";
      radius = 1.0; lifetime = 1500;
      max = 240; release = 12;
      interval = 0.05; life = 0.5;
      total = Some 240;
      blend = Additive; size = 0.25;
      colour = { r = 0.9; g = 0.1; b = 0.1; a = 0.8 };
      to_size = 0.05;
      to_colour = { r = 0.9; g = 0.1; b = 0.1; a = 0.0 };
      start = 0.1;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.05;
      position_planar = Some "on";
      position_planes = Some "110";
      position_perimeter = Some "on";
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = -0.2 };
      velocity_var = 0.2;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = Some { x = 0.0; y = 0.0; z = 0.0 };
      anim_position_var = Some 0.8;
      anim_position_start = Some 0.0;
      anim_position_end = Some 1.0;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "RingWhite"; texture = "Flare.png";
      radius = 1.0; lifetime = 1500;
      max = 240; release = 12;
      interval = 0.05; life = 0.5;
      total = Some 240;
      blend = Additive; size = 0.25;
      colour = { r = 0.9; g = 0.9; b = 0.9; a = 0.8 };
      to_size = 0.05;
      to_colour = { r = 0.9; g = 0.9; b = 0.9; a = 0.0 };
      start = 0.1;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.05;
      position_planar = Some "on";
      position_planes = Some "110";
      position_perimeter = Some "on";
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = -0.2 };
      velocity_var = 0.2;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = Some { x = 0.0; y = 0.0; z = 0.0 };
      anim_position_var = Some 0.8;
      anim_position_start = Some 0.0;
      anim_position_end = Some 1.0;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "RingYellow"; texture = "Flare.png";
      radius = 1.0; lifetime = 1500;
      max = 240; release = 12;
      interval = 0.05; life = 0.5;
      total = Some 240;
      blend = Additive; size = 0.25;
      colour = { r = 0.9; g = 0.9; b = 0.1; a = 0.8 };
      to_size = 0.05;
      to_colour = { r = 0.9; g = 0.9; b = 0.1; a = 0.0 };
      start = 0.1;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.05;
      position_planar = Some "on";
      position_planes = Some "110";
      position_perimeter = Some "on";
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = -0.2 };
      velocity_var = 0.2;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = Some { x = 0.0; y = 0.0; z = 0.0 };
      anim_position_var = Some 0.8;
      anim_position_start = Some 0.0;
      anim_position_end = Some 1.0;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "RuinSparkle0"; texture = "Sparkle.png";
      radius = 1.0; lifetime = 0;
      max = 10; release = 1;
      interval = 0.1; life = 1.0;
      total = None;
      blend = Additive; size = 0.3;
      colour = { r = 0.2; g = 0.8; b = 0.2; a = 0.9 };
      to_size = 0.15;
      to_colour = { r = 0.1; g = 1.0; b = 0.1; a = 0.0 };
      start = 0.5;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.15;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.2; z = 0.0 };
      velocity_var = 0.1;
      gravity = { x = 0.0; y = 0.5; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = true;
      wind = false;
      shape_steps = 1 };
    { name = "RuinSparkle1"; texture = "Sparkle.png";
      radius = 1.0; lifetime = 0;
      max = 20; release = 1;
      interval = 0.05; life = 1.0;
      total = None;
      blend = Additive; size = 0.35;
      colour = { r = 0.1; g = 0.2; b = 0.9; a = 0.9 };
      to_size = 0.15;
      to_colour = { r = 0.1; g = 0.35; b = 1.0; a = 0.0 };
      start = 0.5;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.25;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.2; z = 0.0 };
      velocity_var = 0.15;
      gravity = { x = 0.0; y = 0.5; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = true;
      wind = false;
      shape_steps = 1 };
    { name = "RuinSparkle2"; texture = "Sparkle.png";
      radius = 1.0; lifetime = 0;
      max = 10; release = 1;
      interval = 0.1; life = 1.0;
      total = None;
      blend = Additive; size = 0.25;
      colour = { r = 0.8; g = 0.8; b = 0.7; a = 0.8 };
      to_size = 0.1;
      to_colour = { r = 1.0; g = 1.0; b = 1.0; a = 0.0 };
      start = 0.2;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.15;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.2; z = 0.0 };
      velocity_var = 0.1;
      gravity = { x = 0.0; y = 0.5; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = true;
      wind = false;
      shape_steps = 1 };
    { name = "RuinSparkle3"; texture = "Sparkle.png";
      radius = 1.0; lifetime = 0;
      max = 10; release = 1;
      interval = 0.1; life = 1.0;
      total = None;
      blend = Additive; size = 0.25;
      colour = { r = 0.8; g = 0.8; b = 0.1; a = 0.8 };
      to_size = 0.1;
      to_colour = { r = 1.0; g = 1.0; b = 0.1; a = 0.0 };
      start = 0.2;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.15;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.2; z = 0.0 };
      velocity_var = 0.1;
      gravity = { x = 0.0; y = 0.5; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = true;
      wind = false;
      shape_steps = 1 };
    { name = "RuinSparkle4"; texture = "Sparkle.png";
      radius = 1.0; lifetime = 0;
      max = 10; release = 1;
      interval = 0.1; life = 1.0;
      total = None;
      blend = Additive; size = 0.25;
      colour = { r = 0.8; g = 0.1; b = 0.1; a = 0.8 };
      to_size = 0.1;
      to_colour = { r = 1.0; g = 0.1; b = 0.1; a = 0.0 };
      start = 0.2;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.15;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.2; z = 0.0 };
      velocity_var = 0.1;
      gravity = { x = 0.0; y = 0.5; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = true;
      wind = false;
      shape_steps = 1 };
    { name = "SmallFire"; texture = "Fire.png";
      radius = 1.0; lifetime = 0;
      max = 70; release = 8;
      interval = 0.05; life = 0.4;
      total = None;
      blend = Additive; size = 0.15;
      colour = { r = 0.9; g = 0.9; b = 0.05; a = 1.0 };
      to_size = 0.03;
      to_colour = { r = 0.9; g = 0.05; b = 0.05; a = 0.7 };
      start = 0.0;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.02;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.3; z = 0.0 };
      velocity_var = 0.1;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = true;
      wind = false;
      shape_steps = 1 };
    { name = "SmallSmoke"; texture = "Smoke.png";
      radius = 1.0; lifetime = 0;
      max = 10; release = 1;
      interval = 0.15; life = 1.5;
      total = None;
      blend = Alpha_blend; size = 0.1;
      colour = { r = 0.9; g = 0.9; b = 0.9; a = 1.0 };
      to_size = 0.5;
      to_colour = { r = 0.8; g = 0.8; b = 0.8; a = 0.0 };
      start = 0.3;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.0;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.3; z = 0.0 };
      velocity_var = 0.2;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = true;
      wind = true;
      shape_steps = 1 };
    { name = "Sparks"; texture = "Sparkle.png";
      radius = 2.0; lifetime = 1500;
      max = 80; release = 80;
      interval = 0.05; life = 1.0;
      total = Some 80;
      blend = Additive; size = 0.4;
      colour = { r = 0.8; g = 0.8; b = 0.4; a = 1.0 };
      to_size = 0.1;
      to_colour = { r = 0.5; g = 0.5; b = 0.0; a = 0.0 };
      start = 0.5;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.1;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 1.5;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "Spell0"; texture = "Sparkle.png";
      radius = 0.2; lifetime = 1800;
      max = 16; release = 16;
      interval = 0.05; life = 1.8;
      total = Some 16;
      blend = Additive; size = 0.2;
      colour = { r = 0.9; g = 0.9; b = 0.05; a = 0.9 };
      to_size = 1.6;
      to_colour = { r = 0.9; g = 0.9; b = 0.05; a = 0.0 };
      start = 0.3;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.3;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.2; z = 0.0 };
      velocity_var = 0.8;
      gravity = { x = 0.0; y = -0.2; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "Spell1"; texture = "Sparkle.png";
      radius = 0.2; lifetime = 1800;
      max = 16; release = 16;
      interval = 0.05; life = 1.8;
      total = Some 16;
      blend = Additive; size = 0.2;
      colour = { r = 0.05; g = 0.9; b = 0.9; a = 0.9 };
      to_size = 1.2;
      to_colour = { r = 0.05; g = 0.5; b = 0.9; a = 0.0 };
      start = 0.2;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.3;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.4; z = 0.0 };
      velocity_var = 0.8;
      gravity = { x = 0.0; y = -0.4; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "Travel"; texture = "Sparkle.png";
      radius = 0.05; lifetime = 1500;
      max = 4; release = 4;
      interval = 0.05; life = 1.5;
      total = Some 4;
      blend = Additive; size = 0.3;
      colour = { r = 0.9; g = 0.5; b = 0.1; a = 1.0 };
      to_size = 0.05;
      to_colour = { r = 0.6; g = 0.3; b = 0.05; a = 0.0 };
      start = 0.5;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.1;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.3;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "WhiteExplosion"; texture = "Sparkle.png";
      radius = 0.2; lifetime = 1200;
      max = 100; release = 100;
      interval = 0.05; life = 1.2;
      total = Some 100;
      blend = Additive; size = 0.25;
      colour = { r = 0.8; g = 0.8; b = 0.8; a = 0.7 };
      to_size = 0.1;
      to_colour = { r = 0.5; g = 0.5; b = 0.5; a = 0.0 };
      start = 0.6;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.3;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 1.2;
      gravity = { x = 0.0; y = -2.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "WhiteSparkle"; texture = "Sparkle.png";
      radius = 8.0; lifetime = 1600;
      max = 40; release = 6;
      interval = 0.05; life = 0.6;
      total = Some 40;
      blend = Additive; size = 0.4;
      colour = { r = 0.7; g = 0.7; b = 0.7; a = 0.8 };
      to_size = 0.05;
      to_colour = { r = 0.7; g = 0.7; b = 0.5; a = 0.0 };
      start = 0.3;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.4;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.1;
      gravity = { x = 0.0; y = 1.5; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 2 };
    { name = "WhiteSparkleLite"; texture = "Sparkle.png";
      radius = 10.0; lifetime = 1600;
      max = 40; release = 4;
      interval = 0.05; life = 0.9;
      total = Some 40;
      blend = Additive; size = 0.5;
      colour = { r = 0.7; g = 0.7; b = 0.7; a = 0.5 };
      to_size = 0.05;
      to_colour = { r = 0.7; g = 0.7; b = 0.5; a = 0.0 };
      start = 0.1;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.8;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.1;
      gravity = { x = 0.0; y = 0.5; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "Wildcard"; texture = "Sparkle.png";
      radius = 0.2; lifetime = 1200;
      max = 100; release = 100;
      interval = 0.05; life = 1.2;
      total = Some 100;
      blend = Additive; size = 0.25;
      colour = { r = 0.9; g = 0.5; b = 0.5; a = 0.7 };
      to_size = 0.1;
      to_colour = { r = 0.9; g = 0.9; b = 0.6; a = 0.0 };
      start = 0.6;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.1;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 1.6;
      gravity = { x = 0.0; y = 0.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "YellowExplosion"; texture = "Sparkle.png";
      radius = 0.2; lifetime = 1200;
      max = 100; release = 100;
      interval = 0.05; life = 1.2;
      total = Some 100;
      blend = Additive; size = 0.25;
      colour = { r = 0.8; g = 0.8; b = 0.2; a = 0.7 };
      to_size = 0.1;
      to_colour = { r = 0.5; g = 0.5; b = 0.1; a = 0.0 };
      start = 0.6;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.3;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 1.2;
      gravity = { x = 0.0; y = -2.0; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 1 };
    { name = "YellowSparkle"; texture = "Sparkle.png";
      radius = 8.0; lifetime = 1600;
      max = 40; release = 6;
      interval = 0.05; life = 0.6;
      total = Some 40;
      blend = Additive; size = 0.4;
      colour = { r = 0.9; g = 0.9; b = 0.1; a = 0.8 };
      to_size = 0.05;
      to_colour = { r = 0.9; g = 0.5; b = 0.5; a = 0.0 };
      start = 0.3;
      position = { x = 0.0; y = 0.0; z = 0.0 };
      position_var = 0.4;
      position_planar = None;
      position_planes = None;
      position_perimeter = None;
      velocity_planar = None;
      velocity_planes = None;
      velocity = { x = 0.0; y = 0.0; z = 0.0 };
      velocity_var = 0.1;
      gravity = { x = 0.0; y = 1.5; z = 0.0 };
      anim_position = None;
      anim_position_var = None;
      anim_position_start = None;
      anim_position_end = None;
      air_resistance = false;
      wind = false;
      shape_steps = 2 };
  ]

(** The named effect, if the archive has one. *)
let effect_of name =
  try Some (List.find (fun (e : effect_desc) -> e.name = name) effects)
  with Not_found -> None

let particle_of name =
  try Some (List.find (fun (p : particle) -> p.name = name) particles)
  with Not_found -> None

(** Every particle texture in the archive.

    Six files, 32x32 or 64x64, and none of them a registry frame - so they are
    loaded whole rather than cut up out of a sheet. [Particle.radius] is the
    other half of the sizing story, and it is why. *)
let textures =
  [
    "Sparkle.png";
    "Skull.png";
    "Fire.png";
    "Smoke.png";
    "Rock.png";
    "Flare.png";
  ]

