(* Generated by tools/extract_skin_data.py from game/Assets.zip. Do not edit.

   The game's own bitmap registry, Assets/Assets.xml, in two parts:

   - a [sheet]: a tag and the image behind it;
   - a [frame]: a named rectangle inside a sheet, with the size it is meant
     to be *drawn* at as well as the size it is stored at.

   422 named frames. This is the decoration vocabulary of the whole game - the
   backdrop and its border, the selection glow, the turn-timer backgrounds,
   button states, dialog furniture - so a renderer should look tags up here
   rather than carry coordinates of its own. The gem frames the port needs are
   in this table too, which means [test_skin_data] can check the port's gem
   coordinates against the registry instead of trusting them.

   [dest_w] and [dest_h] are worth keeping: several frames are stored larger
   than they are drawn, the red glow frames being 88x88 on disk for 64x64 on
   screen, so the registry is the only place that knows to scale them. *)

type sheet = { tag : string; file : string }  (** no extension: see the note in the generator *)

type frame = {
  tag : string;
  sheet : string;
  x : int;
  y : int;
  w : int;
  h : int;
  dest_w : int;
  dest_h : int;
}

let sheets : sheet array =
  [|
    { tag = "bmp_skinsidepanel"; file = "Assets/Skin/Skin_SidePanel" };
    { tag = "bmp_skinsidepanel_game"; file = "Assets/Skin/Skin_SidePanel_Battle" };
    { tag = "bmp_skin_backdrop"; file = "Assets/Skin/Skin_Backdrop_Standard" };
    { tag = "bmp_skin_buttmain"; file = "Assets/Skin/Skin_Buttons_Main" };
    { tag = "bmp_skin_buttmisc"; file = "Assets/Skin/Skin_Buttons_Misc" };
    { tag = "bmp_skin_dlgmain"; file = "Assets/Skin/Skin_Dialogs_Main" };
    { tag = "bmp_skin_dlgchar"; file = "Assets/Skin/Skin_Dialogs_Character" };
    { tag = "bmp_skin_battlemisc"; file = "Assets/Skin/Skin_Battle_Misc" };
    { tag = "bmp_skin_gemsgrid"; file = "Assets/Skin/Skin_Gems_Grid" };
    { tag = "bmp_skin_gamepad"; file = "Assets/Skin/Skin_Gamepad" };
    { tag = "bmp_skin_splash"; file = "Assets/Skin/Skin_Splash" };
    { tag = "bmp_skin_xbla_mp"; file = "Assets/Graphics/MatchIcons" };
    { tag = "bmp_combatfx"; file = "Assets/Graphics/CombatEffectBits" };
    { tag = "bmp_rays"; file = "Assets/Graphics/Rays" };
    { tag = "bmp_maincursor"; file = "Assets/Cursors/MainCursor" };
    { tag = "bmp_mist"; file = "Assets/Graphics/Mist" };
    { tag = "bmp_portraits"; file = "Assets/Portraits/Portrait_Knight0" };
    { tag = "bmp_listportraits"; file = "Assets/Portraits/Portrait_Knight0" };
    { tag = "bmp_enemyportrait"; file = "Assets/Portraits/Portrait_Knight0" };
    { tag = "bmp_items"; file = "Assets/Graphics/Items" };
    { tag = "bmp_resistspell"; file = "Assets/Graphics/ResistMessage" };
    { tag = "bmp_statuseffects"; file = "Assets/Graphics/StatusEffects" };
    { tag = "bmp_listbox"; file = "Assets/Graphics/Listbox" };
    { tag = "bmp_quest"; file = "Assets/Graphics/Quest_OrcKing" };
    { tag = "bmp_features"; file = "Assets/Graphics/Sites" };
    { tag = "bmp_cities"; file = "Assets/Graphics/Cities" };
    { tag = "bmp_charportrait0"; file = "Assets/Portraits/Portrait_Knight0" };
    { tag = "bmp_charportrait1"; file = "Assets/Portraits/Portrait_Knight0" };
    { tag = "bmp_scroll"; file = "Assets/Graphics/Scroll" };
    { tag = "bmp_citybits"; file = "Assets/Graphics/CityBits" };
    { tag = "bmp_compportrait"; file = "Assets/Portraits/Portrait_Knight0" };
    { tag = "bmp_charicons"; file = "Assets/Graphics/CharIcons" };
    { tag = "bmp_messages"; file = "English/Messages" };
    { tag = "bmp_rules"; file = "English/Rules_SpellGame" };
    { tag = "bmp_opptute"; file = "Assets/Graphics/OppTuteDialog" };
    { tag = "bmp_opptute2"; file = "Assets/Graphics/OppTuteDialog2" };
    { tag = "bmp_spritehero"; file = "Assets/Graphics/Hero_Knight" };
    { tag = "bmp_conversationbg"; file = "Assets/Conversations/Conv_Forest" };
    { tag = "bmp_speechbubble"; file = "Assets/Graphics/SpeechBubble" };
    { tag = "bmp_characterbg"; file = "Assets/Graphics/CharacterBackdrop" };
    { tag = "bmp_inttut"; file = "Assets/Graphics/InteractiveTutorial" };
    { tag = "bmp_tavern"; file = "Assets/Graphics/Tavern" };
    { tag = "bmp_controls"; file = "English/Controls" };
    { tag = "bmp_hourglass"; file = "Assets/Graphics/Hourglass" };
  |]

let sheet_of_tag (tag : string) : sheet option =
  let rec go (l : sheet list) =
    match l with
    | [] -> None
    | (s : sheet) :: rest -> if s.tag = tag then Some s else go rest
  in
  go (Array.to_list sheets)

let frames : frame array =
  [|
    { tag = "img_sidepanel_l"; sheet = "bmp_skinsidepanel"; x = 0; y = 0; w = 176; h = 768; dest_w = 176; dest_h = 768 };
    { tag = "img_sidepanel_r"; sheet = "bmp_skinsidepanel"; x = 177; y = 0; w = 176; h = 768; dest_w = 176; dest_h = 768 };
    { tag = "img_sidepanel_l_top"; sheet = "bmp_skinsidepanel"; x = 0; y = 0; w = 176; h = 95; dest_w = 176; dest_h = 95 };
    { tag = "img_sidepanel_r_top"; sheet = "bmp_skinsidepanel"; x = 177; y = 0; w = 176; h = 95; dest_w = 176; dest_h = 95 };
    { tag = "img_sidepanel0"; sheet = "bmp_skinsidepanel_game"; x = 0; y = 0; w = 103; h = 768; dest_w = 103; dest_h = 768 };
    { tag = "img_sidepanel1"; sheet = "bmp_skinsidepanel_game"; x = 153; y = 0; w = 103; h = 768; dest_w = 103; dest_h = 768 };
    { tag = "img_sidepanel_top_xb360"; sheet = "bmp_skinsidepanel"; x = 0; y = 927; w = 102; h = 97; dest_w = 102; dest_h = 97 };
    { tag = "img_sidepanel_conv0"; sheet = "bmp_skinsidepanel"; x = 383; y = 0; w = 64; h = 512; dest_w = 64; dest_h = 512 };
    { tag = "img_sidepanel_conv1"; sheet = "bmp_skinsidepanel"; x = 448; y = 0; w = 64; h = 512; dest_w = 64; dest_h = 512 };
    { tag = "img_sidepanel_edge"; sheet = "bmp_skinsidepanel"; x = 142; y = 999; w = 370; h = 25; dest_w = 370; dest_h = 25 };
    { tag = "img_ci_earth"; sheet = "bmp_charicons"; x = 0; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_ci_fire"; sheet = "bmp_charicons"; x = 32; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_ci_air"; sheet = "bmp_charicons"; x = 64; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_ci_water"; sheet = "bmp_charicons"; x = 96; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_ci_battle"; sheet = "bmp_charicons"; x = 128; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_ci_cunning"; sheet = "bmp_charicons"; x = 160; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_ci_morale"; sheet = "bmp_charicons"; x = 192; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_ci_spell0"; sheet = "bmp_charicons"; x = 0; y = 32; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_ci_spell1"; sheet = "bmp_charicons"; x = 32; y = 32; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_ci_locn0"; sheet = "bmp_charicons"; x = 64; y = 32; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_ci_locn1"; sheet = "bmp_charicons"; x = 96; y = 32; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_ci_locn2"; sheet = "bmp_charicons"; x = 128; y = 32; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_ci_locn3"; sheet = "bmp_charicons"; x = 160; y = 32; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_ci_rune"; sheet = "bmp_charicons"; x = 192; y = 32; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_rules"; sheet = "bmp_rules"; x = 0; y = 0; w = 128; h = 395; dest_w = 128; dest_h = 395 };
    { tag = "img_rules_xbox"; sheet = "bmp_rules"; x = 0; y = 0; w = 256; h = 416; dest_w = 256; dest_h = 416 };
    { tag = "img_opptute0"; sheet = "bmp_opptute"; x = 0; y = 0; w = 256; h = 128; dest_w = 256; dest_h = 128 };
    { tag = "img_opptute1"; sheet = "bmp_opptute"; x = 0; y = 128; w = 256; h = 128; dest_w = 256; dest_h = 128 };
    { tag = "img_opptute2"; sheet = "bmp_opptute"; x = 0; y = 256; w = 224; h = 176; dest_w = 224; dest_h = 176 };
    { tag = "img_opptute3"; sheet = "bmp_opptute2"; x = 0; y = 0; w = 256; h = 128; dest_w = 256; dest_h = 128 };
    { tag = "img_opptute4"; sheet = "bmp_opptute2"; x = 0; y = 128; w = 256; h = 128; dest_w = 256; dest_h = 128 };
    { tag = "img_butthide_act"; sheet = "bmp_inttut"; x = 336; y = 0; w = 40; h = 18; dest_w = 40; dest_h = 18 };
    { tag = "img_butthide_hi"; sheet = "bmp_inttut"; x = 336; y = 20; w = 40; h = 18; dest_w = 40; dest_h = 18 };
    { tag = "img_butthide_pres"; sheet = "bmp_inttut"; x = 336; y = 40; w = 40; h = 18; dest_w = 40; dest_h = 18 };
    { tag = "img_butthide_gray"; sheet = "bmp_inttut"; x = 336; y = 60; w = 40; h = 18; dest_w = 40; dest_h = 18 };
    { tag = "img_tavern"; sheet = "bmp_tavern"; x = 0; y = 0; w = 180; h = 220; dest_w = 180; dest_h = 220 };
    { tag = "img_controls"; sheet = "bmp_controls"; x = 0; y = 0; w = 1024; h = 768; dest_w = 1024; dest_h = 768 };
    { tag = "img_hgl00"; sheet = "bmp_hourglass"; x = 0; y = 0; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl01"; sheet = "bmp_hourglass"; x = 30; y = 0; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl02"; sheet = "bmp_hourglass"; x = 60; y = 0; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl03"; sheet = "bmp_hourglass"; x = 90; y = 0; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl04"; sheet = "bmp_hourglass"; x = 120; y = 0; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl05"; sheet = "bmp_hourglass"; x = 150; y = 0; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl06"; sheet = "bmp_hourglass"; x = 180; y = 0; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl07"; sheet = "bmp_hourglass"; x = 210; y = 0; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl08"; sheet = "bmp_hourglass"; x = 0; y = 38; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl09"; sheet = "bmp_hourglass"; x = 30; y = 38; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl10"; sheet = "bmp_hourglass"; x = 60; y = 38; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl11"; sheet = "bmp_hourglass"; x = 90; y = 38; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl12"; sheet = "bmp_hourglass"; x = 120; y = 38; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl13"; sheet = "bmp_hourglass"; x = 150; y = 38; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl14"; sheet = "bmp_hourglass"; x = 180; y = 38; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl15"; sheet = "bmp_hourglass"; x = 210; y = 38; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl16"; sheet = "bmp_hourglass"; x = 0; y = 76; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl17"; sheet = "bmp_hourglass"; x = 30; y = 76; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl18"; sheet = "bmp_hourglass"; x = 60; y = 76; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl19"; sheet = "bmp_hourglass"; x = 90; y = 76; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl20"; sheet = "bmp_hourglass"; x = 120; y = 76; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl21"; sheet = "bmp_hourglass"; x = 150; y = 76; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl22"; sheet = "bmp_hourglass"; x = 180; y = 76; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_hgl23"; sheet = "bmp_hourglass"; x = 210; y = 76; w = 30; h = 38; dest_w = 30; dest_h = 38 };
    { tag = "img_splash"; sheet = "bmp_skin_splash"; x = 0; y = 0; w = 1024; h = 768; dest_w = 1024; dest_h = 768 };
    { tag = "img_border_top"; sheet = "bmp_skin_backdrop"; x = 0; y = 0; w = 1024; h = 95; dest_w = 1024; dest_h = 95 };
    { tag = "img_border_left"; sheet = "bmp_skin_backdrop"; x = 0; y = 95; w = 19; h = 653; dest_w = 19; dest_h = 653 };
    { tag = "img_border_right"; sheet = "bmp_skin_backdrop"; x = 1003; y = 95; w = 21; h = 653; dest_w = 21; dest_h = 653 };
    { tag = "img_border_bottom"; sheet = "bmp_skin_backdrop"; x = 0; y = 748; w = 1024; h = 20; dest_w = 1024; dest_h = 20 };
    { tag = "img_border_top_xbox"; sheet = "bmp_skin_backdrop"; x = 0; y = 0; w = 1024; h = 117; dest_w = 1024; dest_h = 117 };
    { tag = "img_redglow_00"; sheet = "bmp_skin_buttmisc"; x = 261; y = 231; w = 88; h = 88; dest_w = 64; dest_h = 64 };
    { tag = "img_redglow_01"; sheet = "bmp_skin_buttmisc"; x = 263; y = 233; w = 84; h = 84; dest_w = 64; dest_h = 64 };
    { tag = "img_redglow_02"; sheet = "bmp_skin_buttmisc"; x = 265; y = 235; w = 80; h = 80; dest_w = 64; dest_h = 64 };
    { tag = "img_redglow_03"; sheet = "bmp_skin_buttmisc"; x = 267; y = 237; w = 76; h = 76; dest_w = 64; dest_h = 64 };
    { tag = "img_redglow_04"; sheet = "bmp_skin_buttmisc"; x = 269; y = 239; w = 72; h = 72; dest_w = 64; dest_h = 64 };
    { tag = "img_redglow_05"; sheet = "bmp_skin_buttmisc"; x = 271; y = 241; w = 68; h = 68; dest_w = 64; dest_h = 64 };
    { tag = "img_redglow_06"; sheet = "bmp_skin_buttmisc"; x = 273; y = 243; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_tabbar"; sheet = "bmp_skin_dlgchar"; x = 0; y = 465; w = 440; h = 47; dest_w = 440; dest_h = 47 };
    { tag = "img_tabbar_00"; sheet = "bmp_skin_dlgchar"; x = 0; y = 414; w = 48; h = 47; dest_w = 48; dest_h = 47 };
    { tag = "img_tabbar_01"; sheet = "bmp_skin_dlgchar"; x = 49; y = 414; w = 48; h = 47; dest_w = 48; dest_h = 47 };
    { tag = "img_tabbar_02"; sheet = "bmp_skin_dlgchar"; x = 98; y = 414; w = 48; h = 47; dest_w = 48; dest_h = 47 };
    { tag = "img_tabbar_03"; sheet = "bmp_skin_dlgchar"; x = 147; y = 414; w = 48; h = 47; dest_w = 48; dest_h = 47 };
    { tag = "img_tabbar_04"; sheet = "bmp_skin_dlgchar"; x = 196; y = 414; w = 48; h = 47; dest_w = 48; dest_h = 47 };
    { tag = "img_tabbar_05"; sheet = "bmp_skin_dlgchar"; x = 245; y = 414; w = 48; h = 47; dest_w = 48; dest_h = 47 };
    { tag = "img_tabbar_06"; sheet = "bmp_skin_dlgchar"; x = 294; y = 414; w = 48; h = 47; dest_w = 48; dest_h = 47 };
    { tag = "img_tabbar_07"; sheet = "bmp_skin_dlgchar"; x = 343; y = 414; w = 48; h = 47; dest_w = 48; dest_h = 47 };
    { tag = "img_tabbar_08"; sheet = "bmp_skin_dlgchar"; x = 392; y = 414; w = 48; h = 47; dest_w = 48; dest_h = 47 };
    { tag = "img_tabbar_hi"; sheet = "bmp_skin_dlgchar"; x = 456; y = 456; w = 56; h = 56; dest_w = 56; dest_h = 56 };
    { tag = "img_buttctr_act"; sheet = "bmp_skin_dlgchar"; x = 0; y = 302; w = 45; h = 45; dest_w = 45; dest_h = 45 };
    { tag = "img_buttctr_hi"; sheet = "bmp_skin_dlgchar"; x = 46; y = 302; w = 45; h = 45; dest_w = 45; dest_h = 45 };
    { tag = "img_buttctr_pres"; sheet = "bmp_skin_dlgchar"; x = 0; y = 348; w = 45; h = 45; dest_w = 45; dest_h = 45 };
    { tag = "img_buttctr_gray"; sheet = "bmp_skin_dlgchar"; x = 46; y = 348; w = 45; h = 45; dest_w = 45; dest_h = 45 };
    { tag = "img_darkpopup"; sheet = "bmp_skin_dlgmain"; x = 0; y = 261; w = 300; h = 125; dest_w = 448; dest_h = 125 };
    { tag = "img_darkpopup0"; sheet = "bmp_skin_dlgmain"; x = 0; y = 261; w = 100; h = 125; dest_w = 100; dest_h = 125 };
    { tag = "img_darkpopup1"; sheet = "bmp_skin_dlgmain"; x = 100; y = 261; w = 100; h = 125; dest_w = 100; dest_h = 125 };
    { tag = "img_darkpopup2"; sheet = "bmp_skin_dlgmain"; x = 200; y = 261; w = 100; h = 125; dest_w = 100; dest_h = 125 };
    { tag = "img_mapcharpopup"; sheet = "bmp_skin_dlgmain"; x = 0; y = 387; w = 300; h = 125; dest_w = 300; dest_h = 125 };
    { tag = "img_xbl_logo"; sheet = "bmp_skin_dlgmain"; x = 335; y = 413; w = 177; h = 38; dest_w = 177; dest_h = 38 };
    { tag = "img_xbl_mp_frame"; sheet = "bmp_skin_xbla_mp"; x = 0; y = 0; w = 622; h = 335; dest_w = 622; dest_h = 335 };
    { tag = "img_xbl_list_frame_top"; sheet = "bmp_skin_xbla_mp"; x = 0; y = 336; w = 580; h = 49; dest_w = 580; dest_h = 49 };
    { tag = "img_xbl_list_frame_off"; sheet = "bmp_skin_xbla_mp"; x = 0; y = 385; w = 580; h = 36; dest_w = 580; dest_h = 36 };
    { tag = "img_xbl_list_frame_lo"; sheet = "bmp_skin_xbla_mp"; x = 0; y = 421; w = 580; h = 36; dest_w = 580; dest_h = 36 };
    { tag = "img_xbl_list_frame_hi"; sheet = "bmp_skin_xbla_mp"; x = 0; y = 457; w = 580; h = 36; dest_w = 580; dest_h = 36 };
    { tag = "img_xbl_list_frame_bot"; sheet = "bmp_skin_xbla_mp"; x = 0; y = 493; w = 580; h = 9; dest_w = 580; dest_h = 9 };
    { tag = "img_xbl_list_lvlt"; sheet = "bmp_skin_xbla_mp"; x = 623; y = 0; w = 64; h = 32; dest_w = 64; dest_h = 32 };
    { tag = "img_xbl_list_lvl5"; sheet = "bmp_skin_xbla_mp"; x = 623; y = 32; w = 64; h = 32; dest_w = 64; dest_h = 32 };
    { tag = "img_xbl_list_lvl10"; sheet = "bmp_skin_xbla_mp"; x = 623; y = 64; w = 64; h = 32; dest_w = 64; dest_h = 32 };
    { tag = "img_xbl_list_lvl20"; sheet = "bmp_skin_xbla_mp"; x = 623; y = 96; w = 64; h = 32; dest_w = 64; dest_h = 32 };
    { tag = "img_xbl_list_lvl30"; sheet = "bmp_skin_xbla_mp"; x = 623; y = 128; w = 64; h = 32; dest_w = 64; dest_h = 32 };
    { tag = "img_xbl_list_lvl40"; sheet = "bmp_skin_xbla_mp"; x = 623; y = 160; w = 64; h = 32; dest_w = 64; dest_h = 32 };
    { tag = "img_xbl_list_lvl50"; sheet = "bmp_skin_xbla_mp"; x = 623; y = 192; w = 64; h = 32; dest_w = 64; dest_h = 32 };
    { tag = "img_xbl_list_h_t"; sheet = "bmp_skin_xbla_mp"; x = 687; y = 0; w = 40; h = 32; dest_w = 40; dest_h = 32 };
    { tag = "img_xbl_list_h_on"; sheet = "bmp_skin_xbla_mp"; x = 687; y = 32; w = 40; h = 32; dest_w = 40; dest_h = 32 };
    { tag = "img_xbl_list_h_off"; sheet = "bmp_skin_xbla_mp"; x = 687; y = 64; w = 40; h = 32; dest_w = 40; dest_h = 32 };
    { tag = "img_xbl_list_tmt"; sheet = "bmp_skin_xbla_mp"; x = 727; y = 0; w = 40; h = 32; dest_w = 40; dest_h = 32 };
    { tag = "img_xbl_list_tm4"; sheet = "bmp_skin_xbla_mp"; x = 727; y = 32; w = 40; h = 32; dest_w = 40; dest_h = 32 };
    { tag = "img_xbl_list_tm8"; sheet = "bmp_skin_xbla_mp"; x = 727; y = 64; w = 40; h = 32; dest_w = 40; dest_h = 32 };
    { tag = "img_xbl_list_tm12"; sheet = "bmp_skin_xbla_mp"; x = 727; y = 96; w = 40; h = 32; dest_w = 40; dest_h = 32 };
    { tag = "img_xbl_list_tm16"; sheet = "bmp_skin_xbla_mp"; x = 727; y = 128; w = 40; h = 32; dest_w = 40; dest_h = 32 };
    { tag = "img_xbl_list_tm0"; sheet = "bmp_skin_xbla_mp"; x = 727; y = 160; w = 40; h = 32; dest_w = 40; dest_h = 32 };
    { tag = "img_xbl_long_hilite"; sheet = "bmp_skin_xbla_mp"; x = 8; y = 457; w = 565; h = 36; dest_w = 565; dest_h = 36 };
    { tag = "img_hint_00"; sheet = "bmp_skin_gemsgrid"; x = 101; y = 477; w = 55; h = 35; dest_w = 55; dest_h = 35 };
    { tag = "img_hint_01"; sheet = "bmp_skin_gemsgrid"; x = 157; y = 477; w = 55; h = 35; dest_w = 55; dest_h = 35 };
    { tag = "img_hint_02"; sheet = "bmp_skin_gemsgrid"; x = 213; y = 477; w = 55; h = 35; dest_w = 55; dest_h = 35 };
    { tag = "img_hint_03"; sheet = "bmp_skin_gemsgrid"; x = 269; y = 477; w = 55; h = 35; dest_w = 55; dest_h = 35 };
    { tag = "img_ltimebg"; sheet = "bmp_skin_gemsgrid"; x = 331; y = 422; w = 90; h = 90; dest_w = 90; dest_h = 90 };
    { tag = "img_rtimebg"; sheet = "bmp_skin_gemsgrid"; x = 422; y = 422; w = 90; h = 90; dest_w = 90; dest_h = 90 };
    { tag = "img_victory_gold"; sheet = "bmp_skin_dlgchar"; x = 469; y = 218; w = 24; h = 24; dest_w = 24; dest_h = 24 };
    { tag = "img_victory_xp"; sheet = "bmp_skin_dlgchar"; x = 469; y = 243; w = 24; h = 24; dest_w = 24; dest_h = 24 };
    { tag = "img_maincursor"; sheet = "bmp_maincursor"; x = 0; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_listbox"; sheet = "bmp_listbox"; x = 0; y = 0; w = 256; h = 200; dest_w = 256; dest_h = 200 };
    { tag = "img_quest"; sheet = "bmp_quest"; x = 0; y = 0; w = 128; h = 160; dest_w = 128; dest_h = 160 };
    { tag = "img_backdrop"; sheet = "bmp_skin_backdrop"; x = 0; y = 0; w = 1024; h = 768; dest_w = 1024; dest_h = 768 };
    { tag = "img_toppanel"; sheet = "bmp_skin_backdrop"; x = 0; y = 0; w = 1024; h = 95; dest_w = 1024; dest_h = 95 };
    { tag = "img_black"; sheet = "bmp_skin_backdrop"; x = 0; y = 768; w = 50; h = 50; dest_w = 50; dest_h = 50 };
    { tag = "img_buttwide_act"; sheet = "bmp_skin_buttmain"; x = 0; y = 0; w = 300; h = 50; dest_w = 300; dest_h = 50 };
    { tag = "img_buttwide_hi0"; sheet = "bmp_skin_buttmain"; x = 0; y = 51; w = 300; h = 50; dest_w = 300; dest_h = 50 };
    { tag = "img_buttwide_hi1"; sheet = "bmp_skin_buttmain"; x = 0; y = 102; w = 300; h = 50; dest_w = 300; dest_h = 50 };
    { tag = "img_buttwide_hi2"; sheet = "bmp_skin_buttmain"; x = 0; y = 153; w = 300; h = 50; dest_w = 300; dest_h = 50 };
    { tag = "img_buttwide_hi3"; sheet = "bmp_skin_buttmain"; x = 0; y = 204; w = 300; h = 50; dest_w = 300; dest_h = 50 };
    { tag = "img_buttwide_pres"; sheet = "bmp_skin_buttmain"; x = 0; y = 255; w = 300; h = 50; dest_w = 300; dest_h = 50 };
    { tag = "img_buttwide_gray"; sheet = "bmp_skin_buttmain"; x = 0; y = 306; w = 300; h = 50; dest_w = 300; dest_h = 50 };
    { tag = "img_buttsmall_act"; sheet = "bmp_skin_buttmain"; x = 301; y = 0; w = 160; h = 50; dest_w = 160; dest_h = 50 };
    { tag = "img_buttsmall_hi0"; sheet = "bmp_skin_buttmain"; x = 301; y = 51; w = 160; h = 50; dest_w = 160; dest_h = 50 };
    { tag = "img_buttsmall_hi1"; sheet = "bmp_skin_buttmain"; x = 301; y = 102; w = 160; h = 50; dest_w = 160; dest_h = 50 };
    { tag = "img_buttsmall_hi2"; sheet = "bmp_skin_buttmain"; x = 301; y = 153; w = 160; h = 50; dest_w = 160; dest_h = 50 };
    { tag = "img_buttsmall_hi3"; sheet = "bmp_skin_buttmain"; x = 301; y = 204; w = 160; h = 50; dest_w = 160; dest_h = 50 };
    { tag = "img_buttsmall_pres"; sheet = "bmp_skin_buttmain"; x = 301; y = 255; w = 160; h = 50; dest_w = 160; dest_h = 50 };
    { tag = "img_buttsmall_gray"; sheet = "bmp_skin_buttmain"; x = 301; y = 306; w = 160; h = 50; dest_w = 160; dest_h = 50 };
    { tag = "img_buttplus_act"; sheet = "bmp_skin_buttmisc"; x = 327; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttplus_hi0"; sheet = "bmp_skin_buttmisc"; x = 327; y = 33; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttplus_hi1"; sheet = "bmp_skin_buttmisc"; x = 327; y = 66; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttplus_hi2"; sheet = "bmp_skin_buttmisc"; x = 327; y = 99; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttplus_hi3"; sheet = "bmp_skin_buttmisc"; x = 327; y = 132; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttplus_pres"; sheet = "bmp_skin_buttmisc"; x = 327; y = 165; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttplus_gray"; sheet = "bmp_skin_buttmisc"; x = 327; y = 198; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttminus_act"; sheet = "bmp_skin_buttmisc"; x = 360; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttminus_hi0"; sheet = "bmp_skin_buttmisc"; x = 360; y = 33; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttminus_hi1"; sheet = "bmp_skin_buttmisc"; x = 360; y = 66; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttminus_hi2"; sheet = "bmp_skin_buttmisc"; x = 360; y = 99; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttminus_hi3"; sheet = "bmp_skin_buttmisc"; x = 360; y = 132; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttminus_pres"; sheet = "bmp_skin_buttmisc"; x = 360; y = 165; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttminus_gray"; sheet = "bmp_skin_buttmisc"; x = 360; y = 198; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttoff_act"; sheet = "bmp_skin_buttmisc"; x = 393; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttoff_hi0"; sheet = "bmp_skin_buttmisc"; x = 393; y = 33; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttoff_hi1"; sheet = "bmp_skin_buttmisc"; x = 393; y = 66; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttoff_hi2"; sheet = "bmp_skin_buttmisc"; x = 393; y = 99; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttoff_hi3"; sheet = "bmp_skin_buttmisc"; x = 393; y = 132; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttoff_pres"; sheet = "bmp_skin_buttmisc"; x = 393; y = 165; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttoff_gray"; sheet = "bmp_skin_buttmisc"; x = 393; y = 198; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_button_act"; sheet = "bmp_skin_buttmisc"; x = 426; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_button_hi0"; sheet = "bmp_skin_buttmisc"; x = 426; y = 33; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_button_hi1"; sheet = "bmp_skin_buttmisc"; x = 426; y = 66; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_button_hi2"; sheet = "bmp_skin_buttmisc"; x = 426; y = 99; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_button_hi3"; sheet = "bmp_skin_buttmisc"; x = 426; y = 132; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_button_pres"; sheet = "bmp_skin_buttmisc"; x = 426; y = 165; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_button_gray"; sheet = "bmp_skin_buttmisc"; x = 426; y = 198; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttbang_act"; sheet = "bmp_skin_buttmisc"; x = 261; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttbang_hi0"; sheet = "bmp_skin_buttmisc"; x = 261; y = 33; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttbang_hi1"; sheet = "bmp_skin_buttmisc"; x = 261; y = 66; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttbang_hi2"; sheet = "bmp_skin_buttmisc"; x = 261; y = 99; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttbang_hi3"; sheet = "bmp_skin_buttmisc"; x = 261; y = 132; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttbang_pres"; sheet = "bmp_skin_buttmisc"; x = 261; y = 165; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttbang_gray"; sheet = "bmp_skin_buttmisc"; x = 261; y = 198; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_butttiny_act"; sheet = "bmp_skin_buttmain"; x = 0; y = 357; w = 128; h = 35; dest_w = 130; dest_h = 40 };
    { tag = "img_butttiny_hi0"; sheet = "bmp_skin_buttmain"; x = 0; y = 393; w = 128; h = 35; dest_w = 130; dest_h = 40 };
    { tag = "img_butttiny_hi1"; sheet = "bmp_skin_buttmain"; x = 0; y = 429; w = 128; h = 35; dest_w = 130; dest_h = 40 };
    { tag = "img_butttiny_hi2"; sheet = "bmp_skin_buttmain"; x = 0; y = 465; w = 128; h = 35; dest_w = 130; dest_h = 40 };
    { tag = "img_butttiny_hi3"; sheet = "bmp_skin_buttmain"; x = 129; y = 357; w = 128; h = 35; dest_w = 130; dest_h = 40 };
    { tag = "img_butttiny_pres"; sheet = "bmp_skin_buttmain"; x = 129; y = 393; w = 128; h = 35; dest_w = 130; dest_h = 40 };
    { tag = "img_butttiny_gray"; sheet = "bmp_skin_buttmain"; x = 129; y = 429; w = 128; h = 35; dest_w = 130; dest_h = 40 };
    { tag = "img_buttbuy_act"; sheet = "bmp_skin_buttmisc"; x = 294; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttbuy_hi0"; sheet = "bmp_skin_buttmisc"; x = 294; y = 33; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttbuy_hi1"; sheet = "bmp_skin_buttmisc"; x = 294; y = 66; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttbuy_hi2"; sheet = "bmp_skin_buttmisc"; x = 294; y = 99; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttbuy_hi3"; sheet = "bmp_skin_buttmisc"; x = 294; y = 132; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttbuy_pres"; sheet = "bmp_skin_buttmisc"; x = 294; y = 165; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttbuy_gray"; sheet = "bmp_skin_buttmisc"; x = 294; y = 198; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttclose_act"; sheet = "bmp_skin_buttmain"; x = 258; y = 357; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_buttclose_hi"; sheet = "bmp_skin_buttmain"; x = 278; y = 357; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_buttclose_pres"; sheet = "bmp_skin_buttmain"; x = 258; y = 377; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_buttclose_gray"; sheet = "bmp_skin_buttmain"; x = 278; y = 377; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_buttmini_act"; sheet = "bmp_skin_buttmain"; x = 299; y = 357; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_buttmini_hi"; sheet = "bmp_skin_buttmain"; x = 319; y = 357; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_buttmini_pres"; sheet = "bmp_skin_buttmain"; x = 299; y = 377; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_buttmini_gray"; sheet = "bmp_skin_buttmain"; x = 319; y = 377; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_butthelp_act"; sheet = "bmp_skin_buttmain"; x = 340; y = 357; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_butthelp_hi"; sheet = "bmp_skin_buttmain"; x = 360; y = 357; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_butthelp_pres"; sheet = "bmp_skin_buttmain"; x = 340; y = 377; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_butthelp_gray"; sheet = "bmp_skin_buttmain"; x = 360; y = 377; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_buttleft_act"; sheet = "bmp_skin_buttmisc"; x = 0; y = 424; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttleft_hi0"; sheet = "bmp_skin_buttmisc"; x = 33; y = 424; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttleft_hi1"; sheet = "bmp_skin_buttmisc"; x = 66; y = 424; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttleft_hi2"; sheet = "bmp_skin_buttmisc"; x = 99; y = 424; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttleft_hi3"; sheet = "bmp_skin_buttmisc"; x = 132; y = 424; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttleft_pres"; sheet = "bmp_skin_buttmisc"; x = 165; y = 424; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttleft_gray"; sheet = "bmp_skin_buttmisc"; x = 198; y = 424; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttright_act"; sheet = "bmp_skin_buttmisc"; x = 0; y = 457; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttright_hi0"; sheet = "bmp_skin_buttmisc"; x = 33; y = 457; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttright_hi1"; sheet = "bmp_skin_buttmisc"; x = 66; y = 457; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttright_hi2"; sheet = "bmp_skin_buttmisc"; x = 99; y = 457; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttright_hi3"; sheet = "bmp_skin_buttmisc"; x = 132; y = 457; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttright_pres"; sheet = "bmp_skin_buttmisc"; x = 165; y = 457; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_buttright_gray"; sheet = "bmp_skin_buttmisc"; x = 198; y = 457; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_darken"; sheet = "bmp_skin_dlgmain"; x = 0; y = 224; w = 50; h = 20; dest_w = 50; dest_h = 20 };
    { tag = "img_vsbar_bg"; sheet = "bmp_skin_buttmain"; x = 462; y = 252; w = 32; h = 170; dest_w = 32; dest_h = 170 };
    { tag = "img_vsbar_decgray"; sheet = "bmp_skin_buttmain"; x = 396; y = 357; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_vsbar_decup"; sheet = "bmp_skin_buttmain"; x = 396; y = 390; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_vsbar_decdown"; sheet = "bmp_skin_buttmain"; x = 396; y = 423; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_vsbar_incgray"; sheet = "bmp_skin_buttmain"; x = 429; y = 357; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_vsbar_incup"; sheet = "bmp_skin_buttmain"; x = 429; y = 390; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_vsbar_incdown"; sheet = "bmp_skin_buttmain"; x = 429; y = 423; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_vsbar_thumb"; sheet = "bmp_skin_buttmain"; x = 462; y = 423; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_charsheet_sp"; sheet = "bmp_skin_dlgchar"; x = 0; y = 0; w = 273; h = 301; dest_w = 273; dest_h = 301 };
    { tag = "img_charsheet_mp"; sheet = "bmp_skin_dlgchar"; x = 276; y = 0; w = 236; h = 192; dest_w = 236; dest_h = 192 };
    { tag = "img_charsheet_mp0"; sheet = "bmp_skin_dlgchar"; x = 276; y = 0; w = 160; h = 192; dest_w = 160; dest_h = 192 };
    { tag = "img_charsheet_mp1"; sheet = "bmp_skin_dlgchar"; x = 436; y = 0; w = 40; h = 192; dest_w = 40; dest_h = 192 };
    { tag = "img_charsheet_mp2"; sheet = "bmp_skin_dlgchar"; x = 476; y = 0; w = 36; h = 192; dest_w = 36; dest_h = 192 };
    { tag = "img_dlg"; sheet = "bmp_skin_dlgmain"; x = 320; y = 0; w = 192; h = 192; dest_w = 192; dest_h = 192 };
    { tag = "img_dlg_0"; sheet = "bmp_skin_dlgmain"; x = 320; y = 0; w = 192; h = 64; dest_w = 192; dest_h = 64 };
    { tag = "img_dlg_00"; sheet = "bmp_skin_dlgmain"; x = 320; y = 0; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_dlg_01"; sheet = "bmp_skin_dlgmain"; x = 384; y = 0; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_dlg_02"; sheet = "bmp_skin_dlgmain"; x = 448; y = 0; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_dlg_1"; sheet = "bmp_skin_dlgmain"; x = 320; y = 64; w = 192; h = 64; dest_w = 192; dest_h = 64 };
    { tag = "img_dlg_10"; sheet = "bmp_skin_dlgmain"; x = 320; y = 64; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_dlg_11"; sheet = "bmp_skin_dlgmain"; x = 384; y = 64; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_dlg_12"; sheet = "bmp_skin_dlgmain"; x = 448; y = 64; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_dlg_2"; sheet = "bmp_skin_dlgmain"; x = 320; y = 128; w = 192; h = 64; dest_w = 192; dest_h = 64 };
    { tag = "img_dlg_20"; sheet = "bmp_skin_dlgmain"; x = 320; y = 128; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_dlg_21"; sheet = "bmp_skin_dlgmain"; x = 384; y = 128; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_dlg_22"; sheet = "bmp_skin_dlgmain"; x = 448; y = 128; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_frm"; sheet = "bmp_skin_dlgmain"; x = 320; y = 193; w = 192; h = 192; dest_w = 192; dest_h = 192 };
    { tag = "img_frm_0"; sheet = "bmp_skin_dlgmain"; x = 320; y = 193; w = 192; h = 64; dest_w = 192; dest_h = 64 };
    { tag = "img_frm_00"; sheet = "bmp_skin_dlgmain"; x = 320; y = 193; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_frm_01"; sheet = "bmp_skin_dlgmain"; x = 384; y = 193; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_frm_02"; sheet = "bmp_skin_dlgmain"; x = 448; y = 193; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_frm_1"; sheet = "bmp_skin_dlgmain"; x = 320; y = 257; w = 192; h = 64; dest_w = 192; dest_h = 64 };
    { tag = "img_frm_10"; sheet = "bmp_skin_dlgmain"; x = 320; y = 257; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_frm_11"; sheet = "bmp_skin_dlgmain"; x = 384; y = 257; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_frm_12"; sheet = "bmp_skin_dlgmain"; x = 448; y = 257; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_frm_2"; sheet = "bmp_skin_dlgmain"; x = 320; y = 321; w = 192; h = 64; dest_w = 192; dest_h = 64 };
    { tag = "img_frm_20"; sheet = "bmp_skin_dlgmain"; x = 320; y = 321; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_frm_21"; sheet = "bmp_skin_dlgmain"; x = 384; y = 321; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_frm_22"; sheet = "bmp_skin_dlgmain"; x = 448; y = 321; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_lbx_0"; sheet = "bmp_skin_dlgmain"; x = 312; y = 452; w = 200; h = 10; dest_w = 200; dest_h = 10 };
    { tag = "img_lbx_00"; sheet = "bmp_skin_dlgmain"; x = 312; y = 452; w = 50; h = 10; dest_w = 50; dest_h = 10 };
    { tag = "img_lbx_01"; sheet = "bmp_skin_dlgmain"; x = 362; y = 452; w = 100; h = 10; dest_w = 100; dest_h = 10 };
    { tag = "img_lbx_01a"; sheet = "bmp_skin_dlgmain"; x = 362; y = 452; w = 50; h = 10; dest_w = 50; dest_h = 10 };
    { tag = "img_lbx_02"; sheet = "bmp_skin_dlgmain"; x = 462; y = 452; w = 50; h = 10; dest_w = 50; dest_h = 10 };
    { tag = "img_lbx_1"; sheet = "bmp_skin_dlgmain"; x = 312; y = 462; w = 200; h = 20; dest_w = 200; dest_h = 20 };
    { tag = "img_lbx_10"; sheet = "bmp_skin_dlgmain"; x = 312; y = 462; w = 50; h = 20; dest_w = 50; dest_h = 20 };
    { tag = "img_lbx_11"; sheet = "bmp_skin_dlgmain"; x = 362; y = 462; w = 100; h = 20; dest_w = 100; dest_h = 20 };
    { tag = "img_lbx_11a"; sheet = "bmp_skin_dlgmain"; x = 362; y = 462; w = 50; h = 20; dest_w = 50; dest_h = 20 };
    { tag = "img_lbx_12"; sheet = "bmp_skin_dlgmain"; x = 462; y = 462; w = 50; h = 20; dest_w = 50; dest_h = 20 };
    { tag = "img_lbx_2"; sheet = "bmp_skin_dlgmain"; x = 312; y = 502; w = 200; h = 10; dest_w = 200; dest_h = 10 };
    { tag = "img_lbx_20"; sheet = "bmp_skin_dlgmain"; x = 312; y = 502; w = 50; h = 10; dest_w = 50; dest_h = 10 };
    { tag = "img_lbx_21"; sheet = "bmp_skin_dlgmain"; x = 362; y = 502; w = 100; h = 10; dest_w = 100; dest_h = 10 };
    { tag = "img_lbx_21a"; sheet = "bmp_skin_dlgmain"; x = 362; y = 502; w = 50; h = 10; dest_w = 50; dest_h = 10 };
    { tag = "img_lbx_22"; sheet = "bmp_skin_dlgmain"; x = 462; y = 502; w = 50; h = 10; dest_w = 50; dest_h = 10 };
    { tag = "img_editor"; sheet = "bmp_skin_buttmain"; x = 162; y = 465; w = 300; h = 32; dest_w = 300; dest_h = 32 };
    { tag = "img_editor_caret1"; sheet = "bmp_skin_buttmain"; x = 129; y = 465; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_editor_caret2"; sheet = "bmp_skin_buttmain"; x = 342; y = 460; w = 4; h = 4; dest_w = 32; dest_h = 32 };
    { tag = "img_editor_blink"; sheet = "bmp_skin_buttmain"; x = 463; y = 465; w = 16; h = 32; dest_w = 16; dest_h = 32 };
    { tag = "img_blank"; sheet = "bmp_skin_buttmain"; x = 342; y = 460; w = 4; h = 4; dest_w = 16; dest_h = 16 };
    { tag = "img_drop_act"; sheet = "bmp_skin_buttmisc"; x = 0; y = 0; w = 260; h = 50; dest_w = 260; dest_h = 50 };
    { tag = "img_drop_hi0"; sheet = "bmp_skin_buttmisc"; x = 0; y = 51; w = 260; h = 50; dest_w = 260; dest_h = 50 };
    { tag = "img_drop_hi1"; sheet = "bmp_skin_buttmisc"; x = 0; y = 102; w = 260; h = 50; dest_w = 260; dest_h = 50 };
    { tag = "img_drop_hi2"; sheet = "bmp_skin_buttmisc"; x = 0; y = 153; w = 260; h = 50; dest_w = 260; dest_h = 50 };
    { tag = "img_drop_hi3"; sheet = "bmp_skin_buttmisc"; x = 0; y = 204; w = 260; h = 50; dest_w = 260; dest_h = 50 };
    { tag = "img_drop_pres"; sheet = "bmp_skin_buttmisc"; x = 0; y = 255; w = 260; h = 50; dest_w = 260; dest_h = 50 };
    { tag = "img_drop_gray"; sheet = "bmp_skin_buttmisc"; x = 0; y = 306; w = 260; h = 50; dest_w = 260; dest_h = 50 };
    { tag = "img_drop_dtop"; sheet = "bmp_skin_buttmisc"; x = 0; y = 357; w = 250; h = 13; dest_w = 250; dest_h = 13 };
    { tag = "img_drop_dctr"; sheet = "bmp_skin_buttmisc"; x = 0; y = 370; w = 250; h = 20; dest_w = 250; dest_h = 20 };
    { tag = "img_drop_dctrhi"; sheet = "bmp_skin_buttmisc"; x = 0; y = 390; w = 250; h = 20; dest_w = 250; dest_h = 20 };
    { tag = "img_drop_dbot"; sheet = "bmp_skin_buttmisc"; x = 0; y = 410; w = 250; h = 13; dest_w = 250; dest_h = 13 };
    { tag = "img_qbutt0_act"; sheet = "bmp_skin_buttmain"; x = 462; y = 0; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_qbutt0_hi"; sheet = "bmp_skin_buttmain"; x = 462; y = 21; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_qbutt0_pres"; sheet = "bmp_skin_buttmain"; x = 462; y = 42; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_qbutt0_gray"; sheet = "bmp_skin_buttmain"; x = 462; y = 63; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_qbutt1_act"; sheet = "bmp_skin_buttmain"; x = 462; y = 84; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_qbutt1_hi"; sheet = "bmp_skin_buttmain"; x = 462; y = 105; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_qbutt1_pres"; sheet = "bmp_skin_buttmain"; x = 462; y = 126; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_qbutt1_gray"; sheet = "bmp_skin_buttmain"; x = 462; y = 147; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_qbutt2_act"; sheet = "bmp_skin_buttmain"; x = 462; y = 168; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_qbutt2_hi"; sheet = "bmp_skin_buttmain"; x = 462; y = 189; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_qbutt2_pres"; sheet = "bmp_skin_buttmain"; x = 462; y = 210; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_qbutt2_gray"; sheet = "bmp_skin_buttmain"; x = 462; y = 231; w = 20; h = 20; dest_w = 20; dest_h = 20 };
    { tag = "img_listportraits"; sheet = "bmp_listportraits"; x = 0; y = 0; w = 256; h = 256; dest_w = 128; dest_h = 128 };
    { tag = "img_listportraits2"; sheet = "bmp_enemyportrait"; x = 0; y = 0; w = 256; h = 256; dest_w = 128; dest_h = 128 };
    { tag = "img_shieldgrn_0"; sheet = "bmp_skin_battlemisc"; x = 173; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_shieldgrn_1"; sheet = "bmp_skin_battlemisc"; x = 206; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_shieldgrn_2"; sheet = "bmp_skin_battlemisc"; x = 239; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_shieldgrn_3"; sheet = "bmp_skin_battlemisc"; x = 272; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_shieldgrn_4"; sheet = "bmp_skin_battlemisc"; x = 305; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_shieldgrn_5"; sheet = "bmp_skin_battlemisc"; x = 338; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_shieldgrn_6"; sheet = "bmp_skin_battlemisc"; x = 371; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_shieldgrn_7"; sheet = "bmp_skin_battlemisc"; x = 404; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_shieldgrn_8"; sheet = "bmp_skin_battlemisc"; x = 437; y = 0; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_shieldred_0"; sheet = "bmp_skin_battlemisc"; x = 173; y = 33; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_shieldred_1"; sheet = "bmp_skin_battlemisc"; x = 206; y = 33; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_shieldred_2"; sheet = "bmp_skin_battlemisc"; x = 239; y = 33; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_shieldred_3"; sheet = "bmp_skin_battlemisc"; x = 272; y = 33; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_shieldred_4"; sheet = "bmp_skin_battlemisc"; x = 305; y = 33; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_shieldred_5"; sheet = "bmp_skin_battlemisc"; x = 338; y = 33; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_shieldred_6"; sheet = "bmp_skin_battlemisc"; x = 371; y = 33; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_shieldred_7"; sheet = "bmp_skin_battlemisc"; x = 404; y = 33; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_shieldred_8"; sheet = "bmp_skin_battlemisc"; x = 437; y = 33; w = 32; h = 32; dest_w = 32; dest_h = 32 };
    { tag = "img_timer_0"; sheet = "bmp_skin_battlemisc"; x = 201; y = 206; w = 50; h = 50; dest_w = 50; dest_h = 50 };
    { tag = "img_timer_1"; sheet = "bmp_skin_battlemisc"; x = 252; y = 206; w = 50; h = 50; dest_w = 50; dest_h = 50 };
    { tag = "img_timer_2"; sheet = "bmp_skin_battlemisc"; x = 303; y = 206; w = 50; h = 50; dest_w = 50; dest_h = 50 };
    { tag = "img_timer_3"; sheet = "bmp_skin_battlemisc"; x = 354; y = 206; w = 50; h = 50; dest_w = 50; dest_h = 50 };
    { tag = "img_timer_4"; sheet = "bmp_skin_battlemisc"; x = 405; y = 206; w = 50; h = 50; dest_w = 50; dest_h = 50 };
    { tag = "img_timer_5"; sheet = "bmp_skin_battlemisc"; x = 456; y = 206; w = 50; h = 50; dest_w = 50; dest_h = 50 };
    { tag = "img_shieldglow_0"; sheet = "bmp_skin_gemsgrid"; x = 216; y = 216; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_shieldglow_1"; sheet = "bmp_skin_gemsgrid"; x = 281; y = 216; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_shieldglow_2"; sheet = "bmp_skin_gemsgrid"; x = 346; y = 216; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_shieldglow_3"; sheet = "bmp_skin_gemsgrid"; x = 411; y = 216; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_missturn_1"; sheet = "bmp_skin_battlemisc"; x = 0; y = 74; w = 90; h = 24; dest_w = 90; dest_h = 24 };
    { tag = "img_missturn_2"; sheet = "bmp_skin_battlemisc"; x = 0; y = 99; w = 90; h = 24; dest_w = 90; dest_h = 24 };
    { tag = "img_missturn_3"; sheet = "bmp_skin_battlemisc"; x = 0; y = 124; w = 90; h = 24; dest_w = 90; dest_h = 24 };
    { tag = "img_missturn_4"; sheet = "bmp_skin_battlemisc"; x = 0; y = 149; w = 90; h = 24; dest_w = 90; dest_h = 24 };
    { tag = "img_missturn_5"; sheet = "bmp_skin_battlemisc"; x = 0; y = 174; w = 90; h = 24; dest_w = 90; dest_h = 24 };
    { tag = "img_gem_green"; sheet = "bmp_skin_gemsgrid"; x = 0; y = 0; w = 71; h = 71; dest_w = 71; dest_h = 71 };
    { tag = "img_gem_red"; sheet = "bmp_skin_gemsgrid"; x = 72; y = 0; w = 71; h = 71; dest_w = 71; dest_h = 71 };
    { tag = "img_gem_yellow"; sheet = "bmp_skin_gemsgrid"; x = 144; y = 0; w = 71; h = 71; dest_w = 71; dest_h = 71 };
    { tag = "img_gem_blue"; sheet = "bmp_skin_gemsgrid"; x = 216; y = 0; w = 71; h = 71; dest_w = 71; dest_h = 71 };
    { tag = "img_gem_scroll"; sheet = "bmp_skin_gemsgrid"; x = 72; y = 216; w = 71; h = 71; dest_w = 71; dest_h = 71 };
    { tag = "img_hammanv_on"; sheet = "bmp_skin_gemsgrid"; x = 175; y = 389; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_hammanv_off"; sheet = "bmp_skin_gemsgrid"; x = 240; y = 389; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_gamepad_a"; sheet = "bmp_skin_gamepad"; x = 0; y = 51; w = 40; h = 40; dest_w = 40; dest_h = 40 };
    { tag = "img_gamepad_b"; sheet = "bmp_skin_gamepad"; x = 41; y = 51; w = 40; h = 40; dest_w = 40; dest_h = 40 };
    { tag = "img_gamepad_x"; sheet = "bmp_skin_gamepad"; x = 82; y = 51; w = 40; h = 40; dest_w = 40; dest_h = 40 };
    { tag = "img_gamepad_y"; sheet = "bmp_skin_gamepad"; x = 123; y = 51; w = 40; h = 40; dest_w = 40; dest_h = 40 };
    { tag = "img_gamepad_l"; sheet = "bmp_skin_gamepad"; x = 102; y = 92; w = 62; h = 28; dest_w = 62; dest_h = 28 };
    { tag = "img_gamepad_r"; sheet = "bmp_skin_gamepad"; x = 165; y = 92; w = 62; h = 28; dest_w = 62; dest_h = 28 };
    { tag = "img_gamepad_lt"; sheet = "bmp_skin_gamepad"; x = 261; y = 140; w = 57; h = 51; dest_w = 57; dest_h = 51 };
    { tag = "img_gamepad_rt"; sheet = "bmp_skin_gamepad"; x = 319; y = 140; w = 57; h = 51; dest_w = 57; dest_h = 51 };
    { tag = "img_gamepad_back"; sheet = "bmp_skin_gamepad"; x = 51; y = 92; w = 50; h = 40; dest_w = 50; dest_h = 40 };
    { tag = "img_gamepad_start"; sheet = "bmp_skin_gamepad"; x = 0; y = 92; w = 50; h = 40; dest_w = 50; dest_h = 40 };
    { tag = "img_gamepad_buttact"; sheet = "bmp_skin_gamepad"; x = 0; y = 0; w = 260; h = 50; dest_w = 260; dest_h = 50 };
    { tag = "img_gamepad_buttgray"; sheet = "bmp_skin_gamepad"; x = 0; y = 133; w = 260; h = 50; dest_w = 260; dest_h = 50 };
    { tag = "img_gamepad_dpad_ud"; sheet = "bmp_skin_gamepad"; x = 403; y = 0; w = 70; h = 69; dest_w = 70; dest_h = 69 };
    { tag = "img_gpcursor0"; sheet = "bmp_skin_gamepad"; x = 0; y = 192; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_gpcursor1"; sheet = "bmp_skin_gamepad"; x = 64; y = 192; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_gpcursor2"; sheet = "bmp_skin_gamepad"; x = 128; y = 192; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_gpcursor3"; sheet = "bmp_skin_gamepad"; x = 192; y = 192; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_gpcursor4"; sheet = "bmp_skin_gamepad"; x = 256; y = 192; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_gpcursor5"; sheet = "bmp_skin_gamepad"; x = 320; y = 192; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_gpcursor6"; sheet = "bmp_skin_gamepad"; x = 384; y = 192; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_gpcursor7"; sheet = "bmp_skin_gamepad"; x = 448; y = 192; w = 64; h = 64; dest_w = 64; dest_h = 64 };
    { tag = "img_selglow"; sheet = "bmp_skin_battlemisc"; x = 0; y = 206; w = 200; h = 50; dest_w = 200; dest_h = 50 };
    { tag = "img_scroll"; sheet = "bmp_scroll"; x = 0; y = 0; w = 353; h = 256; dest_w = 353; dest_h = 256 };
    { tag = "img_bigscroll"; sheet = "bmp_scroll"; x = 0; y = 257; w = 441; h = 462; dest_w = 441; dest_h = 462 };
    { tag = "img_scrollbutt_act"; sheet = "bmp_scroll"; x = 380; y = 0; w = 132; h = 35; dest_w = 132; dest_h = 35 };
    { tag = "img_scrollbutt_hi"; sheet = "bmp_scroll"; x = 380; y = 36; w = 132; h = 35; dest_w = 132; dest_h = 35 };
    { tag = "img_scrollbutt_pres"; sheet = "bmp_scroll"; x = 380; y = 72; w = 132; h = 35; dest_w = 132; dest_h = 35 };
    { tag = "img_scrollbutt_gray"; sheet = "bmp_scroll"; x = 380; y = 108; w = 132; h = 35; dest_w = 132; dest_h = 35 };
    { tag = "img_scrollframe"; sheet = "bmp_scroll"; x = 382; y = 149; w = 78; h = 96; dest_w = 78; dest_h = 96 };
    { tag = "img_scrollbigframe"; sheet = "bmp_scroll"; x = 0; y = 720; w = 318; h = 256; dest_w = 318; dest_h = 256 };
    { tag = "img_scrollvsbar_bg"; sheet = "bmp_scroll"; x = 461; y = 149; w = 16; h = 148; dest_w = 16; dest_h = 148 };
    { tag = "img_scrollvsbar_decgray"; sheet = "bmp_scroll"; x = 478; y = 180; w = 16; h = 16; dest_w = 16; dest_h = 16 };
    { tag = "img_scrollvsbar_decup"; sheet = "bmp_scroll"; x = 478; y = 148; w = 16; h = 16; dest_w = 16; dest_h = 16 };
    { tag = "img_scrollvsbar_decdown"; sheet = "bmp_scroll"; x = 478; y = 164; w = 16; h = 16; dest_w = 16; dest_h = 16 };
    { tag = "img_scrollvsbar_incgray"; sheet = "bmp_scroll"; x = 478; y = 228; w = 16; h = 16; dest_w = 16; dest_h = 16 };
    { tag = "img_scrollvsbar_incup"; sheet = "bmp_scroll"; x = 478; y = 196; w = 16; h = 16; dest_w = 16; dest_h = 16 };
    { tag = "img_scrollvsbar_incdown"; sheet = "bmp_scroll"; x = 478; y = 212; w = 16; h = 16; dest_w = 16; dest_h = 16 };
    { tag = "img_scrollvsbar_thumb"; sheet = "bmp_scroll"; x = 478; y = 244; w = 16; h = 16; dest_w = 16; dest_h = 16 };
    { tag = "img_popup_0"; sheet = "bmp_skin_buttmisc"; x = 256; y = 396; w = 256; h = 15; dest_w = 256; dest_h = 15 };
    { tag = "img_popup_1"; sheet = "bmp_skin_buttmisc"; x = 256; y = 434; w = 256; h = 26; dest_w = 256; dest_h = 26 };
    { tag = "img_popup_2"; sheet = "bmp_skin_buttmisc"; x = 256; y = 412; w = 256; h = 15; dest_w = 256; dest_h = 15 };
    { tag = "img_charportrait"; sheet = "bmp_charportrait1"; x = 0; y = 0; w = 256; h = 256; dest_w = 128; dest_h = 128 };
    { tag = "img_portrait0"; sheet = "bmp_portraits"; x = 0; y = 0; w = 256; h = 256; dest_w = 128; dest_h = 128 };
    { tag = "img_portrait1"; sheet = "bmp_enemyportrait"; x = 0; y = 0; w = 256; h = 256; dest_w = 128; dest_h = 128 };
    { tag = "img_characterbg"; sheet = "bmp_characterbg"; x = 0; y = 0; w = 128; h = 128; dest_w = 128; dest_h = 128 };
    { tag = "img_portraitcomp"; sheet = "bmp_compportrait"; x = 0; y = 0; w = 256; h = 256; dest_w = 128; dest_h = 128 };
    { tag = "img_city_bg"; sheet = "bmp_citybits"; x = 0; y = 0; w = 984; h = 655; dest_w = 984; dest_h = 655 };
    { tag = "img_city_bord_l"; sheet = "bmp_citybits"; x = 2028; y = 0; w = 20; h = 655; dest_w = 20; dest_h = 655 };
    { tag = "img_city_bord_r"; sheet = "bmp_citybits"; x = 2028; y = 0; w = 20; h = 655; dest_w = 20; dest_h = 655 };
    { tag = "img_city_bld0"; sheet = "bmp_citybits"; x = 1787; y = 374; w = 83; h = 102; dest_w = 83; dest_h = 102 };
    { tag = "img_city_bld1"; sheet = "bmp_citybits"; x = 1222; y = 340; w = 264; h = 185; dest_w = 264; dest_h = 185 };
    { tag = "img_city_bld2"; sheet = "bmp_citybits"; x = 1787; y = 4; w = 221; h = 364; dest_w = 221; dest_h = 364 };
    { tag = "img_city_bld3"; sheet = "bmp_citybits"; x = 1418; y = 9; w = 366; h = 256; dest_w = 366; dest_h = 259 };
    { tag = "img_city_bld4a"; sheet = "bmp_citybits"; x = 1878; y = 377; w = 39; h = 99; dest_w = 39; dest_h = 99 };
    { tag = "img_city_bld4b"; sheet = "bmp_citybits"; x = 1923; y = 378; w = 39; h = 98; dest_w = 39; dest_h = 98 };
    { tag = "img_city_bld5"; sheet = "bmp_citybits"; x = 991; y = 11; w = 418; h = 202; dest_w = 418; dest_h = 202 };
    { tag = "img_city_bld6"; sheet = "bmp_citybits"; x = 991; y = 238; w = 225; h = 253; dest_w = 225; dest_h = 253 };
    { tag = "img_city_bld7a"; sheet = "bmp_citybits"; x = 1497; y = 348; w = 124; h = 123; dest_w = 124; dest_h = 123 };
    { tag = "img_city_bld7b"; sheet = "bmp_citybits"; x = 1632; y = 348; w = 114; h = 176; dest_w = 114; dest_h = 176 };
    { tag = "img_city_bld8"; sheet = "bmp_citybits"; x = 1005; y = 505; w = 93; h = 152; dest_w = 93; dest_h = 152 };
    { tag = "img_city_connlong"; sheet = "bmp_citybits"; x = 0; y = 810; w = 20; h = 36; dest_w = 20; dest_h = 36 };
    { tag = "img_city_connshort"; sheet = "bmp_citybits"; x = 0; y = 828; w = 20; h = 21; dest_w = 20; dest_h = 21 };
    { tag = "img_dblbutton_act"; sheet = "bmp_citybits"; x = 0; y = 675; w = 300; h = 32; dest_w = 300; dest_h = 32 };
    { tag = "img_dblbutton_hi"; sheet = "bmp_citybits"; x = 0; y = 708; w = 300; h = 32; dest_w = 300; dest_h = 32 };
    { tag = "img_dblbutton_hi1"; sheet = "bmp_citybits"; x = 301; y = 708; w = 300; h = 32; dest_w = 300; dest_h = 32 };
    { tag = "img_dblbutton_hi2"; sheet = "bmp_citybits"; x = 602; y = 708; w = 300; h = 32; dest_w = 300; dest_h = 32 };
    { tag = "img_dblbutton_hi3"; sheet = "bmp_citybits"; x = 903; y = 708; w = 300; h = 32; dest_w = 300; dest_h = 32 };
    { tag = "img_dblbutton_hi4"; sheet = "bmp_citybits"; x = 1204; y = 708; w = 300; h = 32; dest_w = 300; dest_h = 32 };
    { tag = "img_dblbutton_hi5"; sheet = "bmp_citybits"; x = 1505; y = 708; w = 300; h = 32; dest_w = 300; dest_h = 32 };
    { tag = "img_dblbutton_pres"; sheet = "bmp_citybits"; x = 0; y = 741; w = 300; h = 32; dest_w = 300; dest_h = 32 };
    { tag = "img_dblbutton_pres1"; sheet = "bmp_citybits"; x = 301; y = 741; w = 300; h = 32; dest_w = 300; dest_h = 32 };
    { tag = "img_dblbutton_pres2"; sheet = "bmp_citybits"; x = 602; y = 741; w = 300; h = 32; dest_w = 300; dest_h = 32 };
    { tag = "img_dblbutton_pres3"; sheet = "bmp_citybits"; x = 903; y = 741; w = 300; h = 32; dest_w = 300; dest_h = 32 };
    { tag = "img_dblbutton_pres4"; sheet = "bmp_citybits"; x = 1204; y = 741; w = 300; h = 32; dest_w = 300; dest_h = 32 };
    { tag = "img_dblbutton_pres5"; sheet = "bmp_citybits"; x = 1505; y = 741; w = 300; h = 32; dest_w = 300; dest_h = 32 };
    { tag = "img_dblbutton_gray"; sheet = "bmp_citybits"; x = 0; y = 774; w = 300; h = 32; dest_w = 300; dest_h = 32 };
  |]

let frame_of_tag (tag : string) : frame option =
  let rec go (l : frame list) =
    match l with
    | [] -> None
    | (f : frame) :: rest -> if f.tag = tag then Some f else go rest
  in
  go (Array.to_list frames)

(** Every frame on one sheet, in registry order.

    The sheet's frames are contiguous in the file, so this is a scan rather than
    an index - and a scan is what keeps [frames] a plain array that can be read
    straight out of the registry. *)
let frames_on (sheet : string) : frame array =
  Array.of_list
    (List.filter (fun (f : frame) -> f.sheet = sheet) (Array.to_list frames))

(** The scale a frame is meant to be drawn at, as a numerator and a denominator.

    Returns 1,1 when the frame is drawn at its stored size, which is the common
    case. The red glows are the exception: 88x88 stored, 64x64 drawn. *)
let draw_scale (f : frame) : int * int =
  if f.dest_w = f.w then (1, 1)
  else
    let rec gcd a b = if b = 0 then a else gcd b (a mod b) in
    let g = gcd f.w f.dest_w in
    (f.dest_w / g, f.w / g)

