(** Generated by tools/extract_spell_data.ps1. Do not edit by hand.

    The real spell table, parsed from the game's own assets:

    * [Assets/Spells/*.xml] for the four costs, [Data cooldown], the [Learn]
      requirements, and the [Input] type.
    * [English/StandardSpellsText.xml] for the turn rule, which has no field in
      the XML. The game states it in each spell's own DETL line, so that is
      transcribed rather than inferred. Breakdowns:

      - [Spell.EndsTurn], the default, is 97 of the 129: no turn clause at all.
      - [Spell.KeepsTurn] is 13, from "Your turn does not end".
      - [Spell.EndsTurnAfterEffect] is 10, from "the turn ends".
      - [Spell.KeepsTurnIfMana] is 9, from "Your turn does not end if COLOUR
        Mana is N+", colour mapped to the engine element: Earth green, Fire
        red, Air yellow, Water blue.

    Casting usually ends the turn, so the caster does not also swap that turn.
    Only the minority hand it back. That is the opposite of what the battle
    loop first assumed.

    SARC is excluded: it is the spell-research mini-game descriptor rather than
    a battle spell. *)

let spell_descriptors : Spell.descriptor list = [
  { id = "SBAC"; cost_earth = 0; cost_fire = 6; cost_air = 4; cost_water = 0;
    cooldown = 0; learn_score = 350; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurnIfMana (Fire, 15) };
  { id = "SBAV"; cost_earth = 20; cost_fire = 5; cost_air = 5; cost_water = 10;
    cooldown = 0; learn_score = 960; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SBLU"; cost_earth = 5; cost_fire = 0; cost_air = 5; cost_water = 5;
    cooldown = 0; learn_score = 300; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurnAfterEffect };
  { id = "SBNA"; cost_earth = 0; cost_fire = 0; cost_air = 5; cost_water = 0;
    cooldown = 0; learn_score = 500; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SBNE"; cost_earth = 5; cost_fire = 0; cost_air = 0; cost_water = 0;
    cooldown = 0; learn_score = 500; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SBNF"; cost_earth = 0; cost_fire = 5; cost_air = 0; cost_water = 0;
    cooldown = 0; learn_score = 500; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SBNW"; cost_earth = 0; cost_fire = 0; cost_air = 0; cost_water = 5;
    cooldown = 0; learn_score = 500; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SBRA"; cost_earth = 6; cost_fire = 10; cost_air = 0; cost_water = 0;
    cooldown = 3; learn_score = 750; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurnIfMana (Fire, 15) };
  { id = "SBRF"; cost_earth = 0; cost_fire = 25; cost_air = 10; cost_water = 0;
    cooldown = 3; learn_score = 990; learn_masks = 0; learn_keys = 0;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SBRI"; cost_earth = 0; cost_fire = 0; cost_air = 10; cost_water = 25;
    cooldown = 3; learn_score = 990; learn_masks = 0; learn_keys = 0;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SBRL"; cost_earth = 4; cost_fire = 8; cost_air = 0; cost_water = 8;
    cooldown = 3; learn_score = 640; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurnAfterEffect };
  { id = "SBRP"; cost_earth = 0; cost_fire = 0; cost_air = 30; cost_water = 12;
    cooldown = 3; learn_score = 990; learn_masks = 0; learn_keys = 0;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SBRZ"; cost_earth = 30; cost_fire = 0; cost_air = 12; cost_water = 0;
    cooldown = 3; learn_score = 990; learn_masks = 0; learn_keys = 0;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SBSG"; cost_earth = 4; cost_fire = 0; cost_air = 4; cost_water = 0;
    cooldown = 0; learn_score = 550; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SBST"; cost_earth = 8; cost_fire = 0; cost_air = 0; cost_water = 5;
    cooldown = 0; learn_score = 575; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurn };
  { id = "SBUR"; cost_earth = 3; cost_fire = 4; cost_air = 0; cost_water = 0;
    cooldown = 2; learn_score = 600; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurnAfterEffect };
  { id = "SCAU"; cost_earth = 0; cost_fire = 6; cost_air = 0; cost_water = 8;
    cooldown = 0; learn_score = 300; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SCBO"; cost_earth = 8; cost_fire = 8; cost_air = 8; cost_water = 8;
    cooldown = 0; learn_score = 680; learn_masks = 1; learn_keys = 1;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SCHA"; cost_earth = 3; cost_fire = 3; cost_air = 0; cost_water = 3;
    cooldown = 0; learn_score = 350; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurn };
  { id = "SCHE"; cost_earth = 0; cost_fire = 3; cost_air = 3; cost_water = 3;
    cooldown = 0; learn_score = 400; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurn };
  { id = "SCHF"; cost_earth = 3; cost_fire = 0; cost_air = 3; cost_water = 3;
    cooldown = 0; learn_score = 400; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurn };
  { id = "SCHG"; cost_earth = 6; cost_fire = 6; cost_air = 6; cost_water = 6;
    cooldown = 0; learn_score = 600; learn_masks = 1; learn_keys = 2;
    input_type = 2; turn_cost = Spell.EndsTurn };
  { id = "SCHL"; cost_earth = 0; cost_fire = 6; cost_air = 6; cost_water = 0;
    cooldown = 0; learn_score = 250; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurnIfMana (Air, 15) };
  { id = "SCHM"; cost_earth = 0; cost_fire = 0; cost_air = 7; cost_water = 6;
    cooldown = 0; learn_score = 1050; learn_masks = 0; learn_keys = 1;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SCHV"; cost_earth = 16; cost_fire = 16; cost_air = 16; cost_water = 16;
    cooldown = 3; learn_score = 850; learn_masks = 0; learn_keys = 0;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SCHW"; cost_earth = 3; cost_fire = 3; cost_air = 3; cost_water = 0;
    cooldown = 0; learn_score = 400; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurn };
  { id = "SCLE"; cost_earth = 0; cost_fire = 0; cost_air = 9; cost_water = 9;
    cooldown = 5; learn_score = 550; learn_masks = 1; learn_keys = 1;
    input_type = 0; turn_cost = Spell.EndsTurnAfterEffect };
  { id = "SCLI"; cost_earth = 6; cost_fire = 0; cost_air = 9; cost_water = 6;
    cooldown = 0; learn_score = 500; learn_masks = 1; learn_keys = 2;
    input_type = 1; turn_cost = Spell.EndsTurn };
  { id = "SCLM"; cost_earth = 0; cost_fire = 0; cost_air = 2; cost_water = 3;
    cooldown = 0; learn_score = 275; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurnIfMana (Water, 10) };
  { id = "SCLV"; cost_earth = 0; cost_fire = 9; cost_air = 6; cost_water = 0;
    cooldown = 1; learn_score = 700; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SCMA"; cost_earth = 6; cost_fire = 6; cost_air = 6; cost_water = 6;
    cooldown = 1; learn_score = 520; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SCON"; cost_earth = 8; cost_fire = 8; cost_air = 8; cost_water = 8;
    cooldown = 2; learn_score = 1250; learn_masks = 1; learn_keys = 1;
    input_type = 3; turn_cost = Spell.EndsTurn };
  { id = "SCOU"; cost_earth = 0; cost_fire = 2; cost_air = 2; cost_water = 2;
    cooldown = 0; learn_score = 300; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurnIfMana (Water, 10) };
  { id = "SCTH"; cost_earth = 0; cost_fire = 0; cost_air = 25; cost_water = 20;
    cooldown = 2; learn_score = 850; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SCTO"; cost_earth = 0; cost_fire = 4; cost_air = 4; cost_water = 0;
    cooldown = 0; learn_score = 260; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SDBO"; cost_earth = 6; cost_fire = 0; cost_air = 0; cost_water = 6;
    cooldown = 2; learn_score = 580; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SDBR"; cost_earth = 8; cost_fire = 16; cost_air = 8; cost_water = 8;
    cooldown = 3; learn_score = 1500; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SDDI"; cost_earth = 0; cost_fire = 6; cost_air = 9; cost_water = 0;
    cooldown = 0; learn_score = 650; learn_masks = 1; learn_keys = 1;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SDGZ"; cost_earth = 30; cost_fire = 20; cost_air = 0; cost_water = 0;
    cooldown = 1; learn_score = 1400; learn_masks = 0; learn_keys = 1;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SDIV"; cost_earth = 0; cost_fire = 0; cost_air = 6; cost_water = 6;
    cooldown = 0; learn_score = 300; learn_masks = 1; learn_keys = 3;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SDRR"; cost_earth = 0; cost_fire = 25; cost_air = 15; cost_water = 0;
    cooldown = 1; learn_score = 995; learn_masks = 0; learn_keys = 0;
    input_type = 0; turn_cost = Spell.EndsTurnAfterEffect };
  { id = "SDST"; cost_earth = 8; cost_fire = 8; cost_air = 16; cost_water = 0;
    cooldown = 0; learn_score = 850; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SDUP"; cost_earth = 10; cost_fire = 0; cost_air = 0; cost_water = 10;
    cooldown = 0; learn_score = 950; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SEGZ"; cost_earth = 20; cost_fire = 20; cost_air = 20; cost_water = 20;
    cooldown = 0; learn_score = 900; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SENR"; cost_earth = 2; cost_fire = 6; cost_air = 0; cost_water = 0;
    cooldown = 0; learn_score = 250; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurn };
  { id = "SENT"; cost_earth = 12; cost_fire = 0; cost_air = 12; cost_water = 0;
    cooldown = 3; learn_score = 1100; learn_masks = 1; learn_keys = 1;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SEPO"; cost_earth = 0; cost_fire = 7; cost_air = 7; cost_water = 7;
    cooldown = 0; learn_score = 550; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SESK"; cost_earth = 8; cost_fire = 0; cost_air = 0; cost_water = 5;
    cooldown = 0; learn_score = 1000; learn_masks = 0; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SEVA"; cost_earth = 0; cost_fire = 5; cost_air = 0; cost_water = 3;
    cooldown = 2; learn_score = 400; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurnAfterEffect };
  { id = "SFAV"; cost_earth = 0; cost_fire = 0; cost_air = 6; cost_water = 8;
    cooldown = 0; learn_score = 250; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SFBA"; cost_earth = 0; cost_fire = 9; cost_air = 6; cost_water = 0;
    cooldown = 2; learn_score = 800; learn_masks = 1; learn_keys = 2;
    input_type = 3; turn_cost = Spell.EndsTurn };
  { id = "SFBM"; cost_earth = 0; cost_fire = 10; cost_air = 5; cost_water = 0;
    cooldown = 0; learn_score = 750; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SFBO"; cost_earth = 0; cost_fire = 4; cost_air = 4; cost_water = 0;
    cooldown = 0; learn_score = 250; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SFBT"; cost_earth = 0; cost_fire = 0; cost_air = 6; cost_water = 9;
    cooldown = 2; learn_score = 750; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SFCA"; cost_earth = 20; cost_fire = 6; cost_air = 6; cost_water = 0;
    cooldown = 0; learn_score = 825; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SFLV"; cost_earth = 5; cost_fire = 25; cost_air = 5; cost_water = 10;
    cooldown = 0; learn_score = 860; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SFOD"; cost_earth = 8; cost_fire = 8; cost_air = 8; cost_water = 8;
    cooldown = 0; learn_score = 800; learn_masks = 1; learn_keys = 2;
    input_type = 3; turn_cost = Spell.EndsTurnAfterEffect };
  { id = "SFOF"; cost_earth = 0; cost_fire = 6; cost_air = 8; cost_water = 0;
    cooldown = 0; learn_score = 400; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SFRZ"; cost_earth = 3; cost_fire = 0; cost_air = 0; cost_water = 4;
    cooldown = 2; learn_score = 400; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SFSH"; cost_earth = 0; cost_fire = 5; cost_air = 0; cost_water = 6;
    cooldown = 0; learn_score = 1300; learn_masks = 1; learn_keys = 1;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SFSK"; cost_earth = 4; cost_fire = 9; cost_air = 4; cost_water = 3;
    cooldown = 3; learn_score = 850; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SFSP"; cost_earth = 4; cost_fire = 32; cost_air = 4; cost_water = 0;
    cooldown = 0; learn_score = 950; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SGEM"; cost_earth = 0; cost_fire = 0; cost_air = 4; cost_water = 6;
    cooldown = 0; learn_score = 300; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SGOW"; cost_earth = 0; cost_fire = 0; cost_air = 6; cost_water = 5;
    cooldown = 2; learn_score = 500; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SHAS"; cost_earth = 0; cost_fire = 0; cost_air = 6; cost_water = 5;
    cooldown = 0; learn_score = 275; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SHBT"; cost_earth = 6; cost_fire = 12; cost_air = 0; cost_water = 0;
    cooldown = 3; learn_score = 850; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SHGO"; cost_earth = 0; cost_fire = 12; cost_air = 4; cost_water = 0;
    cooldown = 0; learn_score = 750; learn_masks = 1; learn_keys = 1;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SHID"; cost_earth = 5; cost_fire = 0; cost_air = 3; cost_water = 5;
    cooldown = 0; learn_score = 600; learn_masks = 1; learn_keys = 0;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SHOP"; cost_earth = 5; cost_fire = 2; cost_air = 7; cost_water = 0;
    cooldown = 2; learn_score = 250; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SHSI"; cost_earth = 3; cost_fire = 0; cost_air = 0; cost_water = 3;
    cooldown = 0; learn_score = 375; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SHWL"; cost_earth = 0; cost_fire = 6; cost_air = 8; cost_water = 0;
    cooldown = 0; learn_score = 500; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SIST"; cost_earth = 30; cost_fire = 10; cost_air = 10; cost_water = 10;
    cooldown = 5; learn_score = 1750; learn_masks = 0; learn_keys = 0;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SKLO"; cost_earth = 6; cost_fire = 0; cost_air = 6; cost_water = 6;
    cooldown = 2; learn_score = 800; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurnAfterEffect };
  { id = "SLCO"; cost_earth = 12; cost_fire = 24; cost_air = 0; cost_water = 0;
    cooldown = 0; learn_score = 790; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurn };
  { id = "SLIG"; cost_earth = 0; cost_fire = 6; cost_air = 10; cost_water = 0;
    cooldown = 2; learn_score = 1450; learn_masks = 0; learn_keys = 1;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SLIS"; cost_earth = 12; cost_fire = 0; cost_air = 18; cost_water = 12;
    cooldown = 0; learn_score = 1050; learn_masks = 1; learn_keys = 1;
    input_type = 1; turn_cost = Spell.EndsTurn };
  { id = "SMBU"; cost_earth = 3; cost_fire = 4; cost_air = 0; cost_water = 0;
    cooldown = 0; learn_score = 280; learn_masks = 2; learn_keys = 3;
    input_type = 0; turn_cost = Spell.KeepsTurnIfMana (Fire, 8) };
  { id = "SMST"; cost_earth = 10; cost_fire = 14; cost_air = 6; cost_water = 0;
    cooldown = 2; learn_score = 1300; learn_masks = 1; learn_keys = 1;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SNWR"; cost_earth = 25; cost_fire = 0; cost_air = 0; cost_water = 10;
    cooldown = 5; learn_score = 900; learn_masks = 0; learn_keys = 0;
    input_type = 0; turn_cost = Spell.EndsTurnAfterEffect };
  { id = "SPAU"; cost_earth = 0; cost_fire = 0; cost_air = 12; cost_water = 9;
    cooldown = 0; learn_score = 900; learn_masks = 1; learn_keys = 1;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SPET"; cost_earth = 24; cost_fire = 12; cost_air = 0; cost_water = 0;
    cooldown = 3; learn_score = 1300; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SPRO"; cost_earth = 8; cost_fire = 8; cost_air = 8; cost_water = 8;
    cooldown = 2; learn_score = 400; learn_masks = 1; learn_keys = 2;
    input_type = 3; turn_cost = Spell.EndsTurn };
  { id = "SRBI"; cost_earth = 8; cost_fire = 0; cost_air = 0; cost_water = 6;
    cooldown = 0; learn_score = 450; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SREV"; cost_earth = 10; cost_fire = 25; cost_air = 20; cost_water = 0;
    cooldown = 0; learn_score = 825; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SRFC"; cost_earth = 0; cost_fire = 0; cost_air = 9; cost_water = 6;
    cooldown = 1; learn_score = 1050; learn_masks = 0; learn_keys = 1;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SRGN"; cost_earth = 0; cost_fire = 0; cost_air = 0; cost_water = 7;
    cooldown = 0; learn_score = 900; learn_masks = 1; learn_keys = 1;
    input_type = 0; turn_cost = Spell.KeepsTurn };
  { id = "SRNC"; cost_earth = 9; cost_fire = 9; cost_air = 9; cost_water = 9;
    cooldown = 5; learn_score = 250; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SRND"; cost_earth = 6; cost_fire = 2; cost_air = 6; cost_water = 0;
    cooldown = 0; learn_score = 350; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurn };
  { id = "SROF"; cost_earth = 8; cost_fire = 12; cost_air = 0; cost_water = 0;
    cooldown = 2; learn_score = 700; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SSAN"; cost_earth = 8; cost_fire = 0; cost_air = 8; cost_water = 4;
    cooldown = 0; learn_score = 500; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SSBD"; cost_earth = 0; cost_fire = 9; cost_air = 0; cost_water = 12;
    cooldown = 2; learn_score = 460; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SSBL"; cost_earth = 0; cost_fire = 8; cost_air = 6; cost_water = 0;
    cooldown = 0; learn_score = 700; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SSBM"; cost_earth = 0; cost_fire = 0; cost_air = 4; cost_water = 6;
    cooldown = 0; learn_score = 550; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SSCV"; cost_earth = 5; cost_fire = 0; cost_air = 4; cost_water = 0;
    cooldown = 1; learn_score = 250; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SSGZ"; cost_earth = 6; cost_fire = 0; cost_air = 0; cost_water = 12;
    cooldown = 2; learn_score = 750; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurnIfMana (Earth, 15) };
  { id = "SSHO"; cost_earth = 4; cost_fire = 8; cost_air = 0; cost_water = 0;
    cooldown = 0; learn_score = 350; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SSNK"; cost_earth = 5; cost_fire = 0; cost_air = 0; cost_water = 5;
    cooldown = 0; learn_score = 300; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurn };
  { id = "SSOA"; cost_earth = 5; cost_fire = 0; cost_air = 6; cost_water = 5;
    cooldown = 3; learn_score = 400; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurnIfMana (Air, 15) };
  { id = "SSOB"; cost_earth = 10; cost_fire = 10; cost_air = 10; cost_water = 10;
    cooldown = 1; learn_score = 750; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SSOS"; cost_earth = 10; cost_fire = 10; cost_air = 10; cost_water = 10;
    cooldown = 1; learn_score = 750; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SSPA"; cost_earth = 6; cost_fire = 8; cost_air = 0; cost_water = 0;
    cooldown = 0; learn_score = 400; learn_masks = 1; learn_keys = 2;
    input_type = 3; turn_cost = Spell.EndsTurn };
  { id = "SSPF"; cost_earth = 5; cost_fire = 0; cost_air = 0; cost_water = 30;
    cooldown = 4; learn_score = 350; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SSPT"; cost_earth = 7; cost_fire = 7; cost_air = 0; cost_water = 12;
    cooldown = 1; learn_score = 1500; learn_masks = 1; learn_keys = 0;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SSSW"; cost_earth = 6; cost_fire = 0; cost_air = 12; cost_water = 18;
    cooldown = 0; learn_score = 950; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurn };
  { id = "SSTL"; cost_earth = 0; cost_fire = 0; cost_air = 6; cost_water = 6;
    cooldown = 0; learn_score = 250; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SSTO"; cost_earth = 0; cost_fire = 8; cost_air = 0; cost_water = 8;
    cooldown = 2; learn_score = 800; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SSTU"; cost_earth = 6; cost_fire = 5; cost_air = 0; cost_water = 0;
    cooldown = 2; learn_score = 1000; learn_masks = 1; learn_keys = 1;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SSUT"; cost_earth = 0; cost_fire = 8; cost_air = 5; cost_water = 5;
    cooldown = 0; learn_score = 1000; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SSWA"; cost_earth = 20; cost_fire = 5; cost_air = 5; cost_water = 0;
    cooldown = 0; learn_score = 1400; learn_masks = 1; learn_keys = 1;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SSWM"; cost_earth = 0; cost_fire = 0; cost_air = 15; cost_water = 9;
    cooldown = 1; learn_score = 850; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SSWP"; cost_earth = 0; cost_fire = 4; cost_air = 8; cost_water = 0;
    cooldown = 0; learn_score = 300; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurnIfMana (Air, 14) };
  { id = "STAU"; cost_earth = 0; cost_fire = 4; cost_air = 8; cost_water = 4;
    cooldown = 0; learn_score = 260; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "STHR"; cost_earth = 0; cost_fire = 6; cost_air = 0; cost_water = 6;
    cooldown = 0; learn_score = 250; learn_masks = 1; learn_keys = 2;
    input_type = 3; turn_cost = Spell.EndsTurn };
  { id = "STHU"; cost_earth = 0; cost_fire = 15; cost_air = 0; cost_water = 0;
    cooldown = 0; learn_score = 350; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "STHX"; cost_earth = 6; cost_fire = 8; cost_air = 0; cost_water = 0;
    cooldown = 1; learn_score = 550; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "STRM"; cost_earth = 7; cost_fire = 7; cost_air = 0; cost_water = 0;
    cooldown = 0; learn_score = 300; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "STWH"; cost_earth = 12; cost_fire = 5; cost_air = 5; cost_water = 0;
    cooldown = 0; learn_score = 550; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurn };
  { id = "SVAM"; cost_earth = 0; cost_fire = 8; cost_air = 6; cost_water = 0;
    cooldown = 0; learn_score = 300; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SVIG"; cost_earth = 0; cost_fire = 0; cost_air = 6; cost_water = 8;
    cooldown = 0; learn_score = 300; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SWBU"; cost_earth = 10; cost_fire = 0; cost_air = 22; cost_water = 0;
    cooldown = 3; learn_score = 850; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SWEB"; cost_earth = 8; cost_fire = 0; cost_air = 12; cost_water = 0;
    cooldown = 3; learn_score = 800; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SWHI"; cost_earth = 7; cost_fire = 7; cost_air = 0; cost_water = 7;
    cooldown = 0; learn_score = 600; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SWLO"; cost_earth = 0; cost_fire = 0; cost_air = 8; cost_water = 8;
    cooldown = 0; learn_score = 250; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SWMG"; cost_earth = 8; cost_fire = 8; cost_air = 8; cost_water = 8;
    cooldown = 1; learn_score = 450; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.KeepsTurn };
  { id = "SWOF"; cost_earth = 9; cost_fire = 6; cost_air = 0; cost_water = 0;
    cooldown = 0; learn_score = 1100; learn_masks = 1; learn_keys = 1;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SWOP"; cost_earth = 20; cost_fire = 20; cost_air = 20; cost_water = 20;
    cooldown = 3; learn_score = 2000; learn_masks = 0; learn_keys = 0;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SWOT"; cost_earth = 6; cost_fire = 0; cost_air = 0; cost_water = 9;
    cooldown = 0; learn_score = 1050; learn_masks = 1; learn_keys = 0;
    input_type = 0; turn_cost = Spell.EndsTurn };
  { id = "SWTD"; cost_earth = 10; cost_fire = 0; cost_air = 0; cost_water = 4;
    cooldown = 0; learn_score = 280; learn_masks = 1; learn_keys = 2;
    input_type = 0; turn_cost = Spell.EndsTurnAfterEffect };
  { id = "SZAP"; cost_earth = 0; cost_fire = 7; cost_air = 7; cost_water = 0;
    cooldown = 0; learn_score = 290; learn_masks = 1; learn_keys = 1;
    input_type = 0; turn_cost = Spell.EndsTurn };
]

let descriptor_of (id : string) : Spell.descriptor option =
  List.find_opt (fun (d : Spell.descriptor) -> d.id = id) spell_descriptors

(** The table as runtime spells, ready to hand to [Battle.create]. Lives here
    rather than in [Spell] because [spell] defines [turn_cost] and this module
    consumes it; a loader in [spell] would close the dependency cycle.

    [Spell_ai.hook_of] supplies the spell's own [ShouldAICastSpell] where it has
    been ported. Where it has not, the hook is attached as "never cast" rather
    than left absent.

    The distinction matters. An absent hook means the script defines none, and
    that is a yes, which is right for a spell built in a test. An unported hook
    is not the same thing: we know the script has one and we know we have not
    read it yet, and guessing yes would make the AI cast spells the game
    deliberately suppresses. SBRA is the clear case, since its hook requires six
    or more red gems on the board and a mediocre board evaluation, and a
    permissive default would have it cast whenever the mana is there.

    So the policy is: unknown means no. 49 of 129 hooks are ported; the other 80
    are listed by [tools/extract_spell_ai.ps1]. *)
let load_spell_table () : Spell.spell list =
  List.map
    (fun (d : Spell.descriptor) ->
      let hook =
        match Spell_ai.hook_of d.id with
        | Some f -> f
        | None -> fun (_ : Spell.ai_context) -> false
      in
      Spell.spell_of_descriptor d ?should_ai_cast:(Some hook) ())
    spell_descriptors

(** Spells whose AI hook has been ported. *)
let spells_with_ai_hook =
  List.filter
    (fun (d : Spell.descriptor) -> Spell_ai.hook_of d.id <> None)
    spell_descriptors

let spells_without_ai_hook =
  List.filter
    (fun (d : Spell.descriptor) -> Spell_ai.hook_of d.id = None)
    spell_descriptors