(** Generated by tools/extract_spell_ai.ps1. Do not edit by hand.

    Each spell's own [ShouldAICastSpell], ported from its Lua script in
    [Assets/Spells/*.lua].

    Only the mechanical shape is generated here:

        return Std_AISpellcastingChance(N);

    Anything else is left unported and reported by the script, because those
    bodies read the board, the caster's mana, or its items and need
    individual treatment. An absent entry means "not ported", not "always
    cast": [Spell.should_ai_cast] defaults a missing hook to true, so the
    unported spells currently always say yes. That is a known gap and it is
    the reason [lib/spell_ai_manual.ml] exists.

    [Std_AISpellcastingChance] is Lua, in
    [Assets/Scripts/StandardUtilityScripts.lua], not an engine native; its
    body is transcribed in [Spell.ai_spellcasting_chance]. *)

let should_ai_cast_hook : (string * (Spell.ai_context -> bool)) list = [
  ("SBAC", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SBLU", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SBRF", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:50 ctx);
  ("SBRI", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:50 ctx);
  ("SBRP", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:50 ctx);
  ("SBRZ", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:50 ctx);
  ("SBSG", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:15 ctx);
  ("SCAU", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SCHA", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SCHE", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SCHF", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SCHW", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SCLM", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SCMA", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:10 ctx);
  ("SDBO", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:15 ctx);
  ("SDBR", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SENT", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SEPO", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SEVA", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SFAV", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SFBM", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:10 ctx);
  ("SFCA", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:20 ctx);
  ("SFOD", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SFOF", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SGOW", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SHGO", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:30 ctx);
  ("SHOP", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SHSI", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SKLO", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SLCO", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:20 ctx);
  ("SLIG", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SMST", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:20 ctx);
  ("SPAU", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SPRO", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SREV", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:50 ctx);
  ("SRNC", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SRND", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:10 ctx);
  ("SSAN", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:5 ctx);
  ("SSBD", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SSPA", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SSTU", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:10 ctx);
  ("SSUT", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("STWH", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:10 ctx);
  ("SVIG", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SWHI", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SWLO", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SWMG", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
  ("SWOP", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:15 ctx);
  ("SWOT", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:0 ctx);
]

(** The ported hook for [id], if it has one yet.

    The hand-written board-reading hooks in [Spell_ai_manual] take precedence,
    since a spell can only have one hook and that file exists precisely for the
    ones this script cannot express. The lookup order belongs here rather than
    as an edit to the generated file, because regenerating overwrites it. *)
let hook_of (id : string) : (Spell.ai_context -> bool) option =
  match Spell_ai_manual.manual_hook_of id with
  | Some f -> Some f
  | None -> List.assoc_opt id should_ai_cast_hook
