(* Generated by tools/extract_spell_fx.py from
   Assets/Scripts/StandardUtilityScripts.lua and Assets/Spells/*.lua.
   Do not edit by hand; re-run the extractor. *)

(** Which effect and sound a spell plays, as the game's own scripts decide it.

    Every spell asks for its effect through one of four `Std_*SpellEffect`
    helpers, and each helper resolves the `SPELLFX_*` constant it is given
    through the two tables below. So the constant a spell passes *is* the
    presentation - which means this is data, transcribed rather than chosen.

    [Default] and [Default_gfx_only] are the awkward ones. Neither appears in
    either table: `Std_CastSpellEffect` special-cases them, adding `Spell0` and
    `Spell1` to the caster, and playing `snd_spellnature` only for [Default].
    That is why there is a [cast_sound_of] as well as a [sound_of] - the first
    is what the helper does, the second is only what its table says. *)

type fx =
  | Healing
  | Necro
  | Water
  | Air
  | Frost
  | Symbol
  | Chaos
  | Good
  | Stone
  | Hide
  | War
  | Nature
  | Stun
  | Fireball
  | Hurlgoblin
  | Poison
  | Disease
  | Web
  | Fear
  | Spin
  | Sparkle
  | Default_Sound_Only
  | Default
  | Default_Gfx_Only

let all = [
  Healing;
  Necro;
  Water;
  Air;
  Frost;
  Symbol;
  Chaos;
  Good;
  Stone;
  Hide;
  War;
  Nature;
  Stun;
  Fireball;
  Hurlgoblin;
  Poison;
  Disease;
  Web;
  Fear;
  Spin;
  Sparkle;
  Default_Sound_Only;
  Default;
  Default_Gfx_Only;
]

(** The name a spell script writes, from the name this module uses. *)
let constant_of = function
  | Healing -> "SPELLFX_HEALING"
  | Necro -> "SPELLFX_NECRO"
  | Water -> "SPELLFX_WATER"
  | Air -> "SPELLFX_AIR"
  | Frost -> "SPELLFX_FROST"
  | Symbol -> "SPELLFX_SYMBOL"
  | Chaos -> "SPELLFX_CHAOS"
  | Good -> "SPELLFX_GOOD"
  | Stone -> "SPELLFX_STONE"
  | Hide -> "SPELLFX_HIDE"
  | War -> "SPELLFX_WAR"
  | Nature -> "SPELLFX_NATURE"
  | Stun -> "SPELLFX_STUN"
  | Fireball -> "SPELLFX_FIREBALL"
  | Hurlgoblin -> "SPELLFX_HURLGOBLIN"
  | Poison -> "SPELLFX_POISON"
  | Disease -> "SPELLFX_DISEASE"
  | Web -> "SPELLFX_WEB"
  | Fear -> "SPELLFX_FEAR"
  | Spin -> "SPELLFX_SPIN"
  | Sparkle -> "SPELLFX_SPARKLE"
  | Default_Sound_Only -> "SPELLFX_DEFAULTSOUNDONLY"
  | Default -> "SPELLFX_DEFAULT"
  | Default_Gfx_Only -> "SPELLFX_DEFAULTGFXONLY"

let of_constant = function
  | "SPELLFX_HEALING" -> Some Healing
  | "SPELLFX_NECRO" -> Some Necro
  | "SPELLFX_WATER" -> Some Water
  | "SPELLFX_AIR" -> Some Air
  | "SPELLFX_FROST" -> Some Frost
  | "SPELLFX_SYMBOL" -> Some Symbol
  | "SPELLFX_CHAOS" -> Some Chaos
  | "SPELLFX_GOOD" -> Some Good
  | "SPELLFX_STONE" -> Some Stone
  | "SPELLFX_HIDE" -> Some Hide
  | "SPELLFX_WAR" -> Some War
  | "SPELLFX_NATURE" -> Some Nature
  | "SPELLFX_STUN" -> Some Stun
  | "SPELLFX_FIREBALL" -> Some Fireball
  | "SPELLFX_HURLGOBLIN" -> Some Hurlgoblin
  | "SPELLFX_POISON" -> Some Poison
  | "SPELLFX_DISEASE" -> Some Disease
  | "SPELLFX_WEB" -> Some Web
  | "SPELLFX_FEAR" -> Some Fear
  | "SPELLFX_SPIN" -> Some Spin
  | "SPELLFX_SPARKLE" -> Some Sparkle
  | "SPELLFX_DEFAULTSOUNDONLY" -> Some Default_Sound_Only
  | "SPELLFX_DEFAULT" -> Some Default
  | "SPELLFX_DEFAULTGFXONLY" -> Some Default_Gfx_Only
  | _ -> None

(** The effect asset `Std_GetSpellFXAsset` names, if any.

    Empty in the source means no effect, and that is [None] here rather than
    [Some ""]: a caller that forgets to test the string would draw a blank
    sprite and call it a spell effect. *)
let asset_of = function
  | Healing -> Some "SpellHealing"
  | Necro -> Some "SpellNecro"
  | Water -> Some "SpellWater"
  | Air -> Some "SpellAir"
  | Frost -> Some "SpellFrost"
  | Symbol -> Some "SpellSymbol"
  | Chaos -> Some "SpellChaos"
  | Good -> Some "SpellGood"
  | Stone -> Some "SpellStone"
  | Hide -> Some "SpellHide"
  | War -> Some "SpellWar"
  | Nature -> Some "SpellNature"
  | Stun -> Some "SpellStun"
  | Fireball -> Some "SpellFireball"
  | Hurlgoblin -> Some "SpellFireball"
  | Poison -> Some "SpellPoison"
  | Disease -> Some "SpellDisease"
  | Web -> Some "SpellWeb"
  | Fear -> Some "SpellFear"
  | Spin -> Some "SpellSpin"
  | Sparkle -> Some "SpellSparkle"
  | Default_Sound_Only -> None
  | Default -> None
  | Default_Gfx_Only -> None

(** The sound tag `Std_GetSpellSoundAsset` names, if any. *)
let sound_of = function
  | Healing -> Some "snd_spellheal"
  | Necro -> Some "snd_spellalter"
  | Water -> Some "snd_spellalter"
  | Air -> Some "snd_spellbuff"
  | Frost -> Some "snd_spellalter"
  | Symbol -> Some "snd_spellalter"
  | Chaos -> Some "snd_spellfire"
  | Good -> Some "snd_spellbuff"
  | Stone -> Some "snd_spellnature"
  | Hide -> Some "snd_spellbuff"
  | War -> Some "snd_spellfire"
  | Nature -> Some "snd_spellnature"
  | Stun -> Some "snd_spelldebuff"
  | Fireball -> Some "snd_spellfire"
  | Hurlgoblin -> Some "snd_spellfire"
  | Poison -> Some "snd_spelldebuff"
  | Disease -> Some "snd_spelldebuff"
  | Web -> Some "snd_spelldebuff"
  | Fear -> Some "snd_spelldebuff"
  | Spin -> Some "snd_spellalter"
  | Sparkle -> Some "snd_spellbuff"
  | Default_Sound_Only -> Some "snd_spellnature"
  | Default -> None
  | Default_Gfx_Only -> None

(** What `Std_CastSpellEffect` plays for a cast, which is not [sound_of].

    [Default] is the special case: the helper skips the lookup entirely, plays
    `snd_spellnature` and adds Spell0 and Spell1 to the caster. [Default_gfx_only]
    is the same two effects with no sound, which is what its name means and
    which `Std_CastSpellEffect` spells out as a separate branch. *)
let cast_sound_of = function
  | Healing -> Some "snd_spellheal"
  | Necro -> Some "snd_spellalter"
  | Water -> Some "snd_spellalter"
  | Air -> Some "snd_spellbuff"
  | Frost -> Some "snd_spellalter"
  | Symbol -> Some "snd_spellalter"
  | Chaos -> Some "snd_spellfire"
  | Good -> Some "snd_spellbuff"
  | Stone -> Some "snd_spellnature"
  | Hide -> Some "snd_spellbuff"
  | War -> Some "snd_spellfire"
  | Nature -> Some "snd_spellnature"
  | Stun -> Some "snd_spelldebuff"
  | Fireball -> Some "snd_spellfire"
  | Hurlgoblin -> Some "snd_spellfire"
  | Poison -> Some "snd_spelldebuff"
  | Disease -> Some "snd_spelldebuff"
  | Web -> Some "snd_spelldebuff"
  | Fear -> Some "snd_spelldebuff"
  | Spin -> Some "snd_spellalter"
  | Sparkle -> Some "snd_spellbuff"
  | Default_Sound_Only -> Some "snd_spellnature"
  | Default -> Some "snd_spellnature"
  | Default_Gfx_Only -> None

(** The two effects `Std_CastSpellEffect` adds to the caster for [Default] and
    [Default_gfx_only]. The helper names them literally; they are assets too. *)
let default_caster_effects = [ "Spell0"; "Spell1" ]

type target = Caster | Enemy | Grid

type call = {
  target : target;  (** which end of the fight the helper aimed at *)
  fx : fx;
  use_sound : bool;
  (** The grid form compares its fourth argument `== 1`, so a truthy non-1 is
      silent. Transcribed as the comparison the file makes rather than as
      truthiness. *)
}

(** Every effect call in one spell's script, in the order the script makes them.

    A spell can ask for more than one: `SBAC` puts a war effect on the grid cell
    it just created and a default one on its own caster. Which *cell* is not
    here - that comes from the spell body, which is where the game gets it. *)
let calls_of_spell (id : string) : call list =
  match id with
  | "SARC" -> [ { target = Caster; fx = Air; use_sound = true } ]
  | "SBAC" -> [ { target = Grid; fx = War; use_sound = true }; { target = Caster; fx = Default_Gfx_Only; use_sound = false } ]
  | "SBAV" -> [ { target = Caster; fx = Necro; use_sound = true } ]
  | "SBLU" -> [ { target = Caster; fx = War; use_sound = true } ]
  | "SBNA" -> [ { target = Caster; fx = Symbol; use_sound = true } ]
  | "SBNE" -> [ { target = Caster; fx = Symbol; use_sound = true } ]
  | "SBNF" -> [ { target = Caster; fx = Symbol; use_sound = true } ]
  | "SBNW" -> [ { target = Caster; fx = Frost; use_sound = true } ]
  | "SBRA" -> [ { target = Caster; fx = War; use_sound = true } ]
  | "SBRF" -> [ { target = Caster; fx = Default_Gfx_Only; use_sound = false }; { target = Enemy; fx = Fireball; use_sound = true } ]
  | "SBRI" -> [ { target = Caster; fx = Frost; use_sound = true }; { target = Enemy; fx = Frost; use_sound = true } ]
  | "SBRL" -> [ { target = Caster; fx = Necro; use_sound = true } ]
  | "SBRP" -> [ { target = Caster; fx = Default_Gfx_Only; use_sound = false }; { target = Enemy; fx = Disease; use_sound = true } ]
  | "SBRZ" -> [ { target = Caster; fx = Default_Gfx_Only; use_sound = false }; { target = Enemy; fx = Poison; use_sound = true } ]
  | "SBSG" -> [ { target = Caster; fx = Default_Gfx_Only; use_sound = false }; { target = Grid; fx = Fireball; use_sound = true } ]
  | "SBST" -> [ { target = Caster; fx = Default_Gfx_Only; use_sound = false }; { target = Enemy; fx = Stun; use_sound = true } ]
  | "SBUR" -> [ { target = Caster; fx = Nature; use_sound = true } ]
  | "SCAU" -> [ { target = Caster; fx = Symbol; use_sound = true } ]
  | "SCBO" -> [ { target = Caster; fx = Hide; use_sound = true } ]
  | "SCHA" -> [ { target = Caster; fx = Air; use_sound = true } ]
  | "SCHE" -> [ { target = Caster; fx = Nature; use_sound = true } ]
  | "SCHF" -> [ { target = Caster; fx = Sparkle; use_sound = true } ]
  | "SCHL" -> [ { target = Caster; fx = Stun; use_sound = true }; { target = Enemy; fx = Stun; use_sound = true } ]
  | "SCHM" -> [ { target = Caster; fx = Healing; use_sound = true } ]
  | "SCHV" -> [ { target = Caster; fx = Good; use_sound = true }; { target = Enemy; fx = Good; use_sound = true } ]
  | "SCHW" -> [ { target = Caster; fx = Water; use_sound = true } ]
  | "SCLE" -> [ { target = Caster; fx = Good; use_sound = true } ]
  | "SCLM" -> [ { target = Caster; fx = Symbol; use_sound = true } ]
  | "SCLV" -> [ { target = Caster; fx = Spin; use_sound = true } ]
  | "SCMA" -> [ { target = Caster; fx = Hide; use_sound = true } ]
  | "SCON" -> [ { target = Caster; fx = Fireball; use_sound = true }; { target = Grid; fx = Fireball; use_sound = false }; { target = Grid; fx = Fireball; use_sound = false }; { target = Grid; fx = Fireball; use_sound = false } ]
  | "SCOU" -> [ { target = Caster; fx = Good; use_sound = true } ]
  | "SCTH" -> [ { target = Caster; fx = Healing; use_sound = true }; { target = Caster; fx = Sparkle; use_sound = true } ]
  | "SCTO" -> [ { target = Caster; fx = Water; use_sound = true }; { target = Enemy; fx = Frost; use_sound = true } ]
  | "SDBO" -> [ { target = Enemy; fx = Web; use_sound = true }; { target = Caster; fx = Sparkle; use_sound = true } ]
  | "SDBR" -> [ { target = Caster; fx = Necro; use_sound = true } ]
  | "SDDI" -> [ { target = Caster; fx = Air; use_sound = true }; { target = Enemy; fx = Air; use_sound = true } ]
  | "SDGZ" -> [ { target = Enemy; fx = Necro; use_sound = true } ]
  | "SDIV" -> [ { target = Caster; fx = Good; use_sound = true } ]
  | "SDRR" -> [ { target = Caster; fx = War; use_sound = true } ]
  | "SDST" -> [ { target = Caster; fx = Default_Gfx_Only; use_sound = false }; { target = Enemy; fx = Poison; use_sound = true } ]
  | "SDUP" -> [ { target = Caster; fx = Symbol; use_sound = true }; { target = Enemy; fx = Symbol; use_sound = true } ]
  | "SEGZ" -> [ { target = Caster; fx = Healing; use_sound = true } ]
  | "SENR" -> [ { target = Caster; fx = War; use_sound = true } ]
  | "SENT" -> [ { target = Enemy; fx = Web; use_sound = true }; { target = Caster; fx = Nature; use_sound = true } ]
  | "SEPO" -> [ { target = Caster; fx = Nature; use_sound = true } ]
  | "SESK" -> [ { target = Caster; fx = Necro; use_sound = true } ]
  | "SEVA" -> [ { target = Caster; fx = Water; use_sound = true } ]
  | "SFAV" -> [ { target = Caster; fx = Healing; use_sound = true } ]
  | "SFBA" -> [ { target = Caster; fx = Sparkle; use_sound = true } ]
  | "SFBM" -> [ { target = Enemy; fx = Fireball; use_sound = true } ]
  | "SFBO" -> [ { target = Caster; fx = Sparkle; use_sound = true } ]
  | "SFBT" -> [ { target = Enemy; fx = Frost; use_sound = true } ]
  | "SFCA" -> [ { target = Caster; fx = Fireball; use_sound = true } ]
  | "SFLV" -> [ { target = Caster; fx = Good; use_sound = true } ]
  | "SFOD" -> [ { target = Grid; fx = Necro; use_sound = true } ]
  | "SFOF" -> [ { target = Caster; fx = Sparkle; use_sound = true }; { target = Enemy; fx = Fireball; use_sound = true } ]
  | "SFRZ" -> [ { target = Caster; fx = Frost; use_sound = true } ]
  | "SFSH" -> [ { target = Caster; fx = Symbol; use_sound = true } ]
  | "SFSK" -> [ { target = Caster; fx = Necro; use_sound = true } ]
  | "SFSP" -> [ { target = Caster; fx = Healing; use_sound = true }; { target = Enemy; fx = Hide; use_sound = true } ]
  | "SGEM" -> [ { target = Caster; fx = Healing; use_sound = true } ]
  | "SGOW" -> [ { target = Caster; fx = Air; use_sound = true } ]
  | "SHAS" -> [ { target = Caster; fx = Nature; use_sound = true } ]
  | "SHBT" -> [ { target = Caster; fx = War; use_sound = true }; { target = Enemy; fx = Stun; use_sound = true } ]
  | "SHGO" -> [ { target = Grid; fx = Fireball; use_sound = true }; { target = Caster; fx = Default_Gfx_Only; use_sound = false } ]
  | "SHID" -> [ { target = Caster; fx = Hide; use_sound = true } ]
  | "SHOP" -> [ { target = Caster; fx = Symbol; use_sound = true } ]
  | "SHSI" -> [ { target = Enemy; fx = Hide; use_sound = true } ]
  | "SHWL" -> [ { target = Enemy; fx = Fear; use_sound = true }; { target = Caster; fx = Air; use_sound = true } ]
  | "SIST" -> [ { target = Caster; fx = War; use_sound = true } ]
  | "SKLO" -> [ { target = Caster; fx = Good; use_sound = true } ]
  | "SLCO" -> [ { target = Caster; fx = Symbol; use_sound = true } ]
  | "SLIG" -> [ { target = Caster; fx = Sparkle; use_sound = true } ]
  | "SMBU" -> [ { target = Caster; fx = Default_Gfx_Only; use_sound = false }; { target = Enemy; fx = Hide; use_sound = true } ]
  | "SMST" -> [ { target = Caster; fx = Stone; use_sound = true } ]
  | "SNWR" -> [ { target = Caster; fx = Nature; use_sound = true } ]
  | "SPAU" -> [ { target = Caster; fx = Symbol; use_sound = true } ]
  | "SPET" -> [ { target = Enemy; fx = Stone; use_sound = true }; { target = Caster; fx = Nature; use_sound = true } ]
  | "SPRO" -> [ { target = Caster; fx = Sparkle; use_sound = true } ]
  | "SRBI" -> [ { target = Enemy; fx = Disease; use_sound = true } ]
  | "SREV" -> [ { target = Caster; fx = Symbol; use_sound = true } ]
  | "SRFC" -> [ { target = Caster; fx = Good; use_sound = true } ]
  | "SRGN" -> [ { target = Caster; fx = Healing; use_sound = true } ]
  | "SRNC" -> [ { target = Caster; fx = Sparkle; use_sound = true } ]
  | "SRND" -> [ { target = Caster; fx = Sparkle; use_sound = true }; { target = Enemy; fx = War; use_sound = true } ]
  | "SROF" -> [ { target = Enemy; fx = Fireball; use_sound = true } ]
  | "SSAN" -> [ { target = Caster; fx = Water; use_sound = true } ]
  | "SSBD" -> [ { target = Caster; fx = Spin; use_sound = true } ]
  | "SSBL" -> [ { target = Enemy; fx = Spin; use_sound = true }; { target = Caster; fx = Spin; use_sound = true } ]
  | "SSBM" -> [ { target = Caster; fx = Water; use_sound = true }; { target = Enemy; fx = Hide; use_sound = true } ]
  | "SSCV" -> [ { target = Caster; fx = Sparkle; use_sound = true } ]
  | "SSGZ" -> [ { target = Caster; fx = Stone; use_sound = true } ]
  | "SSHO" -> [ { target = Grid; fx = Fear; use_sound = true }; { target = Enemy; fx = Hide; use_sound = true } ]
  | "SSNK" -> [ { target = Caster; fx = Chaos; use_sound = true }; { target = Enemy; fx = Chaos; use_sound = true } ]
  | "SSOA" -> [ { target = Caster; fx = Air; use_sound = true } ]
  | "SSOB" -> [ { target = Caster; fx = Necro; use_sound = true }; { target = Enemy; fx = War; use_sound = true } ]
  | "SSOS" -> [ { target = Caster; fx = Sparkle; use_sound = true }; { target = Enemy; fx = War; use_sound = true } ]
  | "SSPA" -> [ { target = Grid; fx = Spin; use_sound = true }; { target = Caster; fx = War; use_sound = true } ]
  | "SSPF" -> [ { target = Caster; fx = Necro; use_sound = true }; { target = Enemy; fx = Stun; use_sound = true } ]
  | "SSPT" -> [ { target = Caster; fx = War; use_sound = true }; { target = Enemy; fx = Poison; use_sound = true } ]
  | "SSSW" -> [ { target = Caster; fx = Symbol; use_sound = true }; { target = Enemy; fx = Symbol; use_sound = true } ]
  | "SSTL" -> [ { target = Caster; fx = Sparkle; use_sound = true }; { target = Enemy; fx = Hide; use_sound = true } ]
  | "SSTO" -> [ { target = Caster; fx = War; use_sound = true }; { target = Enemy; fx = Stun; use_sound = true } ]
  | "SSTU" -> [ { target = Grid; fx = Stone; use_sound = true }; { target = Enemy; fx = Stun; use_sound = true } ]
  | "SSWA" -> [ { target = Enemy; fx = Fear; use_sound = true } ]
  | "SSWM" -> [ { target = Caster; fx = Sparkle; use_sound = true }; { target = Caster; fx = Healing; use_sound = true } ]
  | "SSWP" -> [ { target = Caster; fx = Air; use_sound = true }; { target = Enemy; fx = Hide; use_sound = true } ]
  | "STAU" -> [ { target = Caster; fx = Chaos; use_sound = true }; { target = Enemy; fx = Hide; use_sound = true } ]
  | "STHR" -> [ { target = Grid; fx = War; use_sound = true } ]
  | "STHU" -> [ { target = Caster; fx = War; use_sound = true }; { target = Enemy; fx = Stone; use_sound = true } ]
  | "STHX" -> [ { target = Caster; fx = Spin; use_sound = true }; { target = Enemy; fx = Spin; use_sound = true } ]
  | "STRM" -> [ { target = Caster; fx = War; use_sound = true }; { target = Enemy; fx = Stone; use_sound = true } ]
  | "STWH" -> [ { target = Enemy; fx = Chaos; use_sound = true }; { target = Caster; fx = Spin; use_sound = true } ]
  | "SVAM" -> [ { target = Enemy; fx = Chaos; use_sound = true }; { target = Caster; fx = Healing; use_sound = true } ]
  | "SVIG" -> [ { target = Caster; fx = Symbol; use_sound = true } ]
  | "SWBU" -> [ { target = Caster; fx = Air; use_sound = true } ]
  | "SWEB" -> [ { target = Caster; fx = Nature; use_sound = true }; { target = Enemy; fx = Web; use_sound = true } ]
  | "SWHI" -> [ { target = Caster; fx = Air; use_sound = true } ]
  | "SWLO" -> [ { target = Caster; fx = Sparkle; use_sound = true } ]
  | "SWMG" -> [ { target = Grid; fx = Chaos; use_sound = false }; { target = Caster; fx = Chaos; use_sound = true } ]
  | "SWOF" -> [ { target = Caster; fx = Fireball; use_sound = true } ]
  | "SWOP" -> [ { target = Caster; fx = Symbol; use_sound = true } ]
  | "SWOT" -> [ { target = Caster; fx = Nature; use_sound = true }; { target = Caster; fx = Symbol; use_sound = true } ]
  | "SWTD" -> [ { target = Grid; fx = Necro; use_sound = false }; { target = Caster; fx = Necro; use_sound = true } ]
  | "SZAP" -> [ { target = Caster; fx = Sparkle; use_sound = true }; { target = Enemy; fx = Sparkle; use_sound = true } ]
  | _ -> []

