(** Generated by tools/extract_status_effects.ps1. Do not edit by hand.

    The status effect descriptors, parsed from [Assets/StatusEffects/*.xml]:
    the id, the icon, [Data duration] and [Data stack], and the companion
    script's file and object name.

    [id] is the identity the engine uses. It is {e not} [name]: the Lua tables
    are called Hidden and WallOfFired, but the constants in
    [Assets/Scripts/StandardConstants.lua] are string aliases for the ids -

        STATUS_EFFECT_HIDDEN = "EHID";

    and every [HAS_STATUS_EFFECT] and [ADD_STATUS_EFFECT] comparison is against
    that string. Nothing in the game ever compares a script name. So the ids
    are what [Combatant.effects] must hold, and [name] is kept only so a log
    line or a test can read as English.

    Three of these have [duration = 0], which is not "expired immediately" but
    "indefinite": Hidden, WallOfFired and WallOfThornsed each cancel themselves
    by setting their own remaining duration to 1, which lapses on the next
    tick. Spells that apply them pass 0 as well, so the two agree. This is
    [Combat.tick_duration]'s first branch, [if (duration < 1) return 1].

    Every [hooks] here is [no_hooks]. The behaviour lives in the companion
    .lua and is hand-ported into [Status_effect_hooks], which is what
    [Status_effect_hooks.descriptors] is for - it maps over this list and
    attaches the bodies. Keeping generation independent of the port means a
    transcription mistake cannot corrupt the data half. *)

open Combat

let descriptors : effect_def list = [
  { id = "EBLI"; name = "Blinded"; duration = 5; stack = 1; icon = 3;
    script = "Blinded.lua"; hooks = no_hooks };
  { id = "ECHA"; name = "Challenged"; duration = 6; stack = 1; icon = 17;
    script = "Challenged.lua"; hooks = no_hooks };
  { id = "EDIS"; name = "Disease"; duration = 6; stack = 4; icon = 1;
    script = "Disease.lua"; hooks = no_hooks };
  { id = "EENR"; name = "Enraged"; duration = 8; stack = 1; icon = 16;
    script = "Enraged.lua"; hooks = no_hooks };
  { id = "EFAV"; name = "Favored"; duration = 8; stack = 1; icon = 18;
    script = "Favored.lua"; hooks = no_hooks };
  { id = "EFBO"; name = "FireBombed"; duration = 12; stack = 4; icon = 4;
    script = "FireBombed.lua"; hooks = no_hooks };
  { id = "EFEA"; name = "Fear"; duration = 6; stack = 1; icon = 2;
    script = "Fear.lua"; hooks = no_hooks };
  { id = "EFSH"; name = "FireShielded"; duration = 8; stack = 1; icon = 24;
    script = "FireShielded.lua"; hooks = no_hooks };
  { id = "EHAS"; name = "Hasted"; duration = 8; stack = 1; icon = 23;
    script = "Hasted.lua"; hooks = no_hooks };
  { id = "EHID"; name = "Hidden"; duration = 0; stack = 1; icon = 25;
    script = "Hidden.lua"; hooks = no_hooks };
  { id = "EHOP"; name = "HandOfPowered"; duration = 6; stack = 2; icon = 21;
    script = "HandOfPowered.lua"; hooks = no_hooks };
  { id = "EPAU"; name = "PaladinsAuraed"; duration = 10; stack = 1; icon = 26;
    script = "PaladinsAuraed.lua"; hooks = no_hooks };
  { id = "EPOI"; name = "Poison"; duration = 6; stack = 4; icon = 0;
    script = "Poison.lua"; hooks = no_hooks };
  { id = "ESBL"; name = "SingingBladesed"; duration = 5; stack = 1; icon = 27;
    script = "SingingBladesed.lua"; hooks = no_hooks };
  { id = "EVIG"; name = "Vigiled"; duration = 10; stack = 1; icon = 19;
    script = "Vigiled.lua"; hooks = no_hooks };
  { id = "EWOF"; name = "WallOfFired"; duration = 0; stack = 1; icon = 22;
    script = "WallOfFired.lua"; hooks = no_hooks };
  { id = "EWOT"; name = "WallOfThornsed"; duration = 0; stack = 1; icon = 20;
    script = "WallOfThornsed.lua"; hooks = no_hooks };
]

let descriptor_of (id : string) : effect_def option =
  List.find_opt (fun (d : effect_def) -> d.id = id) descriptors

(** The Lua table name for an id, for logs and failure messages. [None] for an
    id that is not one of the seventeen, which includes the model's own
    [Missed] pseudo-status - see [Combat.miss_turns]. *)
let name_of (id : string) : string option =
  List.find_opt (fun (d : effect_def) -> d.id = id) descriptors
  |> Option.map (fun (d : effect_def) -> d.name)
