#!/usr/bin/env python3
"""Generate lib/font_data.ml from the bitmap fonts in game/Assets.zip.

The game ships its own fonts, so there is no font pipeline here and nothing to
infer about glyph shapes. Two different XML schemas are involved and they are not
interchangeable:

  Assets/Fonts/<Face>.xml   the *glyph* table. <FontData height numchars mincode
                            maxcode> plus one <Glyph code x y width height
                            leading trailing/> per character. Ten faces, 195-199
                            characters each, codes 32..8482 - the range is
                            multilingual, not ASCII.

  <Language>/Font.xml        the *style* table. 32 named logical fonts, each
                            pointing at a face with pointsize, baseline,
                            lineheight, scale and an RGB colour. This is where
                            font_xp being purple and font_gold being orange comes
                            from; the colour is part of the font definition, which
                            is why the original's damage numbers are coloured.

Both are read straight out of the archive. Note that neither "leading" nor
"trailing" nor "numchars" appears anywhere in the binary, so the engine does not
parse these files at runtime - they are build-time metadata describing a glyph
table the asset pipeline precomputed. That is why the per-glyph *advance* is a
question rather than a fact here; see gfx/font_layout.ml.

    python tools/extract_fonts.py
    python tools/extract_fonts.py --language German
    python tools/extract_fonts.py --check     # verify the checked-in file is current

The generated module is committed, like lib/spell_data.ml, so that building the
project does not require the archive.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
import xml.etree.ElementTree as ET
import zipfile

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "lib" / "font_data.ml"

FONT_DIR = "Assets/Fonts"


def face_name(path: str) -> str:
    """Assets\\Fonts\\System -> System. The style table spells paths with
    backslashes and no extension; the glyph tables are addressed by bare face
    name, so both have to arrive at the same string for a style to find its
    face."""
    return path.replace("\\", "/").rsplit("/", 1)[-1].removesuffix(".xml")


def parse_faces(z: zipfile.ZipFile) -> list[tuple[str, ET.Element, list[ET.Element]]]:
    names = sorted(n for n in z.namelist()
                   if n.startswith(FONT_DIR + "/") and n.endswith(".xml"))
    out = []
    for n in names:
        root = ET.fromstring(z.read(n))
        if root.tag != "FontData":
            continue
        glyphs = list(root.findall("Glyph"))
        out.append((face_name(n), root, glyphs))
    return out


def parse_styles(z: zipfile.ZipFile, language: str) -> list[ET.Element]:
    root = ET.fromstring(z.read(f"{language}/Font.xml"))
    return list(root.findall("Font"))


def attrs(el: ET.Element) -> dict[str, str]:
    return {k: v for k, v in el.attrib.items()}


def ocaml_int(s: str | None, default: int = 0) -> int:
    if s is None:
        return default
    return int(s)


def render(faces, styles) -> str:
    L: list[str] = []
    w = L.append

    w("(* Generated by tools/extract_fonts.py from game/Assets.zip. Do not edit.")
    w("")
    w("   Two tables, from two different files in the game's asset tree:")
    w("")
    w("   - a [face] per Assets/Fonts/<Face>.xml: the packed atlas' glyph table,")
    w("     with each character's rectangle and its two side bearings;")
    w("   - a [style] per <Language>/Font.xml: a {e named} font - a face plus a")
    w("     baseline, a line height and a colour. Thirty-two of them, and they are")
    w("     the whole text vocabulary of the game, damage-number colours included.")
    w("")
    w("   Nothing here computes an advance. The three numbers a glyph table gives")
    w("   per character are its rectangle and its leading and trailing bearings;")
    w("   how the engine turns those into a pen movement is in gfx/font_layout.ml,")
    w("   which is where the open question about it lives. *)\n")
    w("type glyph = {")
    w("  code : int;")
    w("  x : int;")
    w("  y : int;")
    w("  w : int;")
    w("  h : int;")
    w("  leading : int;")
    w("  trailing : int;")
    w("}\n")
    w("type face = {")
    w("  name : string;")
    w("  height : int;  (** the FontData/@height: the face's line height *)")
    w("  mincode : int;")
    w("  maxcode : int;")
    w("  glyphs : glyph array;  (** sorted by [code], for binary search *)")
    w("}\n")
    w("type style = {")
    w("  id : int;")
    w("  tag : string;")
    w("  face : string;")
    w("  pointsize : int;")
    w("  baseline : int;")
    w("  lineheight : int;  (** 0 in several faces: fall back to the face's own *)")
    w("  scale : int;")
    w("  yoffset : int;")
    w("  r : int;")
    w("  g : int;")
    w("  b : int;")
    w("  a : int;")
    w("}\n")

    # ---- faces ----
    w("let faces : face array =")
    w("  [|")
    for name, root, glyphs in faces:
        a = attrs(root)
        w(f"    (* {len(glyphs)} characters, codes {a['mincode']}..{a['maxcode']} *)")
        w(f"    {{ name = {name!r};".replace("'", '"'))
        w(f"      height = {a['height']};")
        w(f"      mincode = {a['mincode']};")
        w(f"      maxcode = {a['maxcode']};")
        w("      glyphs =")
        w("        [|")
        for g in sorted(glyphs, key=lambda e: int(attrs(e)["code"])):
            ga = attrs(g)
            w("            { code = %s; x = %s; y = %s; w = %s; h = %s; "
              "leading = %s; trailing = %s };"
              % (ga["code"], ga["x"], ga["y"], ga["width"], ga["height"],
                 ga["leading"], ga["trailing"]))
        w("        |];")
        w("    };")
    w("  |]\n")

    w("""let face_of_name (name : string) : face option =
  let rec go = function
    | [] -> None
    | f :: rest -> if f.name = name then Some f else go rest
  in
  go (Array.to_list faces)

(** The glyph for a character code, or [None] when the face has none.

    The archive's own sentinel for "no glyph" is an all-zero rectangle, and
    FUN_004c75e0 tests exactly that - see the note in gfx/font_layout.ml. Codes
    outside [mincode], [maxcode] have no glyph either, and both cases are [None]
    here because the caller's correct answer to both is the same: draw the
    fallback, or draw nothing. *)
let glyph_of_code (f : face) (code : int) : glyph option =
  if code < f.mincode || code > f.maxcode then None
  else begin
    let g = f.glyphs in
    let lo = ref 0 and hi = ref (Array.length g - 1) in
    let found = ref None in
    while !lo <= !hi && !found = None do
      let mid = (!lo + !hi) / 2 in
      if g.(mid).code = code then found := Some g.(mid)
      else if g.(mid).code < code then lo := mid + 1
      else hi := mid - 1
    done;
    match !found with
    | Some ({ w = 0; x = 0; y = 0; _ } as gl) -> Some gl
    | other -> other
  end
""")

    # ---- styles ----
    w("let styles : style array =")
    w("  [|")
    for s in styles:
        a = attrs(s)
        face = face_name(a["file"])
        w(f"    {{ id = {a['id']}; tag = {a['tag']!r};".replace("'", '"'))
        w(f"      face = {face!r};".replace("'", '"'))
        w(f"      pointsize = {a['pointsize']};")
        w(f"      baseline = {a['baseline']};")
        w(f"      lineheight = {a.get('lineheight', '0')};")
        w(f"      scale = {ocaml_int(a.get('scale'), 1)};")
        w(f"      yoffset = {ocaml_int(a.get('yoffset'), 0)};")
        w(f"      r = {a['r']}; g = {a['g']}; b = {a['b']}; a = {a['a']} }};")
    w("  |]\n")

    w("""let style_of_tag (tag : string) : style option =
  let rec go = function
    | [] -> None
    | s :: rest -> if s.tag = tag then Some s else go rest
  in
  go (Array.to_list styles)

(** The line height to stack lines by.

    Six of the thirty-two styles carry lineheight="0", which cannot mean zero:
    font_heading, font_msg_* and the script faces all do, and their FontData
    heights are 45, 43 and 43. So 0 falls back to the face's own height, which is
    the same field FUN_004c9030 reads for a one-line measurement. *)
let line_height (s : style) : int =
  if s.lineheight > 0 then s.lineheight
  else match face_of_name s.face with Some f -> f.height | None -> 0
""")
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--zip", type=pathlib.Path, default=REPO / "game" / "Assets.zip")
    ap.add_argument("--language", default="English",
                    help="whose Font.xml to read the named styles from")
    ap.add_argument("--out", type=pathlib.Path, default=OUT)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed file differs")
    args = ap.parse_args()

    if not args.zip.is_file():
        print(f"error: {args.zip} not found", file=sys.stderr)
        return 1
    try:
        with zipfile.ZipFile(args.zip) as z:
            faces = parse_faces(z)
            styles = parse_styles(z, args.language)
    except (zipfile.BadZipFile, KeyError, ET.ParseError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    if not faces or not styles:
        print("error: found no font faces or no styles", file=sys.stderr)
        return 1

    total = sum(len(g) for _, _, g in faces)
    print(f"  {len(faces)} faces, {total} glyphs, {len(styles)} named styles")

    text = render(faces, styles)

    if args.check:
        if not args.out.is_file():
            print(f"error: {args.out} missing", file=sys.stderr)
            return 1
        if args.out.read_text(encoding="utf-8") != text:
            print(f"error: {args.out} is stale, re-run tools/extract_fonts.py",
                  file=sys.stderr)
            return 1
        print("  up to date")
        return 0

    args.out.write_text(text, encoding="utf-8")
    print(f"  wrote {args.out} ({len(text):,d} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())