#!/usr/bin/env python3
"""
Extract Encounters: XML metadata + Lua scripts.
Generates lib/campaign_encounters.ml
"""

import xml.etree.ElementTree as ET
from pathlib import Path
import sys

BASE = Path("game/Assets/Assets/Encounters")

def parse_encounter(xml_path):
    tree = ET.parse(xml_path)
    root = tree.getroot()
    eid = root.get("id")
    desc = root.find("Description")
    location = root.find("Location")
    sprite = root.find("Sprite")
    script = root.find("Script")
    lua_path = BASE / script.get("file").replace("\\", "/") if script is not None else None
    lua_source = lua_path.read_text(encoding="utf-8") if lua_path and lua_path.exists() else ""

    # Parse Lua source for myLevel and PERCENTILE_CHANCE
    my_level = 1
    chance = 2
    try:
        import re
        m = re.search(r'myLevel\s*=\s*(\d+)', lua_source)
        if m:
            my_level = int(m.group(1))
        m = re.search(r'PERCENTILE_CHANCE\(\)\s*<=\s*(\d+)', lua_source)
        if m:
            chance = int(m.group(1))
    except:
        pass

    return {
        "id": eid,
        "description": desc.get("text") if desc is not None else "",
        "start": location.get("start") if location is not None else "",
        "end_": location.get("end") if location is not None else "",
        "index": int(location.get("index")) if location is not None else 0,
        "sprite": sprite.get("id") if sprite is not None else "",
        "lua_file": script.get("file") if script is not None else "",
        "lua_object": script.get("object") if script is not None else "",
        "my_level": my_level,
        "chance": chance,
    }

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", default="lib/campaign_encounters.ml")
    args = parser.parse_args()

    encounters = []
    for xml in sorted(BASE.glob("E*.xml")):
        encounters.append(parse_encounter(xml))

    if args.check:
        print(f"Encounters: {len(encounters)}")
        for e in encounters:
            print(f"  {e['id']}: {e['description']} on {e['start']}->{e['end_']}[{e['index']}] sprite={e['sprite']} lua={e['lua_object']}")
        return

    lines = []
    lines.append("(* Generated by tools/extract_encounters.py — do not edit *)")
    lines.append("")
    lines.append("type encounter = {")
    lines.append("  id: string;")
    lines.append("  description: string;")
    lines.append("  start: string;")
    lines.append("  end_: string;")
    lines.append("  index: int;")
    lines.append("  sprite: string;")
    lines.append("  lua_file: string;")
    lines.append("  lua_object: string;")
    lines.append("  my_level: int;")
    lines.append("  chance: int;")
    lines.append("}")
    lines.append("")

    lines.append("let encounters = [")
    for e in encounters:
        lua_escaped = ""
        lines.append("  {")
        lines.append(f'    id = "{e["id"]}";')
        lines.append(f'    description = "{e["description"]}";')
        lines.append(f'    start = "{e["start"]}";')
        lines.append(f'    end_ = "{e["end_"]}";')
        lines.append(f'    index = {e["index"]};')
        lines.append(f'    sprite = "{e["sprite"]}";')
        lines.append(f'    lua_file = "{e["lua_file"].replace(chr(92), chr(92)+chr(92))}";')
        lines.append(f'    lua_object = "{e["lua_object"]}";')
        lines.append(f'    my_level = {e["my_level"]};')
        lines.append(f'    chance = {e["chance"]};')
        lines.append("  };")
    lines.append("]")
    lines.append("")

    lines.append("let encounter_by_id id = List.find (fun e -> e.id = id) encounters")
    lines.append("let encounters_on_road start end_ =")
    lines.append("  List.filter (fun e -> e.start = start && e.end_ = end_) encounters")
    lines.append("")

    Path(args.output).write_text("\n".join(lines))
    print(f"Wrote {args.output}")

if __name__ == "__main__":
    main()