#!/usr/bin/env python3
"""
Extract Conversations: XML + localized text.
Generates lib/campaign_conversations.ml
"""

import xml.etree.ElementTree as ET
from pathlib import Path

BASE = Path("game/Assets/Assets/Conversations")
TEXT_BASE = Path("game/Assets/English/Conversations")


def parse_conv_text(xml_path):
    if not xml_path.exists():
        return {}
    tree = ET.parse(xml_path)
    root = tree.getroot()
    texts = {}
    for text_elem in root.findall("Text"):
        tag = text_elem.get("tag")
        content = text_elem.text or ""
        texts[tag] = content
    return texts


def parse_conversation(xml_path):
    tree = ET.parse(xml_path)
    root = tree.getroot()

    desc = root.find("Description")
    text_elem = root.find("Text")
    backdrop = root.find("Backdrop")
    characters = root.findall("Character")
    actions = root.findall("Actions/Action")

    text_file = text_elem.get("file") if text_elem is not None else None
    texts = parse_conv_text(TEXT_BASE / text_file) if text_file else {}

    chars = []
    for c in characters:
        chars.append({
            "index": int(c.get("index")),
            "type": c.get("type"),
            "portrait": c.get("portrait", ""),
            "portraitindex": int(c.get("portraitindex")) if c.get("portraitindex") is not None else 0,
            "name": c.get("name", ""),
        })

    acts = []
    for a in actions:
        act = {
            "type": a.get("type"),
            "character": int(a.get("character")) if a.get("character") is not None else -1,
            "text": a.get("text", ""),
        }
        if a.get("type") == "scriptcall":
            act["object"] = a.get("object", "")
            act["function"] = a.get("function", "")
        acts.append(act)

    return {
        "id": xml_path.stem,
        "description": desc.get("text") if desc is not None else "",
        "text_file": text_file if text_file else "",
        "texts": texts,
        "backdrop": backdrop.get("file") if backdrop is not None else "",
        "characters": chars,
        "actions": acts,
    }


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", default="lib/campaign_conversations.ml")
    args = parser.parse_args()

    conversations = []
    for xml in sorted(BASE.glob("Conv_*.xml")):
        conversations.append(parse_conversation(xml))

    if args.check:
        print(f"Conversations: {len(conversations)}")
        for c in conversations:
            print(f"  {c['id']}: {c['description']} backdrop={c['backdrop']} chars={len(c['characters'])} actions={len(c['actions'])}")
        return

    lines = []
    lines.append("(* Generated by tools/extract_conversations.py — do not edit *)")
    lines.append("")
    lines.append("type conv_character = {")
    lines.append("  index: int;")
    lines.append("  type_: string;")
    lines.append("  portrait: string;")
    lines.append("  portraitindex: int;")
    lines.append("  name: string;")
    lines.append("}")
    lines.append("")
    lines.append("type conv_action = {")
    lines.append("  type_: string;")
    lines.append("  character: int;")
    lines.append("  text: string;")
    lines.append("  scriptcall_object: string option;")
    lines.append("  scriptcall_function: string option;")
    lines.append("}")
    lines.append("")
    lines.append("type conversation = {")
    lines.append("  id: string;")
    lines.append("  description: string;")
    lines.append("  text_file: string;")
    lines.append("  texts: (string * string) list;")
    lines.append("  backdrop: string;")
    lines.append("  characters: conv_character list;")
    lines.append("  actions: conv_action list;")
    lines.append("}")
    lines.append("")

    lines.append("let conversations = [")
    for c in conversations:
        texts_list = "[" + "; ".join([f'("{k}", "{v.replace("\\", "\\\\").replace(chr(34), chr(92)+chr(34)).replace(chr(10), "\\n")}")' for k, v in c["texts"].items()]) + "]"
        lines.append("  {")
        lines.append(f'    id = "{c["id"]}";')
        lines.append(f'    description = "{c["description"]}";')
        lines.append(f'    text_file = "{c["text_file"].replace(chr(92), chr(92)+chr(92))}";')
        lines.append(f"    texts = {texts_list};")
        lines.append(f'    backdrop = "{c["backdrop"].replace(chr(92), chr(92)+chr(92))}";')
        lines.append("    characters = [")
        for ch in c["characters"]:
            lines.append("      {")
            lines.append(f'        index = {ch["index"]};')
            lines.append(f'        type_ = "{ch["type"]}";')
            lines.append(f'        portrait = "{ch["portrait"].replace(chr(92), chr(92)+chr(92))}";')
            lines.append(f'        portraitindex = {ch["portraitindex"]};')
            lines.append(f'        name = "{ch["name"]}";')
            lines.append("      };")
        lines.append("    ];")
        lines.append("    actions = [")
        for a in c["actions"]:
            lines.append("      {")
            lines.append(f'        type_ = "{a["type"]}";')
            lines.append(f'        character = {a["character"]};')
            lines.append(f'        text = "{a["text"]}";')
            if a["type"] == "scriptcall":
                lines.append(f'        scriptcall_object = Some "{a["object"]}";')
                lines.append(f'        scriptcall_function = Some "{a["function"]}";')
            else:
                lines.append("        scriptcall_object = None;")
                lines.append("        scriptcall_function = None;")
            lines.append("      };")
        lines.append("    ];")
        lines.append("  };")
    lines.append("]")
    lines.append("")

    lines.append("let conversation_by_id id = List.find (fun c -> c.id = id) conversations")
    lines.append("")

    Path(args.output).write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()