$ErrorActionPreference = 'Stop'

# Regenerates lib/spell_data.ml from the game's own assets.
#
# Two sources:
#   * Assets/Spells/*.xml            costs, cooldown, learn requirements, input
#   * English/StandardSpellsText.xml the DETL line, which is where the game
#                                    states whether casting ends your turn
#
# The turn rule has no field in the XML. The game states it in each spell's own
# description, so the localisation table is the authoritative record and the turn
# cost is transcribed from it rather than inferred.

$assets = 'game\Assets.zip'
if (-not (Test-Path $assets)) { throw "missing $assets" }

Add-Type -AssemblyName System.IO.Compression.FileSystem
$z = [System.IO.Compression.ZipFile]::OpenRead($assets)

function Read-Entry($zip, $name) {
  $e = $zip.Entries | Where-Object { $_.FullName -eq $name }
  if (-not $e) { return $null }
  $sr = New-Object System.IO.StreamReader($e.Open())
  $t = $sr.ReadToEnd()
  $sr.Close()
  return $t
}

function Attr($xml, $tag, $attr) {
  $m = [regex]::Match($xml, ('<' + $tag + '\b[^>]*\b' + $attr + '="([^"]*)"'))
  if ($m.Success) { return $m.Groups[1].Value }
  return $null
}

$localised = Read-Entry $z 'English/StandardSpellsText.xml'
$detl = @{}
foreach ($m in [regex]::Matches($localised, '<Text tag="\[(SPELL_[A-Z0-9]+)_DETL\]">([^<]*)</Text>')) {
  $detl[$m.Groups[1].Value] = $m.Groups[2].Value
}

# Game colour names -> engine elements. Earth is green, Fire red, Air yellow,
# Water blue.
$elem = @{ 'Red' = 'Fire'; 'Yellow' = 'Air'; 'Blue' = 'Water'; 'Green' = 'Earth' }

$entries = @{}
foreach ($e in $z.Entries) {
  if ($e.FullName -match '^Assets/Spells/(S[A-Z0-9]+)\.xml$') {
    $id = $Matches[1]
    # SARC is the spell-research mini-game descriptor, not a battle spell.
    if ($id -eq 'SARC') { continue }
    $sr = New-Object System.IO.StreamReader($e.Open())
    $xml = $sr.ReadToEnd()
    $sr.Close()

    $costXml = [regex]::Match($xml, '<Cost\b[^>]*/>').Value
    $learnXml = [regex]::Match($xml, '<Learn\b[^>]*/>').Value
    $dataXml = [regex]::Match($xml, '<Data\b[^>]*/>').Value
    $inputXml = [regex]::Match($xml, '<Input\b[^>]*/>').Value

    $cost = @{
      earth = [int](Attr $costXml 'Cost' 'earth'); fire = [int](Attr $costXml 'Cost' 'fire')
      air = [int](Attr $costXml 'Cost' 'air');   water = [int](Attr $costXml 'Cost' 'water')
    }
    $learn = @{
      score = [int](Attr $learnXml 'Learn' 'score'); masks = [int](Attr $learnXml 'Learn' 'masks')
      keys = [int](Attr $learnXml 'Learn' 'keys')
    }
    $cd = [int](Attr $dataXml 'Data' 'cooldown')

    # Input types: none, column, row, grid.
    $inputType = switch -Regex ($inputXml) {
      'none'   { 0 }
      'column' { 1 }
      'row'    { 2 }
      'grid'   { 3 }
      default  { 0 }
    }

    # Turn cost, from the DETL line.
    $tc = 'EndsTurn'
    $key = 'SPELL_' + $id
    if ($detl.ContainsKey($key)) {
      $d = $detl[$key]
      # The conditional form must be tested first: "Your turn does not end if Red
      # Mana is 15+" also contains the substring "Your turn does not end".
      if ($d -match 'Your turn does not end if (\w+) [Mm]ana is (\d+)') {
        $tc = 'KeepsTurnIfMana (' + $elem[$Matches[1]] + ', ' + $Matches[2] + ')'
      } elseif ($d -match 'turn does not end after casting' -or $d -match 'Your turn does not end' -or $d -match 'Does not end your turn') {
        $tc = 'KeepsTurn'
      } elseif ($d -match 'the turn ends') {
        $tc = 'EndsTurnAfterEffect'
      }
    }

    $entries[$id] = [pscustomobject]@{
      id = $id; cost = $cost; learn = $learn; cooldown = $cd
      input = $inputType; turn = $tc
    }
  }
}
$z.Dispose()

$ids = $entries.Keys | Sort-Object

$rows = New-Object System.Collections.Generic.List[string]
foreach ($id in $ids) {
  $d = $entries[$id]
  $rows.Add(('  {{ id = "{0}"; cost_earth = {1}; cost_fire = {2}; cost_air = {3}; cost_water = {4};' -f `
    $d.id, $d.cost.earth, $d.cost.fire, $d.cost.air, $d.cost.water))
  $rows.Add(('    cooldown = {0}; learn_score = {1}; learn_masks = {2}; learn_keys = {3};' -f `
    $d.cooldown, $d.learn.score, $d.learn.masks, $d.learn.keys))
  $rows.Add(('    input_type = {0}; turn_cost = Spell.{1} }};' -f $d.input, $d.turn))
}

$hdr = @(
  '(** Generated by tools/extract_spell_data.ps1. Do not edit by hand.'
  ''
  '    The real spell table, parsed from the game''s own assets:'
  ''
  '    * [Assets/Spells/*.xml] for the four costs, [Data cooldown], the [Learn]'
  '      requirements, and the [Input] type.'
  '    * [English/StandardSpellsText.xml] for the turn rule, which has no field in'
  '      the XML. The game states it in each spell''s own DETL line, so that is'
  '      transcribed rather than inferred. Breakdowns:'
  ''
  '      - [Spell.EndsTurn], the default, is 97 of the 129: no turn clause at all.'
  '      - [Spell.KeepsTurn] is 13, from "Your turn does not end".'
  '      - [Spell.EndsTurnAfterEffect] is 10, from "the turn ends".'
  '      - [Spell.KeepsTurnIfMana] is 9, from "Your turn does not end if COLOUR'
  '        Mana is N+", colour mapped to the engine element: Earth green, Fire'
  '        red, Air yellow, Water blue.'
  ''
  '    Casting usually ends the turn, so the caster does not also swap that turn.'
  '    Only the minority hand it back. That is the opposite of what the battle'
  '    loop first assumed.'
  ''
  '    SARC is excluded: it is the spell-research mini-game descriptor rather than'
  '    a battle spell. *)'
  ''
  'let spell_descriptors : Spell.descriptor list = ['
)
$tail = @(
  ']'
  ''
  'let descriptor_of (id : string) : Spell.descriptor option ='
  '  List.find_opt (fun (d : Spell.descriptor) -> d.id = id) spell_descriptors'
)
$all = @($hdr) + @($rows) + @($tail)
$path = 'lib\spell_data.ml'
[System.IO.File]::WriteAllLines((Join-Path (Get-Location) $path), $all, (New-Object System.Text.UTF8Encoding($false)))

$tc = @{}
foreach ($id in $ids) { $k = $entries[$id].turn; if ($tc.ContainsKey($k)) { $tc[$k] = $tc[$k] + 1 } else { $tc[$k] = 1 } }
$cdCount = ($ids | Where-Object { $entries[$_].cooldown -gt 0 }).Count

Write-Output ('wrote {0} with {1} spells' -f $path, $ids.Count)
Write-Output ('spells with a cooldown: {0}' -f $cdCount)
Write-Output ''
$tc.GetEnumerator() | Sort-Object Value -Descending | ForEach-Object {
  Write-Output ('{0,4}  {1}' -f $_.Value, $_.Key)
}