#!/usr/bin/env python3
"""Generate lib/skin_data.ml from the game's own bitmap registry.

`Assets/Assets.xml` is the WET engine's asset registry, and it has two halves that
matter here:

  <Bitmap tag="..." >path</Bitmap>       a sheet: a tag and the image behind it
  <BitmapImage tag="..." bitmap="..."    a named rectangle inside a sheet, with
      x y width height destwidth destheight/>

422 named rectangles across the sheets, which is the whole decoration vocabulary
of the game: the backdrop and its border, the selection glow, the turn-timer
backgrounds, button states, cursor art, dialog furniture. Everything the
presentation layer draws should come from here rather than from coordinates
somebody eyeballed off a PNG.

This is the same discipline `gfx/assets.ml` applies to the gem sheet, promoted to
the general case - and it has an immediate payoff: the four gem frames the port
hardcodes can be *checked* against the registry instead of trusted.

Note the paths use backslashes (`Assets\\Skin\\Skin_Gems_Grid.png`) while the
archive uses forward slashes, and the tag is not always the file's name, so both
are normalised here rather than at each use.

    python tools/extract_skin_data.py
    python tools/extract_skin_data.py --check     # verify the committed file is current
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
import xml.etree.ElementTree as ET
import zipfile

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "lib" / "skin_data.ml"
REGISTRY = "Assets/Assets.xml"

SHEET_RE = re.compile(r'<Bitmap\s+tag="([^"]+)"[^>]*>([^<]+)</Bitmap>')
FRAME_RE = re.compile(r"<BitmapImage\s+([^/]*?)/>")


def attrs(s: str) -> dict[str, str]:
    return dict(re.findall(r'(\w+)="([^"]*)"', s))


def normalise(path: str) -> str:
    """`Assets\\Skin\\Skin_Gems_Grid.png` -> `Assets/Skin/Skin_Gems_Grid`.

    The extension goes too, because the caller pairs this with the image decoder
    and there are two JPGs in the tree that differ only by directory."""
    p = path.strip().replace("\\", "/")
    for ext in (".png", ".jpg", ".jpeg"):
        if p.lower().endswith(ext):
            return p[: -len(ext)]
    return p


def ocaml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(sheets: list[tuple[str, str]], frames: list[dict[str, str]]) -> str:
    L: list[str] = []
    w = L.append

    w("(* Generated by tools/extract_skin_data.py from game/Assets.zip. Do not edit.")
    w("")
    w("   The game's own bitmap registry, Assets/Assets.xml, in two parts:")
    w("")
    w("   - a [sheet]: a tag and the image behind it;")
    w("   - a [frame]: a named rectangle inside a sheet, with the size it is meant")
    w("     to be *drawn* at as well as the size it is stored at.")
    w("")
    w("   422 named frames. This is the decoration vocabulary of the whole game - the")
    w("   backdrop and its border, the selection glow, the turn-timer backgrounds,")
    w("   button states, dialog furniture - so a renderer should look tags up here")
    w("   rather than carry coordinates of its own. The gem frames the port needs are")
    w("   in this table too, which means [test_skin_data] can check the port's gem")
    w("   coordinates against the registry instead of trusting them.")
    w("")
    w("   [dest_w] and [dest_h] are worth keeping: several frames are stored larger")
    w("   than they are drawn, the red glow frames being 88x88 on disk for 64x64 on")
    w("   screen, so the registry is the only place that knows to scale them. *)\n")
    w("type sheet = { tag : string; file : string }  (** no extension: see the note in the generator *)\n")
    w("type frame = {")
    w("  tag : string;")
    w("  sheet : string;")
    w("  x : int;")
    w("  y : int;")
    w("  w : int;")
    w("  h : int;")
    w("  dest_w : int;")
    w("  dest_h : int;")
    w("}\n")

    w("let sheets : sheet array =")
    w("  [|")
    for tag, path in sheets:
        w(f"    {{ tag = {ocaml_str(tag)}; file = {ocaml_str(normalise(path))} }};")
    w("  |]\n")

    w("""let sheet_of_tag (tag : string) : sheet option =
  let rec go (l : sheet list) =
    match l with
    | [] -> None
    | (s : sheet) :: rest -> if s.tag = tag then Some s else go rest
  in
  go (Array.to_list sheets)

let frames : frame array =""")
    w("  [|")
    for f in frames:
        w(
            "    { tag = %s; sheet = %s; x = %s; y = %s; w = %s; h = %s; dest_w = %s; dest_h = %s };"
            % (
                ocaml_str(f["tag"]),
                ocaml_str(f["bitmap"]),
                f["x"],
                f["y"],
                f["width"],
                f["height"],
                f.get("destwidth", f["width"]),
                f.get("destheight", f["height"]),
            )
        )
    w("  |]\n")

    w("""let frame_of_tag (tag : string) : frame option =
  let rec go (l : frame list) =
    match l with
    | [] -> None
    | (f : frame) :: rest -> if f.tag = tag then Some f else go rest
  in
  go (Array.to_list frames)

(** Every frame on one sheet, in registry order.

    The sheet's frames are contiguous in the file, so this is a scan rather than
    an index - and a scan is what keeps [frames] a plain array that can be read
    straight out of the registry. *)
let frames_on (sheet : string) : frame array =
  Array.of_list
    (List.filter (fun (f : frame) -> f.sheet = sheet) (Array.to_list frames))

(** The scale a frame is meant to be drawn at, as a numerator and a denominator.

    Returns 1,1 when the frame is drawn at its stored size, which is the common
    case. The red glows are the exception: 88x88 stored, 64x64 drawn. *)
let draw_scale (f : frame) : int * int =
  if f.dest_w = f.w then (1, 1)
  else
    let rec gcd a b = if b = 0 then a else gcd b (a mod b) in
    let g = gcd f.w f.dest_w in
    (f.dest_w / g, f.w / g)
""")
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--zip", type=pathlib.Path, default=REPO / "game" / "Assets.zip")
    ap.add_argument("--out", type=pathlib.Path, default=OUT)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed file differs")
    args = ap.parse_args()

    if not args.zip.is_file():
        print(f"error: {args.zip} not found", file=sys.stderr)
        return 1
    try:
        with zipfile.ZipFile(args.zip) as z:
            raw = z.read(REGISTRY).decode("utf-8")
    except (zipfile.BadZipFile, KeyError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    sheets = [(m.group(1), m.group(2)) for m in SHEET_RE.finditer(raw)]
    frames = [attrs(m.group(1)) for m in FRAME_RE.finditer(raw)]
    known = {t for t, _ in sheets}
    orphans = [f["tag"] for f in frames if f["bitmap"] not in known]
    if not sheets or not frames:
        print("error: registry parsed empty", file=sys.stderr)
        return 1

    print(f"  {len(sheets)} sheets, {len(frames)} named frames")
    if orphans:
        # Not fatal: the registry references sheets this parse did not see, and the
        # port only needs the ones it draws. Worth printing rather than dropping.
        print(f"  note: {len(orphans)} frames name an unseen sheet, e.g. "
              f"{', '.join(orphans[:3])}", file=sys.stderr)

    text = render(sheets, frames)

    if args.check:
        if not args.out.is_file():
            print(f"error: {args.out} missing", file=sys.stderr)
            return 1
        if args.out.read_text(encoding="utf-8") != text:
            print(f"error: {args.out} is stale, re-run tools/extract_skin_data.py",
                  file=sys.stderr)
            return 1
        print("  up to date")
        return 0

    args.out.write_text(text, encoding="utf-8")
    print(f"  wrote {args.out} ({len(text):,d} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())