#!/usr/bin/env python3
"""
Extract campaign map data: Cities, Roads, Waypoints, Ruins.
Generates lib/campaign_map.ml with typed data structures.
"""

import xml.etree.ElementTree as ET
from pathlib import Path
import sys

BASE = Path("game/Assets/Assets")

def parse_city(xml_path):
    tree = ET.parse(xml_path)
    root = tree.getroot()
    cid = root.get("id")
    text = root.find("Text")
    graphics = root.find("Graphics")
    data = root.find("Data")
    items = [it.get("tag") for it in root.findall("Item")]
    spells = [sp.get("tag") for sp in root.findall("Spell")]
    return {
        "id": cid,
        "name_text": text.get("name") if text is not None else "",
        "desc_text": text.get("description") if text is not None else "",
        "icon": int(graphics.get("icon")) if graphics is not None else 0,
        "gfx_type": int(graphics.get("type")) if graphics is not None else 0,
        "x": int(data.get("x")) if data is not None else 0,
        "y": int(data.get("y")) if data is not None else 0,
        "level": int(data.get("level")) if data is not None else 0,
        "visible": data.get("visible") == "yes" if data is not None else False,
        "income": int(data.get("income")) if data is not None else 0,
        "items": items,
        "spells": spells,
    }

def parse_waypoint(xml_path):
    tree = ET.parse(xml_path)
    root = tree.getroot()
    # Waypoints.xml has multiple Waypoint elements
    wps = []
    for wp in root.findall("Waypoint"):
        wps.append({
            "id": wp.get("id"),
            "name_text": wp.get("name"),
            "desc_text": wp.get("description"),
            "x": int(wp.get("x")),
            "y": int(wp.get("y")),
            "type": int(wp.get("type")),
            "icon": int(wp.get("icon")),
            "visible": wp.get("visible") == "yes",
        })
    return wps

def parse_roads(xml_path):
    tree = ET.parse(xml_path)
    root = tree.getroot()
    roads = []
    for rd in root.findall("Road"):
        roads.append({
            "start": rd.get("start"),
            "end_": rd.get("end"),
            "visible": rd.get("visible") == "yes",
        })
    return roads

def parse_ruin(xml_path):
    tree = ET.parse(xml_path)
    root = tree.getroot()
    rid = root.get("id")
    text = root.find("Text")
    graphics = root.find("Graphics")
    data = root.find("Data")
    return {
        "id": rid,
        "name_text": text.get("name") if text is not None else "",
        "desc_text": text.get("description") if text is not None else "",
        "icon": int(graphics.get("icon")) if graphics is not None else 0,
        "x": int(data.get("x")) if data is not None else 0,
        "y": int(data.get("y")) if data is not None else 0,
        "ruin_type": int(data.get("type")) if data is not None else 0,
        "visible": data.get("visible") == "yes" if data is not None else False,
        "attach": data.get("attach") if data is not None else "",
    }

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Validate only")
    parser.add_argument("--output", default="lib/campaign_map.ml")
    args = parser.parse_args()

    cities = []
    for xml in sorted((BASE / "Cities").glob("C*.xml")):
        cities.append(parse_city(xml))

    waypoints = parse_waypoint(BASE / "Cities" / "Waypoints.xml")
    roads = parse_roads(BASE / "Cities" / "Roads.xml")
    ruins = []
    for xml in sorted((BASE / "Ruins").glob("R*.xml")):
        ruins.append(parse_ruin(xml))

    if args.check:
        print(f"Cities: {len(cities)}")
        print(f"Waypoints: {len(waypoints)}")
        print(f"Roads: {len(roads)}")
        print(f"Ruins: {len(ruins)}")
        # Basic validation
        all_nodes = {c["id"] for c in cities} | {w["id"] for w in waypoints} | {r["id"] for r in ruins}
        for rd in roads:
            if rd["start"] not in all_nodes:
                print(f"WARNING: road start {rd['start']} not a known node")
            if rd["end_"] not in all_nodes:
                print(f"WARNING: road end {rd['end_']} not a known node")
        for r in ruins:
            if r["attach"] and r["attach"] not in all_nodes:
                print(f"WARNING: ruin {r['id']} attaches to unknown {r['attach']}")
        return

    # Generate OCaml
    lines = []
    lines.append("(* Generated by tools/extract_campaign_map.py — do not edit *)")
    lines.append("")
    lines.append("type node_kind = City | Waypoint | Ruin")
    lines.append("")
    lines.append("type city = {")
    lines.append("  id: string;")
    lines.append("  name_text: string;")
    lines.append("  desc_text: string;")
    lines.append("  icon: int;")
    lines.append("  gfx_type: int;")
    lines.append("  x: int;")
    lines.append("  y: int;")
    lines.append("  level: int;")
    lines.append("  visible: bool;")
    lines.append("  income: int;")
    lines.append("  items: string list;")
    lines.append("  spells: string list;")
    lines.append("}")
    lines.append("")
    lines.append("type waypoint = {")
    lines.append("  id: string;")
    lines.append("  name_text: string;")
    lines.append("  desc_text: string;")
    lines.append("  x: int;")
    lines.append("  y: int;")
    lines.append("  wtype: int;")
    lines.append("  icon: int;")
    lines.append("  visible: bool;")
    lines.append("}")
    lines.append("")
    lines.append("type ruin = {")
    lines.append("  id: string;")
    lines.append("  name_text: string;")
    lines.append("  desc_text: string;")
    lines.append("  icon: int;")
    lines.append("  x: int;")
    lines.append("  y: int;")
    lines.append("  ruin_type: int;")
    lines.append("  visible: bool;")
    lines.append("  attach: string;")
    lines.append("}")
    lines.append("")
    lines.append("type road = {")
    lines.append("  start: string;")
    lines.append("  end_: string;")
    lines.append("  visible: bool;")
    lines.append("}")
    lines.append("")

    # Cities
    lines.append("let cities : city list = [")
    for c in cities:
        lines.append("  {")
        lines.append(f'    id = "{c["id"]}";')
        lines.append(f'    name_text = "{c["name_text"]}";')
        lines.append(f'    desc_text = "{c["desc_text"]}";')
        lines.append(f'    icon = {c["icon"]};')
        lines.append(f'    gfx_type = {c["gfx_type"]};')
        lines.append(f'    x = {c["x"]};')
        lines.append(f'    y = {c["y"]};')
        lines.append(f'    level = {c["level"]};')
        lines.append(f'    visible = {str(c["visible"]).lower()};')
        lines.append(f'    income = {c["income"]};')
        items_str = "[ " + "; ".join([f'"{s}"' for s in c["items"]]) + " ]"
        lines.append(f'    items = {items_str};')
        spells_str = "[ " + "; ".join([f'"{s}"' for s in c["spells"]]) + " ]"
        lines.append(f'    spells = {spells_str};')
        lines.append("  };")
    lines.append("]")
    lines.append("")

    # Waypoints
    lines.append("let waypoints : waypoint list = [")
    for w in waypoints:
        lines.append("  {")
        lines.append(f'    id = "{w["id"]}";')
        lines.append(f'    name_text = "{w["name_text"]}";')
        lines.append(f'    desc_text = "{w["desc_text"]}";')
        lines.append(f'    x = {w["x"]};')
        lines.append(f'    y = {w["y"]};')
        lines.append(f'    wtype = {w["type"]};')
        lines.append(f'    icon = {w["icon"]};')
        lines.append(f'    visible = {str(w["visible"]).lower()};')
        lines.append("  };")
    lines.append("]")
    lines.append("")

    # Ruins
    lines.append("let ruins : ruin list = [")
    for r in ruins:
        lines.append("  {")
        lines.append(f'    id = "{r["id"]}";')
        lines.append(f'    name_text = "{r["name_text"]}";')
        lines.append(f'    desc_text = "{r["desc_text"]}";')
        lines.append(f'    icon = {r["icon"]};')
        lines.append(f'    x = {r["x"]};')
        lines.append(f'    y = {r["y"]};')
        lines.append(f'    ruin_type = {r["ruin_type"]};')
        lines.append(f'    visible = {str(r["visible"]).lower()};')
        lines.append(f'    attach = "{r["attach"]}";')
        lines.append("  };")
    lines.append("]")
    lines.append("")

    # Roads
    lines.append("let roads : road list = [")
    for rd in roads:
        lines.append(f'  {{ start = "{rd["start"]}"; end_ = "{rd["end_"]}"; visible = {str(rd["visible"]).lower()} }};')
    lines.append("]")
    lines.append("")

    # Lookup helpers
    lines.append("let city_by_id (id: string) : city = List.find (fun (c: city) -> c.id = id) cities")
    lines.append("let waypoint_by_id (id: string) : waypoint = List.find (fun (w: waypoint) -> w.id = id) waypoints")
    lines.append("let ruin_by_id (id: string) : ruin = List.find (fun (r: ruin) -> r.id = id) ruins")
    lines.append("")
    lines.append("let roads_from (node: string) : road list = List.filter (fun (r: road) -> r.start = node) roads")
    lines.append("let roads_to (node: string) : road list = List.filter (fun (r: road) -> r.end_ = node) roads")
    lines.append("let roads_connected (node: string) : road list =")
    lines.append("  List.filter (fun (r: road) -> r.start = node || r.end_ = node) roads")
    lines.append("")
    lines.append("let node_position (kind: node_kind) (id: string) : (int * int) =")
    lines.append("  match kind with")
    lines.append("  | City -> (let c = city_by_id id in (c.x, c.y))")
    lines.append("  | Waypoint -> (let w = waypoint_by_id id in (w.x, w.y))")
    lines.append("  | Ruin -> (let r = ruin_by_id id in (r.x, r.y))")
    lines.append("")

    output = "\n".join(lines)
    Path(args.output).write_text(output)
    print(f"Wrote {args.output}")

if __name__ == "__main__":
    main()