#!/usr/bin/env python3
"""
Extract Quests: XML metadata + Lua scripts + localized text.
Generates lib/campaign_quests.ml
"""

import xml.etree.ElementTree as ET
from pathlib import Path
import sys

BASE = Path("game/Assets/Assets/Quests")
TEXT_BASE = Path("game/Assets/English/Quests")

def parse_quest_text(xml_path):
    """Parse the localized text XML for a quest."""
    if not xml_path.exists():
        return {}
    tree = ET.parse(xml_path)
    root = tree.getroot()
    texts = {}
    for text_elem in root.findall("Text"):
        tag = text_elem.get("tag")
        content = text_elem.text or ""
        texts[tag] = content
    return texts

def parse_quest(xml_path):
    tree = ET.parse(xml_path)
    root = tree.getroot()
    qid = root.get("id")
    text_elem = root.find("Text")
    script_elem = root.find("Script")
    data_elem = root.find("Data")
    avail_elem = root.find("Available")
    battle_elem = root.find("Battle")

    # Load localized text
    text_file = text_elem.get("file") if text_elem is not None else None
    texts = parse_quest_text(TEXT_BASE / text_file) if text_file else {}

    lua_path = BASE / script_elem.get("file").replace("\\", "/") if script_elem is not None else None
    lua_source = lua_path.read_text(encoding="utf-8") if lua_path and lua_path.exists() else ""

    return {
        "id": qid,
        "name_text": text_elem.get("name") if text_elem is not None else "",
        "desc_text": text_elem.get("description") if text_elem is not None else "",
        "group": text_elem.get("group") if text_elem is not None else "",
        "text_file": text_file if text_file else "",
        "texts": texts,
        "lua_file": script_elem.get("file") if script_elem is not None else "",
        "lua_object": script_elem.get("object") if script_elem is not None else "",
        "lua_source": lua_source,
        "abandonable": data_elem.get("abandon") == "yes" if data_elem is not None else False,
        "icon": int(data_elem.get("icon")) if data_elem is not None else 0,
        "important": data_elem.get("important") == "yes" if data_elem is not None else False,
        "avail_location": avail_elem.get("location") if avail_elem is not None else "",
        "avail_minlevel": int(avail_elem.get("minlevel")) if avail_elem is not None else 0,
        "avail_maxlevel": int(avail_elem.get("maxlevel")) if avail_elem is not None else 1000,
        "avail_repeat": int(avail_elem.get("repeat")) if avail_elem is not None else 0,
        "avail_donequest0": avail_elem.get("donequest0") if avail_elem is not None else "",
        "avail_donequest1": avail_elem.get("donequest1") if avail_elem is not None else "",
        "avail_donequest2": avail_elem.get("donequest2") if avail_elem is not None else "",
        "avail_notdonequest": avail_elem.get("notdonequest") if avail_elem is not None else "",
        "avail_notactivequest": avail_elem.get("notactivequest") if avail_elem is not None else "",
        "avail_companion0": avail_elem.get("companion0") if avail_elem is not None else "",
        "avail_companion1": avail_elem.get("companion1") if avail_elem is not None else "",
        "avail_notcompanion": avail_elem.get("notcompanion") if avail_elem is not None else "",
        "avail_item": avail_elem.get("item") if avail_elem is not None else "",
        "avail_notitem": avail_elem.get("notitem") if avail_elem is not None else "",
        "avail_award": avail_elem.get("award") if avail_elem is not None else "",
        "avail_notaward": avail_elem.get("notaward") if avail_elem is not None else "",
        "battle_monster": battle_elem.get("monster") if battle_elem is not None else "",
        "battle_spells": [sp.get("id") for sp in battle_elem.findall("Spell")] if battle_elem is not None else [],
    }

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", default="lib/campaign_quests.ml")
    args = parser.parse_args()

    quests = []
    for xml in sorted(BASE.glob("Q*.xml")):
        quests.append(parse_quest(xml))

    if args.check:
        print(f"Quests: {len(quests)}")
        for q in quests:
            print(f"  {q['id']}: {q['name_text']} avail@{q['avail_location']} lvl{q['avail_minlevel']}-{q['avail_maxlevel']} monster={q['battle_monster']} spells={q['battle_spells']}")
            if q['texts']:
                for tag, txt in q['texts'].items():
                    print(f"    {tag}: {txt[:60]}")
        return

    lines = []
    lines.append("(* Generated by tools/extract_quests.py — do not edit *)")
    lines.append("")
    lines.append("type quest = {")
    lines.append("  id: string;")
    lines.append("  name_text: string;")
    lines.append("  desc_text: string;")
    lines.append("  group: string;")
    lines.append("  text_file: string;")
    lines.append("  texts: (string * string) list;")
    lines.append("  lua_file: string;")
    lines.append("  lua_object: string;")
    lines.append("  lua_source: string;")
    lines.append("  abandonable: bool;")
    lines.append("  icon: int;")
    lines.append("  important: bool;")
    lines.append("  avail_location: string;")
    lines.append("  avail_minlevel: int;")
    lines.append("  avail_maxlevel: int;")
    lines.append("  avail_repeat: int;")
    lines.append("  avail_donequest0: string;")
    lines.append("  avail_donequest1: string;")
    lines.append("  avail_donequest2: string;")
    lines.append("  avail_notdonequest: string;")
    lines.append("  avail_notactivequest: string;")
    lines.append("  avail_companion0: string;")
    lines.append("  avail_companion1: string;")
    lines.append("  avail_notcompanion: string;")
    lines.append("  avail_item: string;")
    lines.append("  avail_notitem: string;")
    lines.append("  avail_award: string;")
    lines.append("  avail_notaward: string;")
    lines.append("  battle_monster: string;")
    lines.append("  battle_spells: string list;")
    lines.append("}")
    lines.append("")

    lines.append("let quests = [")
    for q in quests:
        lua_escaped = q["lua_source"].replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "")
        texts_list = "[" + "; ".join([f'("{k}", "{v.replace("\\", "\\\\").replace(chr(34), chr(92)+chr(34)).replace(chr(10), "\\n")}")' for k, v in q["texts"].items()]) + "]"
        lines.append("  {")
        lines.append(f'    id = "{q["id"]}";')
        lines.append(f'    name_text = "{q["name_text"]}";')
        lines.append(f'    desc_text = "{q["desc_text"]}";')
        lines.append(f'    group = "{q["group"]}";')
        lines.append(f'    text_file = "{q["text_file"].replace(chr(92), chr(92)+chr(92))}";')
        lines.append(f"    texts = {texts_list};")
        lines.append(f'    lua_file = "{q["lua_file"].replace(chr(92), chr(92)+chr(92))}";')
        lines.append(f'    lua_object = "{q["lua_object"]}";')
        lines.append(f'    lua_source = "{lua_escaped}";')
        lines.append(f'    abandonable = {str(q["abandonable"]).lower()};')
        lines.append(f'    icon = {q["icon"]};')
        lines.append(f'    important = {str(q["important"]).lower()};')
        lines.append(f'    avail_location = "{q["avail_location"]}";')
        lines.append(f'    avail_minlevel = {q["avail_minlevel"]};')
        lines.append(f'    avail_maxlevel = {q["avail_maxlevel"]};')
        lines.append(f'    avail_repeat = {q["avail_repeat"]};')
        lines.append(f'    avail_donequest0 = "{q["avail_donequest0"]}";')
        lines.append(f'    avail_donequest1 = "{q["avail_donequest1"]}";')
        lines.append(f'    avail_donequest2 = "{q["avail_donequest2"]}";')
        lines.append(f'    avail_notdonequest = "{q["avail_notdonequest"]}";')
        lines.append(f'    avail_notactivequest = "{q["avail_notactivequest"]}";')
        lines.append(f'    avail_companion0 = "{q["avail_companion0"]}";')
        lines.append(f'    avail_companion1 = "{q["avail_companion1"]}";')
        lines.append(f'    avail_notcompanion = "{q["avail_notcompanion"]}";')
        lines.append(f'    avail_item = "{q["avail_item"]}";')
        lines.append(f'    avail_notitem = "{q["avail_notitem"]}";')
        lines.append(f'    avail_award = "{q["avail_award"]}";')
        lines.append(f'    avail_notaward = "{q["avail_notaward"]}";')
        lines.append(f'    battle_monster = "{q["battle_monster"]}";')
        spells_str = "[ " + "; ".join([f'"{s}"' for s in q["battle_spells"]]) + " ]"
        lines.append(f'    battle_spells = {spells_str};')
        lines.append("  };")
    lines.append("]")
    lines.append("")

    lines.append("let quest_by_id id = List.find (fun q -> q.id = id) quests")
    lines.append("let quests_at_location loc = List.filter (fun q -> q.avail_location = loc) quests")
    lines.append("")

    Path(args.output).write_text("\n".join(lines))
    print(f"Wrote {args.output}")

if __name__ == "__main__":
    main()