#!/usr/bin/env python3
"""Generate lib/text_data.ml from the game's global text libraries.

Every string the game shows that is not owned by one particular asset lives in a
TextLibrary: one XML file per subject, all of them `<Text tag="...">value</Text>`
entries under a `<TextLibrary>` root. Five languages, each with the same fifteen
files and the same 2638 entries:

    English/StandardQuestsText.xml    quest titles and descriptions
    English/StandardSitesText.xml     city names, waypoint and ruin names
    English/StandardItemsText.xml     item names and descriptions
    English/StandardMonstersText.xml  monster names, descriptions, capture text
    English/StandardSpellsText.xml    spell names and descriptions
    English/StandardProfessionsText.xml  the four classes
    English/StandardAwardsText.xml    award names
    English/StandardCompanionsText.xml   companion names and dialogue
    English/StandardRumorsText.xml    tavern rumors
    English/StandardQuestGroupsText.xml   quest group headings
    English/StandardStatusEffectsText.xml status effect names
    English/StandardSpellEffectsText.xml  spell effect school names
    English/GameText.xml              interface strings
    English/RunesText.xml             rune mini-game text
    English/TutorialsText.xml         tutorial panels

This matters because the per-asset extracts do not carry these strings. A quest's
own `*_Text.xml` holds its ACTION/FIRST/STEP lines but not `[QUEST_X_NAME]`, and
`campaign_map.ml` stores `[CITY_CBAR_NAME]` rather than "Bartonia" - so without
this table every name in the game prints as a tag. (Checked: all 454 `name_text`
and 294 `desc_text` tags the campaign modules reference resolve here.)

Duplicate tags: 7 of the 2630, six of them with identical values. Later entries
overwrite earlier ones, which is what a map built by parsing in order does. The
one tag whose two values differ is `[DEMO_HERO_LIMIT]` - two spellings of the
trial-mode limit message - and nothing in the port reads it.

    python tools/extract_text_tables.py                  # -> lib/text_data.ml
    python tools/extract_text_tables.py --language French
    python tools/extract_text_tables.py --check          # fail if stale
"""

from __future__ import annotations

import argparse
import pathlib
import sys
import xml.etree.ElementTree as ET

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "lib" / "text_data.ml"
ASSETS = REPO / "game" / "Assets"

LANGUAGES = ("English", "French", "German", "Italian", "Spanish")


def ocaml_string(s: str) -> str:
    """An OCaml string literal. The tables carry real newlines and quotes."""
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append("\\%03d" % ord(ch))
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def load(language: str) -> tuple[dict[str, str], list[str], int, int]:
    """All TextLibrary files for one language.

    Returns (tag -> text, file names in order, entry count, duplicate tags).
    Later entries win; files are read in sorted name order so the result does not
    depend on the filesystem.
    """
    lang_dir = ASSETS / language
    if not lang_dir.is_dir():
        raise SystemExit(f"error: {lang_dir} not found")
    files = sorted(lang_dir.glob("*Text.xml"))
    if not files:
        raise SystemExit(f"error: no *Text.xml under {lang_dir}")

    table: dict[str, str] = {}
    entries = 0
    dupes: set[str] = set()
    for path in files:
        root = ET.parse(path).getroot()
        for node in root.findall("Text"):
            tag = node.get("tag")
            if tag is None:
                continue
            entries += 1
            if tag in table:
                dupes.add(tag)
            table[tag] = node.text or ""
    return table, [p.name for p in files], entries, len(dupes)


def render(table: dict[str, str], language: str, files: list[str],
           entries: int, dupes: int) -> str:
    lines = [
        "(* Generated by tools/extract_text_tables.py - do not edit. *)",
        "",
        f"(* The {language} TextLibrary: {len(table):,} tags from {len(files)} files",
        "   under game/Assets/%s/ - the Standard*Text tables with GameText," % language,
        "   RunesText and TutorialsText.",
        "",
        "   These are the strings no per-asset extract carries. A quest's own text",
        "   file has its step lines but not [QUEST_X_NAME]; campaign_map stores",
        "   [CITY_CBAR_NAME], not \"Bartonia\". Anything that shows a name resolves",
        "   the tag here first and falls back to the tag itself, so a missing string",
        "   reads as a tag rather than raising.",
        "",
        f"   {entries} entries read, {dupes} tags seen twice; later entries won. *)",
        "",
        "let entries : (string * string) list = [",
    ]
    for tag in sorted(table):
        lines.append(f"  {ocaml_string(tag)}, {ocaml_string(table[tag])};")
    lines += [
        "]",
        "",
        "let table : (string, string) Hashtbl.t = Hashtbl.create 4096",
        "let () = List.iter (fun (k, v) -> Hashtbl.replace table k v) entries",
        "",
        "let lookup (tag : string) : string option = Hashtbl.find_opt table tag",
        "",
        "let text (tag : string) : string =",
        "  match lookup tag with Some s -> s | None -> tag",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--language", default="English", choices=LANGUAGES,
                    help="whose text libraries to extract")
    ap.add_argument("--out", type=pathlib.Path, default=OUT)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed file differs")
    args = ap.parse_args()

    table, files, entries, dupes = load(args.language)
    if not table:
        print("error: tables parsed empty", file=sys.stderr)
        return 1
    print(f"  {args.language}: {len(table):,} tags from {len(files)} files "
          f"({entries} entries, {dupes} duplicated)")

    text = render(table, args.language, files, entries, dupes)

    if args.check:
        if not args.out.is_file():
            print(f"error: {args.out} missing", file=sys.stderr)
            return 1
        if args.out.read_text(encoding="utf-8") != text:
            print(f"error: {args.out} is stale, re-run tools/extract_text_tables.py",
                  file=sys.stderr)
            return 1
        print("  up to date")
        return 0

    args.out.write_text(text, encoding="utf-8")
    print(f"  wrote {args.out} ({len(text):,d} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
