$ErrorActionPreference = 'Stop'

# Regenerates lib/status_effect_data.ml from the game's own assets.
#
# One source:
#   * Assets/StatusEffects/*.xml    id, icon, Data duration, Data stack, and the
#                                   companion script's object name
#
# The XML is pure data. The behaviour is in the companion .lua, which is
# hand-ported into lib/status_effect_hooks.ml - the same split as spells and
# items.
#
# The id is the important field and it is worth being explicit about why. The
# engine keys status effects on the XML id, never on the script's name: the Lua
# constants in Assets/Scripts/StandardConstants.lua are string aliases
#
#     STATUS_EFFECT_HIDDEN = "EHID";
#
# and every HAS_STATUS_EFFECT / ADD_STATUS_EFFECT comparison is against that
# string. The script object name ("Hidden") is a Lua table name and appears in
# no comparison anywhere. Storing the friendly name in combatant.effects, which
# an earlier revision of lib/spell_effects.ml did, means no effect can ever
# match a descriptor and none of them fire.

$assets = 'game\Assets.zip'
if (-not (Test-Path $assets)) { throw "missing $assets" }

Add-Type -AssemblyName System.IO.Compression.FileSystem
$z = [System.IO.Compression.ZipFile]::OpenRead($assets)

function Read-Entry($zip, $name) {
  $e = $zip.Entries | Where-Object { $_.FullName -eq $name }
  if (-not $e) { return $null }
  $sr = New-Object System.IO.StreamReader($e.Open())
  $t = $sr.ReadToEnd()
  $sr.Close()
  return $t
}

function Attr($xml, $tag, $attr) {
  $m = [regex]::Match($xml, ('<' + $tag + '\b[^>]*\b' + $attr + '="([^"]*)"'))
  if ($m.Success) { return $m.Groups[1].Value }
  return $null
}

# STATUS_EFFECT_* -> id, so the report can say which constant maps where and a
# mismatch between the two tables shows up as a gap rather than as silence.
$const = @{}
$constants = Read-Entry $z 'Assets/Scripts/StandardConstants.lua'
foreach ($m in [regex]::Matches($constants, '(STATUS_EFFECT_\w+)\s*=\s*"([^"]+)"')) {
  $const[$m.Groups[2].Value] = $m.Groups[1].Value
}

$entries = @{}

foreach ($e in $z.Entries) {
  if ($e.FullName -match '^Assets/StatusEffects/([A-Za-z]+)\.xml$') {
    $name = $Matches[1]
    $sr = New-Object System.IO.StreamReader($e.Open())
    $xml = $sr.ReadToEnd()
    $sr.Close()

    $dataXml = [regex]::Match($xml, '<Data\b[^>]*/>').Value
    $iconXml = [regex]::Match($xml, '<Graphics\b[^>]*/>').Value
    $scriptXml = [regex]::Match($xml, '<Script\b[^>]*/>').Value

    $id = Attr $xml 'StatusEffect' 'id'
    if (-not $id) { throw "no id in $($e.FullName)" }

    $entries[$id] = [pscustomobject]@{
      id = $id
      name = $name
      duration = [int](Attr $dataXml 'Data' 'duration')
      stack = [int](Attr $dataXml 'Data' 'stack')
      icon = [int](Attr $iconXml 'Graphics' 'icon')
      script = [System.IO.Path]::GetFileName((Attr $scriptXml 'Script' 'file'))
    }
  }
}
$z.Dispose()

$ids = $entries.Keys | Sort-Object

$rows = New-Object System.Collections.Generic.List[string]
foreach ($id in $ids) {
  $d = $entries[$id]
  $rows.Add(('  {{ id = "{0}"; name = "{1}"; duration = {2}; stack = {3}; icon = {4};' -f `
    $d.id, $d.name, $d.duration, $d.stack, $d.icon))
  $rows.Add(('    script = "{0}"; hooks = no_hooks }};' -f $d.script))
}

$hdr = @(
  '(** Generated by tools/extract_status_effects.ps1. Do not edit by hand.'
  ''
  '    The status effect descriptors, parsed from [Assets/StatusEffects/*.xml]:'
  '    the id, the icon, [Data duration] and [Data stack], and the companion'
  '    script''s file and object name.'
  ''
  '    [id] is the identity the engine uses. It is {e not} [name]: the Lua tables'
  '    are called Hidden and WallOfFired, but the constants in'
  '    [Assets/Scripts/StandardConstants.lua] are string aliases for the ids -'
  ''
  '        STATUS_EFFECT_HIDDEN = "EHID";'
  ''
  '    and every [HAS_STATUS_EFFECT] and [ADD_STATUS_EFFECT] comparison is against'
  '    that string. Nothing in the game ever compares a script name. So the ids'
  '    are what [Combatant.effects] must hold, and [name] is kept only so a log'
  '    line or a test can read as English.'
  ''
  '    Three of these have [duration = 0], which is not "expired immediately" but'
  '    "indefinite": Hidden, WallOfFired and WallOfThornsed each cancel themselves'
  '    by setting their own remaining duration to 1, which lapses on the next'
  '    tick. Spells that apply them pass 0 as well, so the two agree. This is'
  '    [Combat.tick_duration]''s first branch, [if (duration < 1) return 1].'
  ''
  '    Every [hooks] here is [no_hooks]. The behaviour lives in the companion'
  '    .lua and is hand-ported into [Status_effect_hooks], which is what'
  '    [Status_effect_hooks.descriptors] is for - it maps over this list and'
  '    attaches the bodies. Keeping generation independent of the port means a'
  '    transcription mistake cannot corrupt the data half. *)'
  ''
  'open Combat'
  ''
  'let descriptors : effect_def list = ['
)
$tail = @(
  ']'
  ''
  'let descriptor_of (id : string) : effect_def option ='
  '  List.find_opt (fun (d : effect_def) -> d.id = id) descriptors'
  ''
  '(** The Lua table name for an id, for logs and failure messages. [None] for an'
  '    id that is not one of the seventeen, which includes the model''s own'
  '    [Missed] pseudo-status - see [Combat.miss_turns]. *)'
  'let name_of (id : string) : string option ='
  '  List.find_opt (fun (d : effect_def) -> d.id = id) descriptors'
  '  |> Option.map (fun (d : effect_def) -> d.name)'
)
$all = New-Object System.Collections.Generic.List[string]
foreach ($line in $hdr) { $all.Add($line) }
foreach ($line in $rows) { $all.Add($line) }
foreach ($line in $tail) { $all.Add($line) }
$path = 'lib\status_effect_data.ml'
[System.IO.File]::WriteAllLines((Join-Path (Get-Location) $path), $all, (New-Object System.Text.UTF8Encoding($false)))

Write-Output ('wrote {0} with {1} status effects' -f $path, $ids.Count)
Write-Output ''

# Cross-check the two tables. A STATUS_EFFECT_* constant with no XML, or an XML
# with no constant, is normal (the spells pass some ids raw), but it is worth
# seeing rather than assuming.
$missingConst = $ids | Where-Object { -not $const.ContainsKey($_) }
$missingXml = $const.Keys | Where-Object { -not $entries.ContainsKey($_) }
Write-Output ('ids with no STATUS_EFFECT_* constant (spells pass these raw): {0}' -f ($missingConst -join ', '))
Write-Output ('STATUS_EFFECT_* constants with no XML descriptor: {0}' -f ($missingXml -join ', '))
Write-Output ''
Write-Output 'indefinite (duration 0, self-cancelling):'
$ids | Where-Object { $entries[$_].duration -eq 0 } | ForEach-Object {
  $d = $entries[$_]
  Write-Output ('  {0}  {1,-16} stack {2}' -f $d.id, $d.name, $d.stack)
}
Write-Output ''
Write-Output 'stack limit above 1:'
$ids | Where-Object { $entries[$_].stack -gt 1 } | ForEach-Object {
  $d = $entries[$_]
  Write-Output ('  {0}  {1,-16} stack {2}' -f $d.id, $d.name, $d.stack)
}