#!/usr/bin/env python3
"""
Extract Companions: XML data + OnStartBattle presence from the Lua.
Generates lib/campaign_companions.ml

The ten companion scripts are hand-ported (lib/campaign_companion_hooks.ml),
so this extractor carries the data half only - ids, the text tags, home
location, portrait, and whether the script declares OnStartBattle, which is
the hook the port dispatches.
"""

import xml.etree.ElementTree as ET
from pathlib import Path
import sys

BASE = Path("game/Assets/Assets/Companions")


def parse_companion(xml_path: Path) -> dict:
    tree = ET.parse(xml_path)
    root = tree.getroot()
    cid = root.get("id")
    text = root.find("Text")
    data = root.find("Data")
    script = root.find("Script")

    def tag(name: str) -> str:
        return text.get(name, "") if text is not None else ""

    lua_file = script.get("file", "") if script is not None else ""
    lua_path = BASE / Path(lua_file.replace("\\", "/")).name
    lua_source = lua_path.read_text(encoding="utf-8") if lua_path.exists() else ""

    return {
        "id": cid,
        "name_text": tag("name"),
        "desc_text": tag("description"),
        "activate_text": tag("activate"),
        "depart_text": tag("depart"),
        "goodbye_text": tag("goodbye"),
        "race_text": tag("race"),
        "gender_text": tag("gender"),
        "flavor_text": tag("flavor"),
        "age": int(tag("age") or 0),
        "home": data.get("home", "") if data is not None else "",
        "portrait": data.get("portrait", "") if data is not None else "",
        "uses": int(data.get("uses", "0")) if data is not None else 0,
        "lua_file": lua_file,
        "lua_object": script.get("object", "") if script is not None else "",
        "on_start_battle": "function OnStartBattle" in lua_source,
    }


def ocaml_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(companions: list) -> str:
    lines = []
    lines.append("(* Generated by tools/extract_companions.py - do not edit *)")
    lines.append("")
    lines.append("type companion = {")
    for field in (
        "id", "name_text", "desc_text", "activate_text", "depart_text",
        "goodbye_text", "race_text", "gender_text", "flavor_text",
        "home", "portrait", "lua_file", "lua_object",
    ):
        lines.append(f"  {field}: string;")
    lines.append("  age: int;")
    lines.append("  uses: int;")
    lines.append("  on_start_battle: bool;")
    lines.append("}")
    lines.append("")
    lines.append("let companions = [")
    for c in companions:
        lines.append("  {")
        lines.append(f"    id = {ocaml_string(c['id'])};")
        lines.append(f"    name_text = {ocaml_string(c['name_text'])};")
        lines.append(f"    desc_text = {ocaml_string(c['desc_text'])};")
        lines.append(f"    activate_text = {ocaml_string(c['activate_text'])};")
        lines.append(f"    depart_text = {ocaml_string(c['depart_text'])};")
        lines.append(f"    goodbye_text = {ocaml_string(c['goodbye_text'])};")
        lines.append(f"    race_text = {ocaml_string(c['race_text'])};")
        lines.append(f"    gender_text = {ocaml_string(c['gender_text'])};")
        lines.append(f"    flavor_text = {ocaml_string(c['flavor_text'])};")
        lines.append(f"    home = {ocaml_string(c['home'])};")
        lines.append(f"    portrait = {ocaml_string(c['portrait'])};")
        lines.append(f"    lua_file = {ocaml_string(c['lua_file'])};")
        lines.append(f"    lua_object = {ocaml_string(c['lua_object'])};")
        lines.append(f"    age = {c['age']};")
        lines.append(f"    uses = {c['uses']};")
        lines.append(f"    on_start_battle = {str(c['on_start_battle']).lower()};")
        lines.append("  };")
    lines.append("]")
    lines.append("")
    lines.append("let companion_by_id id = List.find (fun c -> c.id = id) companions")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", default="lib/campaign_companions.ml")
    args = parser.parse_args()

    companions = [parse_companion(xml) for xml in sorted(BASE.glob("N*.xml"))]
    with_hook = sum(1 for c in companions if c["on_start_battle"])

    print(f"Companions: {len(companions)}")
    print(f"  with OnStartBattle: {with_hook}")
    for c in companions:
        print(f"  {c['id']}: {c['name_text']} home={c['home']} "
              f"hook={'yes' if c['on_start_battle'] else 'no'}")

    generated = render(companions)

    if args.check:
        try:
            existing = Path(args.output).read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"MISSING {args.output}", file=sys.stderr)
            sys.exit(1)
        if existing.replace("\r\n", "\n") != generated:
            print(f"OUT OF DATE {args.output} - rerun tools/extract_companions.py",
                  file=sys.stderr)
            sys.exit(1)
        print(f"up to date ({args.output})")
        return

    Path(args.output).write_text(generated, encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
