$ErrorActionPreference = 'Stop'

# Regenerates lib/spell_ai.ml from the 130 spell scripts.
#
# Handles the ShouldAICastSpell shapes that are mechanical:
#
#   return Std_AISpellcastingChance(N);          -> Spell.ai_spellcasting_chance ~modifier:N
#
# and nothing else. Spells whose hook does real work are listed in the output and
# left unported, so the gap is visible rather than silent. Hand-written ports of
# those go in lib/spell_ai_manual.ml.

Add-Type -AssemblyName System.IO.Compression.FileSystem
$z = [System.IO.Compression.ZipFile]::OpenRead('game\Assets.zip')

$bodies = @{}
foreach ($e in $z.Entries) {
  if ($e.FullName -match '^Assets/Spells/(S[A-Z0-9]+)\.lua$') {
    $id = $Matches[1]
    if ($id -eq 'SARC') { continue }
    $sr = New-Object System.IO.StreamReader($e.Open())
    $t = $sr.ReadToEnd()
    $sr.Close()
    $m = [regex]::Match($t, '(?s)local function ShouldAICastSpell\([^)]*\)(.*?)\nend')
    if ($m.Success) { $bodies[$id] = $m.Groups[1].Value.Trim() }
  }
}
$z.Dispose()

$rows = New-Object System.Collections.Generic.List[string]
$done = New-Object System.Collections.Generic.List[string]
$todo = New-Object System.Collections.Generic.List[string]

foreach ($id in ($bodies.Keys | Sort-Object)) {
  $flat = ($bodies[$id] -replace '\s+', ' ').Trim()
  if ($flat -match '^return Std_AISpellcastingChance\((-?\d+)\);$') {
    $n = $Matches[1]
    $rows.Add(('  ("{0}", fun ctx -> Spell.ai_spellcasting_chance_i ~modifier:({1}) ctx);' -f $id, $n))
    $done.Add(($id + ' (chance ' + $n + ')'))
  }
  elseif ($flat -match '^return (-?\d+);$') {
    # A bare constant body: SSNK returns 1 and so is always a candidate. The
    # sign matters, because these hooks return a number and the engine treats
    # anything <= 0 as a veto. See Spell.ai_spellcasting_chance.
    $n = [int]$Matches[1]
    $rows.Add(('  ("{0}", fun _ctx -> {1});' -f $id, $(if ($n -gt 0) { 'true' } else { 'false' })))
    $done.Add(($id + ' (constant ' + $n + ')'))
  }
  else {
    $todo.Add($id)
  }
}

$hdr = @(
  '(** Generated by tools/extract_spell_ai.ps1. Do not edit by hand.'
  ''
  '    Each spell''s own [ShouldAICastSpell], ported from its Lua script in'
  '    [Assets/Spells/*.lua].'
  ''
  '    Only the mechanical shapes are generated here:'
  ''
  '        return Std_AISpellcastingChance(N);'
  '        return N;'
  ''
  '    where N is an integer literal, negative included. The sign is not cosmetic:'
  '    these hooks return a number rather than a boolean, and the engine treats'
  '    anything at or below zero as a veto, so a negative constant is an'
  '    unconditional "no". That is why -15 (SCHV, SCLE, SSTL) is generated rather'
  '    than skipped.'
  ''
  '    Anything else is left unported and reported by the script, because those'
  '    bodies read the board, the caster''s mana, or its items and need'
  '    individual treatment. An absent entry means "not ported", not "always'
  '    cast": [Spell.should_ai_cast] defaults a missing hook to true, so the'
  '    unported spells currently always say yes. That is a known gap and it is'
  '    the reason [lib/spell_ai_manual.ml] exists.'
  ''
  '    [Std_AISpellcastingChance] is Lua, in'
  '    [Assets/Scripts/StandardUtilityScripts.lua], not an engine native; its'
  '    body is transcribed in [Spell.ai_spellcasting_chance]. *)'
  ''
  'let should_ai_cast_hook : (string * (Spell.ai_context -> bool)) list = ['
)
$tail = @(
  ']'
  ''
  '(** The ported hook for [id], if it has one yet.'
  ''
  '    The hand-written board-reading hooks in [Spell_ai_manual] take precedence,'
  '    since a spell can only have one hook and that file exists precisely for the'
  '    ones this script cannot express. The lookup order belongs here rather than'
  '    as an edit to the generated file, because regenerating overwrites it. *)'
  'let hook_of (id : string) : (Spell.ai_context -> bool) option ='
  '  match Spell_ai_manual.manual_hook_of id with'
  '  | Some f -> Some f'
  '  | None -> List.assoc_opt id should_ai_cast_hook'
)
$all = @($hdr) + @($rows) + @($tail)
[System.IO.File]::WriteAllLines((Join-Path (Get-Location) 'lib\spell_ai.ml'), $all, (New-Object System.Text.UTF8Encoding($false)))

Write-Output ('wrote lib\spell_ai.ml with {0} generated hooks' -f $done.Count)
Write-Output ''

# Ids covered by lib/spell_ai_manual.ml. Kept in step with that file by the
# coverage test in test/test_spell.ml, which asserts the 28.
$manual = @(
  'SBNA','SBNE','SBNF','SBNW','SBRL','SCLI','STHR','SLIS','SCLV','SFBT','SROF'
  ,'SNWR','SDDI','SFRZ','SFSK','SSCV','SDIV','STHX','SHBT','SWBU','SCTH','SDRR'
  ,'SSWM','SESK','SWTD','SIST','SSGZ','SCON'
  ,'SBAV','SFLV','SDST','SFBO','SFSH','SSOB','SSOS','SCBO','SCTO','STRM','SBST'
  ,'SSWA','SFSP','SMBU','SSSW','SSBM','SSHO','SEGZ','SGEM','SDGZ','SRGN','SCOU'
  ,'SCHL','SENR','SHAS','SHID','SHWL','SSPT','SWOF','SSBL'
  ,'SRBI','SRFC','SCHM','SBUR','SSTO','SBRA','SSOA','SPET','SWEB','SSPF','STAU'
  ,'SSWP','SVAM','SZAP','STHU'
  ,'SDUP'
)
$manualSet = New-Object System.Collections.Generic.HashSet[string]
foreach ($m in $manual) { [void]$manualSet.Add($m) }

$stillTodo = New-Object System.Collections.Generic.List[string]
foreach ($id in $todo) { if (-not $manualSet.Contains($id)) { $stillTodo.Add($id) } }
$overlap = @($todo | Where-Object { $manualSet.Contains($_) })

Write-Output 'ported by hand in lib/spell_ai_manual.ml ({0}):' -f $overlap.Count
Write-Output ('  ' + (($overlap | Sort-Object) -join ' '))
Write-Output ''
Write-Output ('NOT ported, these bodies still need individual work ({0}):' -f $stillTodo.Count)
Write-Output ('  ' + (($stillTodo | Sort-Object) -join ' '))
Write-Output ''
Write-Output ('total ported: {0} of {1}' -f ($done.Count + $manualSet.Count), ($done.Count + $todo.Count))