$ErrorActionPreference = 'Stop'

# Regenerates lib/item_data.ml from the game's own assets.
#
# Source: Assets/Items/I*.xml, 160 items, each with a paired .lua effect script.
#
# The XML carries the static descriptor: where the item goes, what it costs, how
# rare it is, and what restricts equipping it. The behaviour is in the Lua and is
# hand-ported, the same split as spells - except for the presence flag for
# OnStartBattle, which is read straight out of each script's declare table so
# the generated row records what the script itself declares.

Add-Type -AssemblyName System.IO.Compression.FileSystem
$z = [System.IO.Compression.ZipFile]::OpenRead('game\Assets.zip')

$rows = New-Object System.Collections.Generic.List[string]
$loc = @{}
$restr = @{}

function Attr($xml, $tag, $attr) {
  $m = [regex]::Match($xml, ('<' + $tag + '\b[^>]*\b' + $attr + '="([^"]*)"'))
  if ($m.Success) { return $m.Groups[1].Value }
  return $null
}

# Same thing against a bare attribute fragment, where there is no tag name to
# anchor on. The Restriction element's attributes are matched this way.
function AttrIn($fragment, $attr) {
  $m = [regex]::Match($fragment, ('\b' + $attr + '="([^"]*)"'))
  if ($m.Success) { return $m.Groups[1].Value }
  return $null
}

# The XML spells locations in lower case; the constructors are capitalised.
$locMap = @{ 'weapon' = 'Weapon'; 'head' = 'Head'; 'body' = 'Body'; 'misc' = 'Misc' }

# Skill restrictions name a skill, in the game's colour names for the four
# elemental ones and in plain English for the other three.
$skillMap = @{
  'earth' = 'SEarth'; 'fire' = 'SFire'; 'air' = 'SAir'; 'water' = 'SWater'
  'battle' = 'SBattle'; 'morale' = 'SMorale'; 'cunning' = 'SCunning'
}

# Which item scripts declare OnStartBattle in their table: IDHE and IFLH add
# mana, the four IWL* walls life. Read from the paired .lua files in a first
# pass so the descriptor rows below can carry the flag.
$startHooks = @{}
foreach ($e in $z.Entries) {
  if ($e.FullName -notmatch '^Assets/Items/(I[A-Z0-9]+)\.lua$') { continue }
  $luaId = $Matches[1]
  $sr = New-Object System.IO.StreamReader($e.Open())
  $lua = $sr.ReadToEnd()
  $sr.Close()
  if ($lua -match 'OnStartBattle\s*=\s*OnStartBattle') { $startHooks[$luaId] = $true }
}

foreach ($e in ($z.Entries | Sort-Object FullName)) {
  if ($e.FullName -notmatch '^Assets/Items/(I[A-Z0-9]+)\.xml$') { continue }
  $id = $Matches[1]
  $sr = New-Object System.IO.StreamReader($e.Open())
  $x = $sr.ReadToEnd()
  $sr.Close()

  $location = Attr $x 'Data' 'location'
  if (-not $location) { $location = 'Misc' }

  $cost = Attr $x 'Shop' 'cost'
  $rarity = Attr $x 'Shop' 'rarity'
  $icon = Attr $x 'Graphics' 'icon'

  # Restriction: none / skill / level, with the detail that goes with it.
  $rm = [regex]::Match($x, '<Restriction\b([^>]*?)/>')
  $rtype = 'none'; $rskill = $null; $rlevel = '0'
  if ($rm.Success) {
    $ra = $rm.Groups[1].Value
    $t = AttrIn $ra 'type'
    if ($t) { $rtype = $t.ToLower() }
    $s = AttrIn $ra 'skill'
    if ($s) { $rskill = $s.ToLower() }
    $l = AttrIn $ra 'level'
    if ($l) { $rlevel = $l }
  }

  if (-not $loc.ContainsKey($location)) { $loc[$location] = 0 }
  $loc[$location]++
  if (-not $restr.ContainsKey($rtype)) { $restr[$rtype] = 0 }
  $restr[$rtype]++

  # The XML names skills by colour, so map them explicitly rather than letting a
  # capitalised colour leak into the generated source.
  $skillExpr = 'None'
  if ($rtype -eq 'skill' -and $skillMap.ContainsKey($rskill)) {
    $skillExpr = 'Some Combat.' + $skillMap[$rskill]
  }
  $kind = 'RK_' + $rtype
  $sb = if ($startHooks.ContainsKey($id)) { 'true' } else { 'false' }

  $lines = @()
  $lines += ('  {{ id = "{0}"; location = Item.{1}; shop_cost = {2}; rarity = {3}; icon = {4};' -f `
      $id, $locMap[$location], $(if ($cost) { [int]$cost } else { 0 }), $(if ($rarity) { [int]$rarity } else { 0 }), $(if ($icon) { [int]$icon } else { 0 }))
  $lines += ('    restriction_kind = Item.{0}; restriction_skill = {1}; restriction_level = {2};' -f `
      $kind, $skillExpr, $rlevel)
  $lines += ('    on_start_battle = {0}; }};' -f $sb)
  $rows.Add($lines -join "`n")
}
$z.Dispose()

$hdr = @(
  '(** Generated by tools/extract_items.ps1. Do not edit by hand.'
  ''
  '    The 160 items in [Assets/Items], static descriptor only: where the item'
  '    goes, what it costs, how rare it is, its icon, and what restricts'
  '    equipping it. Behaviour lives in each item''s paired .lua script and is'
  '    hand-ported into [lib/item_hooks.ml].'
  ''
  '    [on_start_battle] is the one piece of behaviour carried here: whether the'
  '    script''s declare table exports OnStartBattle. The bodies those six items'
  '    ship are hand-ported into [Item_hooks] alongside the flag''s check.'
  ''
  '    [restriction_skill] is [Item.None] for every item whose restriction is not'
  '    a skill requirement; [Item.descriptor_of_raw] folds the pair back into a'
  '    single [restriction]. *)'
  ''
  'let raw_descriptors : Item.raw_descriptor list = ['
)
$tail = @(
  ']'
  ''
  'let descriptors : Item.descriptor list = List.map Item.descriptor_of_raw raw_descriptors'
  ''
  'let descriptor_of (id : string) : Item.descriptor option ='
  '  List.find_opt (fun (d : Item.descriptor) -> d.id = id) descriptors'
)
$all = @($hdr) + @($rows) + @($tail)
[System.IO.File]::WriteAllLines((Join-Path (Get-Location) 'lib\item_data.ml'), $all, (New-Object System.Text.UTF8Encoding($false)))

Write-Output ('wrote lib\item_data.ml with {0} items' -f $rows.Count)
Write-Output ('OnStartBattle declared by {0}: {1}' -f $startHooks.Count, (($startHooks.Keys | Sort-Object) -join ', '))
Write-Output ''
Write-Output 'location:'
$loc.GetEnumerator() | Sort-Object Value -Descending | ForEach-Object { Write-Output ('{0,5}  {1}' -f $_.Value, $_.Key) }
Write-Output ''
Write-Output 'restriction:'
$restr.GetEnumerator() | Sort-Object Value -Descending | ForEach-Object { Write-Output ('{0,5}  {1}' -f $_.Value, $_.Key) }
